/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum EAllowedDOFs implements NativeEnum<EAllowedDOFs> {

    CUSTOM(0),
    TranslationX(EAllowedDOFs_TranslationX_NATIVE()),
    TranslationY(EAllowedDOFs_TranslationY_NATIVE()),
    TranslationZ(EAllowedDOFs_TranslationZ_NATIVE()),
    RotationX(EAllowedDOFs_RotationX_NATIVE()),
    RotationY(EAllowedDOFs_RotationY_NATIVE()),
    RotationZ(EAllowedDOFs_RotationZ_NATIVE()),
    Plane2D(EAllowedDOFs_Plane2D_NATIVE()),
    All(EAllowedDOFs_All_NATIVE());

    private int value;

    private EAllowedDOFs(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public EAllowedDOFs setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public EAllowedDOFs getCustom() {
        return CUSTOM;
    }

    private static int EAllowedDOFs_TranslationX_NATIVE() {
        try {
            return (int) FFMHandles.EAllowedDOFs_TranslationX_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EAllowedDOFs_TranslationY_NATIVE() {
        try {
            return (int) FFMHandles.EAllowedDOFs_TranslationY_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EAllowedDOFs_TranslationZ_NATIVE() {
        try {
            return (int) FFMHandles.EAllowedDOFs_TranslationZ_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EAllowedDOFs_RotationX_NATIVE() {
        try {
            return (int) FFMHandles.EAllowedDOFs_RotationX_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EAllowedDOFs_RotationY_NATIVE() {
        try {
            return (int) FFMHandles.EAllowedDOFs_RotationY_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EAllowedDOFs_RotationZ_NATIVE() {
        try {
            return (int) FFMHandles.EAllowedDOFs_RotationZ_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EAllowedDOFs_Plane2D_NATIVE() {
        try {
            return (int) FFMHandles.EAllowedDOFs_Plane2D_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EAllowedDOFs_All_NATIVE() {
        try {
            return (int) FFMHandles.EAllowedDOFs_All_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle EAllowedDOFs_TranslationX_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_ealloweddofs_ealloweddofs_translationx_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EAllowedDOFs_TranslationY_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_ealloweddofs_ealloweddofs_translationy_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EAllowedDOFs_TranslationZ_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_ealloweddofs_ealloweddofs_translationz_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EAllowedDOFs_RotationX_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_ealloweddofs_ealloweddofs_rotationx_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EAllowedDOFs_RotationY_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_ealloweddofs_ealloweddofs_rotationy_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EAllowedDOFs_RotationZ_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_ealloweddofs_ealloweddofs_rotationz_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EAllowedDOFs_Plane2D_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_ealloweddofs_ealloweddofs_plane2d_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EAllowedDOFs_All_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_ealloweddofs_ealloweddofs_all_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
