/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum EBackFaceMode implements NativeEnum<EBackFaceMode> {

    CUSTOM(0), IgnoreBackFaces(EBackFaceMode_IgnoreBackFaces_NATIVE()), CollideWithBackFaces(EBackFaceMode_CollideWithBackFaces_NATIVE());

    private int value;

    private EBackFaceMode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public EBackFaceMode setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public EBackFaceMode getCustom() {
        return CUSTOM;
    }

    private static int EBackFaceMode_IgnoreBackFaces_NATIVE() {
        try {
            return (int) FFMHandles.EBackFaceMode_IgnoreBackFaces_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EBackFaceMode_CollideWithBackFaces_NATIVE() {
        try {
            return (int) FFMHandles.EBackFaceMode_CollideWithBackFaces_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle EBackFaceMode_IgnoreBackFaces_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_ebackfacemode_ebackfacemode_ignorebackfaces_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EBackFaceMode_CollideWithBackFaces_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_ebackfacemode_ebackfacemode_collidewithbackfaces_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
