/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum EConstraintType implements NativeEnum<EConstraintType> {

    CUSTOM(0), Constraint(EConstraintType_Constraint_NATIVE()), TwoBodyConstraint(EConstraintType_TwoBodyConstraint_NATIVE());

    private int value;

    private EConstraintType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public EConstraintType setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public EConstraintType getCustom() {
        return CUSTOM;
    }

    private static int EConstraintType_Constraint_NATIVE() {
        try {
            return (int) FFMHandles.EConstraintType_Constraint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EConstraintType_TwoBodyConstraint_NATIVE() {
        try {
            return (int) FFMHandles.EConstraintType_TwoBodyConstraint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle EConstraintType_Constraint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_econstrainttype_econstrainttype_constraint_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EConstraintType_TwoBodyConstraint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_econstrainttype_econstrainttype_twobodyconstraint_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
