/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum EMotionQuality implements NativeEnum<EMotionQuality> {

    CUSTOM(0), Discrete(EMotionQuality_Discrete_NATIVE()), LinearCast(EMotionQuality_LinearCast_NATIVE());

    private int value;

    private EMotionQuality(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public EMotionQuality setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public EMotionQuality getCustom() {
        return CUSTOM;
    }

    private static int EMotionQuality_Discrete_NATIVE() {
        try {
            return (int) FFMHandles.EMotionQuality_Discrete_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EMotionQuality_LinearCast_NATIVE() {
        try {
            return (int) FFMHandles.EMotionQuality_LinearCast_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle EMotionQuality_Discrete_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_emotionquality_emotionquality_discrete_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EMotionQuality_LinearCast_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_emotionquality_emotionquality_linearcast_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
