/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum EShapeColor implements NativeEnum<EShapeColor> {

    CUSTOM(0),
    EShapeColor_InstanceColor(EShapeColor_InstanceColor_NATIVE()),
    EShapeColor_ShapeTypeColor(EShapeColor_ShapeTypeColor_NATIVE()),
    EShapeColor_MotionTypeColor(EShapeColor_MotionTypeColor_NATIVE()),
    EShapeColor_SleepColor(EShapeColor_SleepColor_NATIVE()),
    EShapeColor_IslandColor(EShapeColor_IslandColor_NATIVE()),
    EShapeColor_MaterialColor(EShapeColor_MaterialColor_NATIVE());

    private int value;

    private EShapeColor(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public EShapeColor setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public EShapeColor getCustom() {
        return CUSTOM;
    }

    private static int EShapeColor_InstanceColor_NATIVE() {
        try {
            return (int) FFMHandles.EShapeColor_InstanceColor_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EShapeColor_ShapeTypeColor_NATIVE() {
        try {
            return (int) FFMHandles.EShapeColor_ShapeTypeColor_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EShapeColor_MotionTypeColor_NATIVE() {
        try {
            return (int) FFMHandles.EShapeColor_MotionTypeColor_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EShapeColor_SleepColor_NATIVE() {
        try {
            return (int) FFMHandles.EShapeColor_SleepColor_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EShapeColor_IslandColor_NATIVE() {
        try {
            return (int) FFMHandles.EShapeColor_IslandColor_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EShapeColor_MaterialColor_NATIVE() {
        try {
            return (int) FFMHandles.EShapeColor_MaterialColor_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle EShapeColor_InstanceColor_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_eshapecolor_eshapecolor_instancecolor_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EShapeColor_ShapeTypeColor_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_eshapecolor_eshapecolor_shapetypecolor_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EShapeColor_MotionTypeColor_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_eshapecolor_eshapecolor_motiontypecolor_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EShapeColor_SleepColor_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_eshapecolor_eshapecolor_sleepcolor_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EShapeColor_IslandColor_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_eshapecolor_eshapecolor_islandcolor_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EShapeColor_MaterialColor_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_eshapecolor_eshapecolor_materialcolor_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
