/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ESoftBodyConstraintColor implements NativeEnum<ESoftBodyConstraintColor> {

    CUSTOM(0), ESoftBodyConstraintColor_ConstraintType(ESoftBodyConstraintColor_ConstraintType_NATIVE()), ESoftBodyConstraintColor_ConstraintGroup(ESoftBodyConstraintColor_ConstraintGroup_NATIVE()), ESoftBodyConstraintColor_ConstraintOrder(ESoftBodyConstraintColor_ConstraintOrder_NATIVE());

    private int value;

    private ESoftBodyConstraintColor(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ESoftBodyConstraintColor setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ESoftBodyConstraintColor getCustom() {
        return CUSTOM;
    }

    private static int ESoftBodyConstraintColor_ConstraintType_NATIVE() {
        try {
            return (int) FFMHandles.ESoftBodyConstraintColor_ConstraintType_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ESoftBodyConstraintColor_ConstraintGroup_NATIVE() {
        try {
            return (int) FFMHandles.ESoftBodyConstraintColor_ConstraintGroup_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ESoftBodyConstraintColor_ConstraintOrder_NATIVE() {
        try {
            return (int) FFMHandles.ESoftBodyConstraintColor_ConstraintOrder_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle ESoftBodyConstraintColor_ConstraintType_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_esoftbodyconstraintcolor_esoftbodyconstraintcolor_constrainttype_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ESoftBodyConstraintColor_ConstraintGroup_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_esoftbodyconstraintcolor_esoftbodyconstraintcolor_constraintgroup_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ESoftBodyConstraintColor_ConstraintOrder_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_esoftbodyconstraintcolor_esoftbodyconstraintcolor_constraintorder_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
