/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum MeshShapeSettings_EBuildQuality implements NativeEnum<MeshShapeSettings_EBuildQuality> {

    CUSTOM(0), FavorRuntimePerformance(MeshShapeSettings_EBuildQuality_FavorRuntimePerformance_NATIVE()), FavorBuildSpeed(MeshShapeSettings_EBuildQuality_FavorBuildSpeed_NATIVE());

    private int value;

    private MeshShapeSettings_EBuildQuality(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public MeshShapeSettings_EBuildQuality setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public MeshShapeSettings_EBuildQuality getCustom() {
        return CUSTOM;
    }

    private static int MeshShapeSettings_EBuildQuality_FavorRuntimePerformance_NATIVE() {
        try {
            return (int) FFMHandles.MeshShapeSettings_EBuildQuality_FavorRuntimePerformance_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int MeshShapeSettings_EBuildQuality_FavorBuildSpeed_NATIVE() {
        try {
            return (int) FFMHandles.MeshShapeSettings_EBuildQuality_FavorBuildSpeed_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle MeshShapeSettings_EBuildQuality_FavorRuntimePerformance_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_meshshapesettings_ebuildquality_meshshapesettings_ebuildquality_favorruntimeperformance_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle MeshShapeSettings_EBuildQuality_FavorBuildSpeed_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_enums_meshshapesettings_ebuildquality_meshshapesettings_ebuildquality_favorbuildspeed_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
