/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum SoftBodySharedSettings_EBendType implements NativeEnum<SoftBodySharedSettings_EBendType> {

    CUSTOM(0), None(SoftBodySharedSettings_EBendType_None_NATIVE()), Distance(SoftBodySharedSettings_EBendType_Distance_NATIVE()), Dihedral(SoftBodySharedSettings_EBendType_Dihedral_NATIVE());

    private int value;

    private SoftBodySharedSettings_EBendType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public SoftBodySharedSettings_EBendType setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public SoftBodySharedSettings_EBendType getCustom() {
        return CUSTOM;
    }

    private static int SoftBodySharedSettings_EBendType_None_NATIVE() {
        try {
            return (int) FFMHandles.SoftBodySharedSettings_EBendType_None_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int SoftBodySharedSettings_EBendType_Distance_NATIVE() {
        try {
            return (int) FFMHandles.SoftBodySharedSettings_EBendType_Distance_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int SoftBodySharedSettings_EBendType_Dihedral_NATIVE() {
        try {
            return (int) FFMHandles.SoftBodySharedSettings_EBendType_Dihedral_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle SoftBodySharedSettings_EBendType_None_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_softbodysharedsettings_ebendtype_softbodysharedsettings_ebendtype_none_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle SoftBodySharedSettings_EBendType_Distance_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_softbodysharedsettings_ebendtype_softbodysharedsettings_ebendtype_distance_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle SoftBodySharedSettings_EBendType_Dihedral_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_softbodysharedsettings_ebendtype_softbodysharedsettings_ebendtype_dihedral_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
