/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.enums.EActiveEdgeMode;
import jolt.enums.ECollectFacesMode;
import jolt.math.Vec3;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class CollideSettingsBase extends NativeObject {

    private Vec3 Vec3_TEMP_GEN_0;

    static public final CollideSettingsBase NULL = CollideSettingsBase.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CollideSettingsBase(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static CollideSettingsBase native_new() {
        return new CollideSettingsBase((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public EActiveEdgeMode get_mActiveEdgeMode() {
        int value = internal_native_get_mActiveEdgeMode(native_address);
        EActiveEdgeMode[] values = EActiveEdgeMode.values();
        for (int i = 0; i < values.length; i++) {
            EActiveEdgeMode enumVal = values[i];
            if (enumVal != EActiveEdgeMode.CUSTOM && enumVal.getValue() == value)
                return enumVal;
        }
        return EActiveEdgeMode.CUSTOM.setValue(value);
    }

    public static int internal_native_get_mActiveEdgeMode(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_mActiveEdgeMode__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mActiveEdgeMode(EActiveEdgeMode mActiveEdgeMode) {
        internal_native_set_mActiveEdgeMode(native_address, mActiveEdgeMode.getValue());
    }

    public static void internal_native_set_mActiveEdgeMode(long this_addr, int mActiveEdgeMode) {
        try {
            FFMHandles.internal_native_set_mActiveEdgeMode__JI.invokeExact(this_addr, mActiveEdgeMode);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ECollectFacesMode get_mCollectFacesMode() {
        int value = internal_native_get_mCollectFacesMode(native_address);
        ECollectFacesMode[] values = ECollectFacesMode.values();
        for (int i = 0; i < values.length; i++) {
            ECollectFacesMode enumVal = values[i];
            if (enumVal != ECollectFacesMode.CUSTOM && enumVal.getValue() == value)
                return enumVal;
        }
        return ECollectFacesMode.CUSTOM.setValue(value);
    }

    public static int internal_native_get_mCollectFacesMode(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_mCollectFacesMode__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mCollectFacesMode(ECollectFacesMode mCollectFacesMode) {
        internal_native_set_mCollectFacesMode(native_address, mCollectFacesMode.getValue());
    }

    public static void internal_native_set_mCollectFacesMode(long this_addr, int mCollectFacesMode) {
        try {
            FFMHandles.internal_native_set_mCollectFacesMode__JI.invokeExact(this_addr, mCollectFacesMode);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mCollisionTolerance() {
        return internal_native_get_mCollisionTolerance(native_address);
    }

    public static float internal_native_get_mCollisionTolerance(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mCollisionTolerance__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mCollisionTolerance(float mCollisionTolerance) {
        internal_native_set_mCollisionTolerance(native_address, mCollisionTolerance);
    }

    public static void internal_native_set_mCollisionTolerance(long this_addr, float mCollisionTolerance) {
        try {
            FFMHandles.internal_native_set_mCollisionTolerance__JF.invokeExact(this_addr, mCollisionTolerance);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mPenetrationTolerance() {
        return internal_native_get_mPenetrationTolerance(native_address);
    }

    public static float internal_native_get_mPenetrationTolerance(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mPenetrationTolerance__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mPenetrationTolerance(float mPenetrationTolerance) {
        internal_native_set_mPenetrationTolerance(native_address, mPenetrationTolerance);
    }

    public static void internal_native_set_mPenetrationTolerance(long this_addr, float mPenetrationTolerance) {
        try {
            FFMHandles.internal_native_set_mPenetrationTolerance__JF.invokeExact(this_addr, mPenetrationTolerance);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 get_mActiveEdgeMovementDirection() {
        long addr = internal_native_get_mActiveEdgeMovementDirection_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = Vec3.native_new();
        Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return Vec3_TEMP_GEN_0;
    }

    public static long internal_native_get_mActiveEdgeMovementDirection_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mActiveEdgeMovementDirection_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mActiveEdgeMovementDirection(Vec3 mActiveEdgeMovementDirection) {
        internal_native_set_mActiveEdgeMovementDirection(native_address, mActiveEdgeMovementDirection.native_address);
    }

    public static void internal_native_set_mActiveEdgeMovementDirection(long this_addr, long mActiveEdgeMovementDirection_addr) {
        try {
            FFMHandles.internal_native_set_mActiveEdgeMovementDirection__JJ.invokeExact(this_addr, mActiveEdgeMovementDirection_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_collidesettingsbase_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mActiveEdgeMode__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_collidesettingsbase_get_mactiveedgemode", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mActiveEdgeMode__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_collidesettingsbase_set_mactiveedgemode", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_mCollectFacesMode__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_collidesettingsbase_get_mcollectfacesmode", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mCollectFacesMode__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_collidesettingsbase_set_mcollectfacesmode", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_mCollisionTolerance__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_collidesettingsbase_get_mcollisiontolerance", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mCollisionTolerance__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_collidesettingsbase_set_mcollisiontolerance", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_mPenetrationTolerance__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_collidesettingsbase_get_mpenetrationtolerance", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mPenetrationTolerance__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_collidesettingsbase_set_mpenetrationtolerance", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_mActiveEdgeMovementDirection_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_collidesettingsbase_get_mactiveedgemovementdirection_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mActiveEdgeMovementDirection__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_collidesettingsbase_set_mactiveedgemovementdirection", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
