/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class GroupFilter extends NativeObject {

    static private CollisionGroup CollisionGroup_TEMP_STATIC_GEN_0;

    static private CollisionGroup CollisionGroup_TEMP_STATIC_GEN_1;

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_CanCollide = java.lang.invoke.MethodType.methodType(boolean.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_CanCollide = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_BOOLEAN, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    static public final GroupFilter NULL = GroupFilter.native_new();

    @Deprecated()
    protected GroupFilter(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static GroupFilter native_new() {
        return new GroupFilter((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetRefCount() {
        return internal_native_GetRefCount(native_address);
    }

    public static int internal_native_GetRefCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetRefCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void AddRef() {
        internal_native_AddRef(native_address);
    }

    public static void internal_native_AddRef(long this_addr) {
        try {
            FFMHandles.internal_native_AddRef__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void Release() {
        internal_native_Release(native_address);
    }

    public static void internal_native_Release(long this_addr) {
        try {
            FFMHandles.internal_native_Release__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public GroupFilter() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_CanCollide = callbackLookup.findVirtual(GroupFilter.class, "internal_CanCollide", callbackMethodType_CanCollide).bindTo(this);
            upcallStub_CanCollide = callbackLinker.upcallStub(mh_CanCollide, callbackDescriptor_CanCollide, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_CanCollide.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected boolean CanCollide(CollisionGroup inGroup1, CollisionGroup inGroup2) {
        return false;
    }

    private boolean internal_CanCollide(long inGroup1_addr, long inGroup2_addr) {
        if (CollisionGroup_TEMP_STATIC_GEN_0 == null)
            CollisionGroup_TEMP_STATIC_GEN_0 = CollisionGroup.native_new();
        CollisionGroup_TEMP_STATIC_GEN_0.internal_reset(inGroup1_addr, false);
        if (CollisionGroup_TEMP_STATIC_GEN_1 == null)
            CollisionGroup_TEMP_STATIC_GEN_1 = CollisionGroup.native_new();
        CollisionGroup_TEMP_STATIC_GEN_1.internal_reset(inGroup2_addr, false);
        return CanCollide(CollisionGroup_TEMP_STATIC_GEN_0, CollisionGroup_TEMP_STATIC_GEN_1);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_CanCollide;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_CanCollide = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long CanCollide_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJ.invokeExact(this_addr, CanCollide_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_groupfilter_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetRefCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_groupfilter_getrefcount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_AddRef__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_groupfilter_addref", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Release__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_groupfilter_release", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_groupfilter_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_groupfilter_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
