/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class ObjectLayerPairFilter extends NativeObject {

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_ShouldCollide = java.lang.invoke.MethodType.methodType(boolean.class, int.class, int.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_ShouldCollide = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_BOOLEAN, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT);

    static public final ObjectLayerPairFilter NULL = ObjectLayerPairFilter.native_new();

    @Deprecated()
    protected ObjectLayerPairFilter(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ObjectLayerPairFilter native_new() {
        return new ObjectLayerPairFilter((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean ShouldCollideNative(int inLayer1, int inLayer2) {
        return internal_native_ShouldCollideNative(native_address, inLayer1, inLayer2);
    }

    public static boolean internal_native_ShouldCollideNative(long this_addr, int inLayer1, int inLayer2) {
        try {
            return (boolean) FFMHandles.internal_native_ShouldCollideNative__JII.invokeExact(this_addr, inLayer1, inLayer2);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ObjectLayerPairFilter() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_ShouldCollide = callbackLookup.findVirtual(ObjectLayerPairFilter.class, "internal_ShouldCollide", callbackMethodType_ShouldCollide).bindTo(this);
            upcallStub_ShouldCollide = callbackLinker.upcallStub(mh_ShouldCollide, callbackDescriptor_ShouldCollide, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_ShouldCollide.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected boolean ShouldCollide(int inLayer1, int inLayer2) {
        return false;
    }

    private boolean internal_ShouldCollide(int inLayer1, int inLayer2) {
        return ShouldCollide(inLayer1, inLayer2);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_ShouldCollide;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_ShouldCollide = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long ShouldCollide_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJ.invokeExact(this_addr, ShouldCollide_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_objectlayerpairfilter_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_ShouldCollideNative__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_objectlayerpairfilter_shouldcollidenative", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_objectlayerpairfilter_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_objectlayerpairfilter_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
