/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.broadphase;

import com.github.xpenatan.jParser.api.NativeObject;

public class ObjectVsBroadPhaseLayerFilter extends NativeObject {

    static public final ObjectVsBroadPhaseLayerFilter NULL = ObjectVsBroadPhaseLayerFilter.native_new();

    public ObjectVsBroadPhaseLayerFilter() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ObjectVsBroadPhaseLayerFilter(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ObjectVsBroadPhaseLayerFilter native_new() {
        return new ObjectVsBroadPhaseLayerFilter((byte) 0, (char) 0);
    }
}
