/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class CompoundShape extends Shape {

    private CompoundShapeSubShape CompoundShapeSubShape_TEMP_GEN_0;

    static public final CompoundShape NULL = CompoundShape.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CompoundShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static CompoundShape native_new() {
        return new CompoundShape((byte) 0, (char) 0);
    }

    public int GetNumSubShapes() {
        return internal_native_GetNumSubShapes(native_address);
    }

    public static int internal_native_GetNumSubShapes(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetNumSubShapes__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public CompoundShapeSubShape GetSubShape(int inIdx) {
        long addr = internal_native_GetSubShape_addr(native_address, inIdx);
        if (addr == 0)
            return CompoundShapeSubShape.NULL;
        if (CompoundShapeSubShape_TEMP_GEN_0 == null)
            CompoundShapeSubShape_TEMP_GEN_0 = CompoundShapeSubShape.native_new();
        CompoundShapeSubShape_TEMP_GEN_0.internal_reset(addr, false);
        return CompoundShapeSubShape_TEMP_GEN_0;
    }

    public static long internal_native_GetSubShape_addr(long this_addr, int inIdx) {
        try {
            return (long) FFMHandles.internal_native_GetSubShape_addr__JI.invokeExact(this_addr, inIdx);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_GetNumSubShapes__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_shape_compoundshape_getnumsubshapes", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetSubShape_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_shape_compoundshape_getsubshape_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));
    }
}
