/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

import com.github.xpenatan.jParser.api.NativeObject;

public class VehicleCollisionTester extends NativeObject {

    static public final VehicleCollisionTester NULL = VehicleCollisionTester.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VehicleCollisionTester(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static VehicleCollisionTester native_new() {
        return new VehicleCollisionTester((byte) 0, (char) 0);
    }

    public int GetRefCount() {
        return 0;
    }

    public void AddRef() {
    }

    public void Release() {
    }
}
