/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

public class WheeledVehicleController extends VehicleController {

    static public final WheeledVehicleController NULL = WheeledVehicleController.native_new();

    public WheeledVehicleController(WheeledVehicleControllerSettings inSettings, VehicleConstraint inConstraint) {
        super((byte) 1, (char) 1);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WheeledVehicleController(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static WheeledVehicleController native_new() {
        return new WheeledVehicleController((byte) 0, (char) 0);
    }

    public void SetDriverInput(float inForward, float inRight, float inBrake, float inHandBrake) {
    }

    public void SetForwardInput(float inForward) {
    }

    public float GetForwardInput() {
        return 0;
    }

    public void SetRightInput(float inRight) {
    }

    public float GetRightInput() {
        return 0;
    }

    public void SetBrakeInput(float inBrake) {
    }

    public float GetBrakeInput() {
        return 0;
    }

    public void SetHandBrakeInput(float inHandBrake) {
    }

    public float GetHandBrakeInput() {
        return 0;
    }

    public VehicleEngine GetEngine() {
        return null;
    }

    public VehicleTransmission GetTransmission() {
        return null;
    }

    public ArrayVehicleDifferentialSettings GetDifferentials() {
        return null;
    }

    public float GetDifferentialLimitedSlipRatio() {
        return 0;
    }

    public void SetDifferentialLimitedSlipRatio(float inV) {
    }

    public float GetWheelSpeedAtClutch() {
        return 0;
    }
}
