/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ESpringMode implements NativeEnum<ESpringMode> {

    CUSTOM(0), FrequencyAndDamping(ESpringMode_FrequencyAndDamping_NATIVE()), StiffnessAndDamping(ESpringMode_StiffnessAndDamping_NATIVE());

    private int value;

    private ESpringMode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ESpringMode setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ESpringMode getCustom() {
        return CUSTOM;
    }

    private static native int ESpringMode_FrequencyAndDamping_NATIVE();

    private static native int ESpringMode_StiffnessAndDamping_NATIVE();
}
