/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum SoftBodySharedSettings_ELRAType implements NativeEnum<SoftBodySharedSettings_ELRAType> {

    CUSTOM(0), None(SoftBodySharedSettings_ELRAType_None_NATIVE()), EuclideanDistance(SoftBodySharedSettings_ELRAType_EuclideanDistance_NATIVE()), GeodesicDistance(SoftBodySharedSettings_ELRAType_GeodesicDistance_NATIVE());

    private int value;

    private SoftBodySharedSettings_ELRAType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public SoftBodySharedSettings_ELRAType setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public SoftBodySharedSettings_ELRAType getCustom() {
        return CUSTOM;
    }

    private static native int SoftBodySharedSettings_ELRAType_None_NATIVE();

    private static native int SoftBodySharedSettings_ELRAType_EuclideanDistance_NATIVE();

    private static native int SoftBodySharedSettings_ELRAType_GeodesicDistance_NATIVE();
}
