/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums.natives;

import jolt.enums.*;

final public class JNI_ValidateResult {

    static native public int ValidateResult_AcceptAllContactsForThisBodyPair_NATIVE();

    static native public int ValidateResult_AcceptContact_NATIVE();

    static native public int ValidateResult_RejectContact_NATIVE();

    static native public int ValidateResult_RejectAllContactsForThisBodyPair_NATIVE();
}
