/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums.natives;

import jolt.enums.*;

final public class JNI_EStateRecorderState {

    static native public int EStateRecorderState_None_NATIVE();

    static native public int EStateRecorderState_Global_NATIVE();

    static native public int EStateRecorderState_Bodies_NATIVE();

    static native public int EStateRecorderState_Contacts_NATIVE();

    static native public int EStateRecorderState_Constraints_NATIVE();

    static native public int EStateRecorderState_All_NATIVE();
}
