/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums.natives;

import jolt.enums.*;

final public class JNI_EPathRotationConstraintType {

    static native public int EPathRotationConstraintType_Free_NATIVE();

    static native public int EPathRotationConstraintType_ConstrainAroundTangent_NATIVE();

    static native public int EPathRotationConstraintType_ConstrainAroundNormal_NATIVE();

    static native public int EPathRotationConstraintType_ConstrainAroundBinormal_NATIVE();

    static native public int EPathRotationConstraintType_ConstrainToPath_NATIVE();

    static native public int EPathRotationConstraintType_FullyConstrained_NATIVE();
}
