/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums.natives;

import jolt.enums.*;

final public class JNI_EAllowedDOFs {

    static native public int EAllowedDOFs_TranslationX_NATIVE();

    static native public int EAllowedDOFs_TranslationY_NATIVE();

    static native public int EAllowedDOFs_TranslationZ_NATIVE();

    static native public int EAllowedDOFs_RotationX_NATIVE();

    static native public int EAllowedDOFs_RotationY_NATIVE();

    static native public int EAllowedDOFs_RotationZ_NATIVE();

    static native public int EAllowedDOFs_Plane2D_NATIVE();

    static native public int EAllowedDOFs_All_NATIVE();
}
