/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.skeleton.natives;

import jolt.skeleton.*;

final public class JNI_SkeletalAnimationAnimatedJoint {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_get_mJointName_addr(long this_addr);

    public static native void internal_native_set_mJointName(long this_addr, long mJointName_addr);

    public static native long internal_native_get_mKeyframes_addr(long this_addr);

    public static native void internal_native_set_mKeyframes(long this_addr, long mKeyframes_addr);
}
