/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class VehicleCollisionTester extends NativeObject {

    static public final VehicleCollisionTester NULL = VehicleCollisionTester.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VehicleCollisionTester(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static VehicleCollisionTester native_new() {
        return new VehicleCollisionTester((byte) 0, (char) 0);
    }

    public int GetRefCount() {
        return internal_native_GetRefCount(native_address);
    }

    public static int internal_native_GetRefCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetRefCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void AddRef() {
        internal_native_AddRef(native_address);
    }

    public static void internal_native_AddRef(long this_addr) {
        try {
            FFMHandles.internal_native_AddRef__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void Release() {
        internal_native_Release(native_address);
    }

    public static void internal_native_Release(long this_addr) {
        try {
            FFMHandles.internal_native_Release__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_GetRefCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_vehiclecollisiontester_getrefcount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_AddRef__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_vehiclecollisiontester_addref", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Release__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_vehiclecollisiontester_release", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));
    }
}
