/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.body;

import com.github.xpenatan.jParser.api.NativeObject;

public class BodyFilter extends NativeObject {

    static private BodyID BodyID_TEMP_STATIC_GEN_0;

    static private Body Body_TEMP_STATIC_GEN_0;

    static public final BodyFilter NULL = BodyFilter.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected BodyFilter(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static BodyFilter native_new() {
        return new BodyFilter((byte) 0, (char) 0);
    }

    public BodyFilter() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
    }

    protected boolean ShouldCollide(BodyID inBodyID) {
        return false;
    }

    private boolean internal_ShouldCollide(long inBodyID_addr) {
        if (BodyID_TEMP_STATIC_GEN_0 == null)
            BodyID_TEMP_STATIC_GEN_0 = BodyID.native_new();
        BodyID_TEMP_STATIC_GEN_0.internal_reset(inBodyID_addr, false);
        return ShouldCollide(BodyID_TEMP_STATIC_GEN_0);
    }

    protected boolean ShouldCollideLocked(Body inBody) {
        return false;
    }

    private boolean internal_ShouldCollideLocked(long inBody_addr) {
        if (Body_TEMP_STATIC_GEN_0 == null)
            Body_TEMP_STATIC_GEN_0 = Body.native_new();
        Body_TEMP_STATIC_GEN_0.internal_reset(inBody_addr, false);
        return ShouldCollideLocked(Body_TEMP_STATIC_GEN_0);
    }

    public static native long internal_native_create_addr();
}
