/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.body;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.core.SharedMutex;
import jolt.core.MutexMask;

public class BodyLockInterface extends NativeObject {

    static public final BodyLockInterface NULL = BodyLockInterface.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected BodyLockInterface(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static BodyLockInterface native_new() {
        return new BodyLockInterface((byte) 0, (char) 0);
    }

    public Body TryGetBody(BodyID inBodyID) {
        return null;
    }

    public SharedMutex LockRead(BodyID inBodyID) {
        return null;
    }

    public void UnlockRead(SharedMutex inMutex) {
    }

    public SharedMutex LockWrite(BodyID inBodyID) {
        return null;
    }

    public void UnlockWrite(SharedMutex inMutex) {
    }

    public MutexMask GetMutexMask(IDLArrayBodyID inBodies, int inNumber) {
        return null;
    }

    public void LockRead(MutexMask inMutexMask) {
    }

    public void UnlockRead(MutexMask inMutexMask) {
    }

    public void LockWrite(MutexMask inMutexMask) {
    }

    public void UnlockWrite(MutexMask inMutexMask) {
    }
}
