/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum EBodyType implements NativeEnum<EBodyType> {

    CUSTOM(0), RigidBody(EBodyType_RigidBody_NATIVE()), SoftBody(EBodyType_SoftBody_NATIVE());

    private int value;

    private EBodyType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public EBodyType setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public EBodyType getCustom() {
        return CUSTOM;
    }

    private static native int EBodyType_RigidBody_NATIVE();

    private static native int EBodyType_SoftBody_NATIVE();
}
