/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.natives;

import jolt.physics.collision.*;

final public class JNI_CollideShapeSettings {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native float internal_native_get_mMaxSeparationDistance(long this_addr);

    public static native void internal_native_set_mMaxSeparationDistance(long this_addr, float mMaxSeparationDistance);

    public static native int internal_native_get_mBackFaceMode(long this_addr);

    public static native void internal_native_set_mBackFaceMode(long this_addr, int mBackFaceMode);
}
