/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.core.LinearCurve;

public class VehicleEngineSettings extends NativeObject {

    private LinearCurve LinearCurve_TEMP_GEN_0;

    static public final VehicleEngineSettings NULL = VehicleEngineSettings.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VehicleEngineSettings(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static VehicleEngineSettings native_new() {
        return new VehicleEngineSettings((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.vehicle.natives.JNI_VehicleEngineSettings.internal_native_deleteNative(this_addr);
    }

    public float get_mMaxTorque() {
        return internal_native_get_mMaxTorque(native_address);
    }

    public static float internal_native_get_mMaxTorque(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_VehicleEngineSettings.internal_native_get_mMaxTorque(this_addr);
    }

    public void set_mMaxTorque(float mMaxTorque) {
        internal_native_set_mMaxTorque(native_address, mMaxTorque);
    }

    public static void internal_native_set_mMaxTorque(long this_addr, float mMaxTorque) {
        jolt.physics.vehicle.natives.JNI_VehicleEngineSettings.internal_native_set_mMaxTorque(this_addr, mMaxTorque);
    }

    public float get_mMinRPM() {
        return internal_native_get_mMinRPM(native_address);
    }

    public static float internal_native_get_mMinRPM(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_VehicleEngineSettings.internal_native_get_mMinRPM(this_addr);
    }

    public void set_mMinRPM(float mMinRPM) {
        internal_native_set_mMinRPM(native_address, mMinRPM);
    }

    public static void internal_native_set_mMinRPM(long this_addr, float mMinRPM) {
        jolt.physics.vehicle.natives.JNI_VehicleEngineSettings.internal_native_set_mMinRPM(this_addr, mMinRPM);
    }

    public float get_mMaxRPM() {
        return internal_native_get_mMaxRPM(native_address);
    }

    public static float internal_native_get_mMaxRPM(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_VehicleEngineSettings.internal_native_get_mMaxRPM(this_addr);
    }

    public void set_mMaxRPM(float mMaxRPM) {
        internal_native_set_mMaxRPM(native_address, mMaxRPM);
    }

    public static void internal_native_set_mMaxRPM(long this_addr, float mMaxRPM) {
        jolt.physics.vehicle.natives.JNI_VehicleEngineSettings.internal_native_set_mMaxRPM(this_addr, mMaxRPM);
    }

    public LinearCurve get_mNormalizedTorque() {
        long addr = internal_native_get_mNormalizedTorque_addr(native_address);
        if (addr == 0)
            return LinearCurve.NULL;
        if (LinearCurve_TEMP_GEN_0 == null)
            LinearCurve_TEMP_GEN_0 = LinearCurve.native_new();
        LinearCurve_TEMP_GEN_0.internal_reset(addr, false);
        return LinearCurve_TEMP_GEN_0;
    }

    public static long internal_native_get_mNormalizedTorque_addr(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_VehicleEngineSettings.internal_native_get_mNormalizedTorque_addr(this_addr);
    }

    public void set_mNormalizedTorque(LinearCurve mNormalizedTorque) {
        internal_native_set_mNormalizedTorque(native_address, mNormalizedTorque.native_address);
    }

    public static void internal_native_set_mNormalizedTorque(long this_addr, long mNormalizedTorque_addr) {
        jolt.physics.vehicle.natives.JNI_VehicleEngineSettings.internal_native_set_mNormalizedTorque(this_addr, mNormalizedTorque_addr);
    }

    public float get_mInertia() {
        return internal_native_get_mInertia(native_address);
    }

    public static float internal_native_get_mInertia(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_VehicleEngineSettings.internal_native_get_mInertia(this_addr);
    }

    public void set_mInertia(float mInertia) {
        internal_native_set_mInertia(native_address, mInertia);
    }

    public static void internal_native_set_mInertia(long this_addr, float mInertia) {
        jolt.physics.vehicle.natives.JNI_VehicleEngineSettings.internal_native_set_mInertia(this_addr, mInertia);
    }

    public float get_mAngularDamping() {
        return internal_native_get_mAngularDamping(native_address);
    }

    public static float internal_native_get_mAngularDamping(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_VehicleEngineSettings.internal_native_get_mAngularDamping(this_addr);
    }

    public void set_mAngularDamping(float mAngularDamping) {
        internal_native_set_mAngularDamping(native_address, mAngularDamping);
    }

    public static void internal_native_set_mAngularDamping(long this_addr, float mAngularDamping) {
        jolt.physics.vehicle.natives.JNI_VehicleEngineSettings.internal_native_set_mAngularDamping(this_addr, mAngularDamping);
    }
}
