/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics;

import com.github.xpenatan.jParser.api.NativeObject;

public class PhysicsStepListener extends NativeObject {

    static private PhysicsStepListenerContext PhysicsStepListenerContext_TEMP_STATIC_GEN_0;

    static public final PhysicsStepListener NULL = PhysicsStepListener.native_new();

    @Deprecated()
    protected PhysicsStepListener(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static PhysicsStepListener native_new() {
        return new PhysicsStepListener((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.natives.JNI_PhysicsStepListener.internal_native_deleteNative(this_addr);
    }

    public PhysicsStepListener() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        internal_native_setupCallback(native_address);
    }

    protected void OnStep(PhysicsStepListenerContext inContext) {
    }

    private void internal_OnStep(long inContext_addr) {
        if (PhysicsStepListenerContext_TEMP_STATIC_GEN_0 == null)
            PhysicsStepListenerContext_TEMP_STATIC_GEN_0 = PhysicsStepListenerContext.native_new();
        PhysicsStepListenerContext_TEMP_STATIC_GEN_0.internal_reset(inContext_addr, false);
        OnStep(PhysicsStepListenerContext_TEMP_STATIC_GEN_0);
    }

    public static long internal_native_create_addr() {
        return jolt.physics.natives.JNI_PhysicsStepListener.internal_native_create_addr();
    }

    public native void internal_native_setupCallback(long this_addr);
}
