/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.softbody;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.physics.collision.TransformedShape;
import jolt.physics.collision.BroadPhaseCastResult;

public class RayCastBodyCollector extends NativeObject {

    static private BroadPhaseCastResult BroadPhaseCastResult_TEMP_STATIC_GEN_0;

    static public final RayCastBodyCollector NULL = RayCastBodyCollector.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected RayCastBodyCollector(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static RayCastBodyCollector native_new() {
        return new RayCastBodyCollector((byte) 0, (char) 0);
    }

    public void ResetNative() {
    }

    public void SetContext(TransformedShape inContext) {
    }

    public TransformedShape GetContext() {
        return null;
    }

    public void UpdateEarlyOutFraction(float inFraction) {
    }

    public void ResetEarlyOutFraction(float inFraction) {
    }

    public void ResetEarlyOutFraction() {
    }

    public void ForceEarlyOut() {
    }

    public boolean ShouldEarlyOut() {
        return false;
    }

    public float GetEarlyOutFraction() {
        return 0;
    }

    public float GetPositiveEarlyOutFraction() {
        return 0;
    }

    public RayCastBodyCollector() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
    }

    protected void Reset() {
    }

    private void internal_Reset() {
        Reset();
    }

    protected void AddHit(BroadPhaseCastResult inResult) {
    }

    private void internal_AddHit(long inResult_addr) {
        if (BroadPhaseCastResult_TEMP_STATIC_GEN_0 == null)
            BroadPhaseCastResult_TEMP_STATIC_GEN_0 = BroadPhaseCastResult.native_new();
        BroadPhaseCastResult_TEMP_STATIC_GEN_0.internal_reset(inResult_addr, false);
        AddHit(BroadPhaseCastResult_TEMP_STATIC_GEN_0);
    }

    public static native long internal_native_create_addr();
}
