/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_SphereShapeSettings {

    public static native long internal_native_create_float_PhysicsMaterial_addr(float inRadius, long inMaterial_addr);

    public static native long internal_native_create_float_addr(float inRadius);

    public static native void internal_native_deleteNative(long this_addr);

    public static native float internal_native_get_mRadius(long this_addr);

    public static native void internal_native_set_mRadius(long this_addr, float mRadius);
}
