/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_CompoundShape {

    public static native int internal_native_GetNumSubShapes(long this_addr);

    public static native long internal_native_GetSubShape_addr(long this_addr, int inIdx);
}
