/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_SubShapeIDPair {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetBody1ID_addr(long this_addr);

    public static native long internal_native_GetSubShapeID1_addr(long this_addr);

    public static native long internal_native_GetBody2ID_addr(long this_addr);

    public static native long internal_native_GetSubShapeID2_addr(long this_addr);
}
