/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_MeshShapeSettings {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_TriangleList_PhysicsMaterialList_addr(long inTriangleList_addr, long inMaterialList_addr);

    public static native long internal_native_create_TriangleList_addr(long inTriangleList_addr);

    public static native long internal_native_create_VertexList_IndexedTriangleList_PhysicsMaterialList_addr(long inVertices_addr, long inTriangles_addr, long inMaterialList_addr);

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_Sanitize(long this_addr);

    public static native long internal_native_get_mTriangleVertices_addr(long this_addr);

    public static native void internal_native_set_mTriangleVertices(long this_addr, long mTriangleVertices_addr);

    public static native long internal_native_get_mIndexedTriangles_addr(long this_addr);

    public static native void internal_native_set_mIndexedTriangles(long this_addr, long mIndexedTriangles_addr);

    public static native long internal_native_get_mMaterials_addr(long this_addr);

    public static native void internal_native_set_mMaterials(long this_addr, long mMaterials_addr);

    public static native int internal_native_get_mMaxTrianglesPerLeaf(long this_addr);

    public static native void internal_native_set_mMaxTrianglesPerLeaf(long this_addr, int mMaxTrianglesPerLeaf);

    public static native float internal_native_get_mActiveEdgeCosThresholdAngle(long this_addr);

    public static native void internal_native_set_mActiveEdgeCosThresholdAngle(long this_addr, float mActiveEdgeCosThresholdAngle);

    public static native boolean internal_native_get_mPerTriangleUserData(long this_addr);

    public static native void internal_native_set_mPerTriangleUserData(long this_addr, boolean mPerTriangleUserData);

    public static native int internal_native_get_mBuildQuality(long this_addr);

    public static native void internal_native_set_mBuildQuality(long this_addr, int mBuildQuality);
}
