/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_ScaledShapeSettings {

    public static native long internal_native_create_ShapeSettings_Vec3_addr(long inShape_addr, long inScale_addr);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_get_mScale_addr(long this_addr);

    public static native void internal_native_set_mScale(long this_addr, long mScale_addr);
}
