/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle.natives;

import jolt.physics.vehicle.*;

final public class JNI_WheelSettingsWV {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native float internal_native_get_mInertia(long this_addr);

    public static native void internal_native_set_mInertia(long this_addr, float mInertia);

    public static native float internal_native_get_mAngularDamping(long this_addr);

    public static native void internal_native_set_mAngularDamping(long this_addr, float mAngularDamping);

    public static native float internal_native_get_mMaxSteerAngle(long this_addr);

    public static native void internal_native_set_mMaxSteerAngle(long this_addr, float mMaxSteerAngle);

    public static native long internal_native_get_mLongitudinalFriction_addr(long this_addr);

    public static native void internal_native_set_mLongitudinalFriction(long this_addr, long mLongitudinalFriction_addr);

    public static native long internal_native_get_mLateralFriction_addr(long this_addr);

    public static native void internal_native_set_mLateralFriction(long this_addr, long mLateralFriction_addr);

    public static native float internal_native_get_mMaxBrakeTorque(long this_addr);

    public static native void internal_native_set_mMaxBrakeTorque(long this_addr, float mMaxBrakeTorque);

    public static native float internal_native_get_mMaxHandBrakeTorque(long this_addr);

    public static native void internal_native_set_mMaxHandBrakeTorque(long this_addr, float mMaxHandBrakeTorque);
}
