/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle.natives;

import jolt.physics.vehicle.*;

final public class JNI_WheelTV {

    public static native long internal_native_create_WheelSettingsTV_addr(long inWheel_addr);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetSettings_addr(long this_addr);

    public static native int internal_native_get_mTrackIndex(long this_addr);

    public static native void internal_native_set_mTrackIndex(long this_addr, int mTrackIndex);

    public static native float internal_native_get_mCombinedLongitudinalFriction(long this_addr);

    public static native void internal_native_set_mCombinedLongitudinalFriction(long this_addr, float mCombinedLongitudinalFriction);

    public static native float internal_native_get_mCombinedLateralFriction(long this_addr);

    public static native void internal_native_set_mCombinedLateralFriction(long this_addr, float mCombinedLateralFriction);

    public static native float internal_native_get_mBrakeImpulse(long this_addr);

    public static native void internal_native_set_mBrakeImpulse(long this_addr, float mBrakeImpulse);
}
