/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle.natives;

import jolt.physics.vehicle.*;

final public class JNI_VehicleCollisionTester {

    public static native int internal_native_GetRefCount(long this_addr);

    public static native void internal_native_AddRef(long this_addr);

    public static native void internal_native_Release(long this_addr);
}
