/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.softbody.natives;

import jolt.physics.softbody.*;

final public class JNI_SoftBodySharedSettingsRodBendTwist {

    public static native long internal_native_create_int_int_float_addr(int inRod1, int inRod2, float inCompliance);

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_get_mRod(long this_addr, int index);

    public static native void internal_native_set_mRod(long this_addr, int index, int mRod);

    public static native float internal_native_get_mCompliance(long this_addr);

    public static native void internal_native_set_mCompliance(long this_addr, float mCompliance);

    public static native long internal_native_get_mOmega0_addr(long this_addr);

    public static native void internal_native_set_mOmega0(long this_addr, long mOmega0_addr);
}
