/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.softbody.natives;

import jolt.physics.softbody.*;

final public class JNI_SoftBodySharedSettingsInvBind {

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_get_mJointIndex(long this_addr);

    public static native void internal_native_set_mJointIndex(long this_addr, int mJointIndex);

    public static native long internal_native_get_mInvBind_addr(long this_addr);

    public static native void internal_native_set_mInvBind(long this_addr, long mInvBind_addr);
}
