/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.softbody.natives;

import jolt.physics.softbody.*;

final public class JNI_SoftBodySharedSettingsRodStretchShear {

    public static native long internal_native_create_int_int_float_addr(int inVertex1, int inVertex2, float inCompliance);

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_get_mVertex(long this_addr, int index);

    public static native void internal_native_set_mVertex(long this_addr, int index, int mVertex);

    public static native float internal_native_get_mLength(long this_addr);

    public static native void internal_native_set_mLength(long this_addr, float mLength);

    public static native float internal_native_get_mInvMass(long this_addr);

    public static native void internal_native_set_mInvMass(long this_addr, float mInvMass);

    public static native float internal_native_get_mCompliance(long this_addr);

    public static native void internal_native_set_mCompliance(long this_addr, float mCompliance);

    public static native long internal_native_get_mBishop_addr(long this_addr);

    public static native void internal_native_set_mBishop(long this_addr, long mBishop_addr);
}
