/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.physics.body.BodyID;

public class BroadPhaseCastResult extends NativeObject {

    static public final BroadPhaseCastResult NULL = BroadPhaseCastResult.native_new();

    public BroadPhaseCastResult() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected BroadPhaseCastResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static BroadPhaseCastResult native_new() {
        return new BroadPhaseCastResult((byte) 0, (char) 0);
    }

    public void Reset() {
    }

    public BodyID get_mBodyID() {
        return null;
    }

    public void set_mBodyID(BodyID mBodyID) {
    }

    public float get_mFraction() {
        return 0;
    }

    public void set_mFraction(float mFraction) {
    }
}
