/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.enums.EActiveEdgeMode;
import jolt.enums.ECollectFacesMode;
import jolt.math.Vec3;

public class CollideSettingsBase extends NativeObject {

    static public final CollideSettingsBase NULL = CollideSettingsBase.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CollideSettingsBase(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static CollideSettingsBase native_new() {
        return new CollideSettingsBase((byte) 0, (char) 0);
    }

    public EActiveEdgeMode get_mActiveEdgeMode() {
        return null;
    }

    public void set_mActiveEdgeMode(EActiveEdgeMode mActiveEdgeMode) {
    }

    public ECollectFacesMode get_mCollectFacesMode() {
        return null;
    }

    public void set_mCollectFacesMode(ECollectFacesMode mCollectFacesMode) {
    }

    public float get_mCollisionTolerance() {
        return 0;
    }

    public void set_mCollisionTolerance(float mCollisionTolerance) {
    }

    public float get_mPenetrationTolerance() {
        return 0;
    }

    public void set_mPenetrationTolerance(float mPenetrationTolerance) {
    }

    public Vec3 get_mActiveEdgeMovementDirection() {
        return null;
    }

    public void set_mActiveEdgeMovementDirection(Vec3 mActiveEdgeMovementDirection) {
    }
}
