/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.character;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.physics.body.Body;
import jolt.math.Vec3;
import jolt.physics.body.BodyID;
import jolt.physics.collision.shape.SubShapeID;
import jolt.RVec3;
import jolt.physics.collision.PhysicsMaterial;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class CharacterContactListener extends NativeObject {

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_0;

    static private Body Body_TEMP_STATIC_GEN_0;

    static private Vec3 Vec3_TEMP_STATIC_GEN_0;

    static private Vec3 Vec3_TEMP_STATIC_GEN_1;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_1;

    static private BodyID BodyID_TEMP_STATIC_GEN_0;

    static private SubShapeID SubShapeID_TEMP_STATIC_GEN_0;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_2;

    static private CharacterVirtualContact CharacterVirtualContact_TEMP_STATIC_GEN_0;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_3;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_4;

    static private SubShapeID SubShapeID_TEMP_STATIC_GEN_1;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_5;

    static private CharacterVirtualContact CharacterVirtualContact_TEMP_STATIC_GEN_1;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_6;

    static private BodyID BodyID_TEMP_STATIC_GEN_1;

    static private SubShapeID SubShapeID_TEMP_STATIC_GEN_2;

    static private RVec3 RVec3_TEMP_STATIC_GEN_0;

    static private Vec3 Vec3_TEMP_STATIC_GEN_2;

    static private CharacterContactSettings CharacterContactSettings_TEMP_STATIC_GEN_0;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_7;

    static private CharacterVirtualContact CharacterVirtualContact_TEMP_STATIC_GEN_2;

    static private CharacterContactSettings CharacterContactSettings_TEMP_STATIC_GEN_1;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_8;

    static private BodyID BodyID_TEMP_STATIC_GEN_2;

    static private SubShapeID SubShapeID_TEMP_STATIC_GEN_3;

    static private RVec3 RVec3_TEMP_STATIC_GEN_1;

    static private Vec3 Vec3_TEMP_STATIC_GEN_3;

    static private CharacterContactSettings CharacterContactSettings_TEMP_STATIC_GEN_2;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_9;

    static private CharacterVirtualContact CharacterVirtualContact_TEMP_STATIC_GEN_3;

    static private CharacterContactSettings CharacterContactSettings_TEMP_STATIC_GEN_3;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_10;

    static private BodyID BodyID_TEMP_STATIC_GEN_3;

    static private SubShapeID SubShapeID_TEMP_STATIC_GEN_4;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_11;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_12;

    static private SubShapeID SubShapeID_TEMP_STATIC_GEN_5;

    static private RVec3 RVec3_TEMP_STATIC_GEN_2;

    static private Vec3 Vec3_TEMP_STATIC_GEN_4;

    static private CharacterContactSettings CharacterContactSettings_TEMP_STATIC_GEN_4;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_13;

    static private CharacterVirtualContact CharacterVirtualContact_TEMP_STATIC_GEN_4;

    static private CharacterContactSettings CharacterContactSettings_TEMP_STATIC_GEN_5;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_14;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_15;

    static private SubShapeID SubShapeID_TEMP_STATIC_GEN_6;

    static private Vec3 Vec3_TEMP_STATIC_GEN_5;

    static private Vec3 Vec3_TEMP_STATIC_GEN_6;

    static private CharacterContactSettings CharacterContactSettings_TEMP_STATIC_GEN_6;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_16;

    static private CharacterVirtualContact CharacterVirtualContact_TEMP_STATIC_GEN_5;

    static private CharacterContactSettings CharacterContactSettings_TEMP_STATIC_GEN_7;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_17;

    static private CharacterID CharacterID_TEMP_STATIC_GEN_0;

    static private SubShapeID SubShapeID_TEMP_STATIC_GEN_7;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_18;

    static private BodyID BodyID_TEMP_STATIC_GEN_4;

    static private SubShapeID SubShapeID_TEMP_STATIC_GEN_8;

    static private RVec3 RVec3_TEMP_STATIC_GEN_3;

    static private Vec3 Vec3_TEMP_STATIC_GEN_7;

    static private Vec3 Vec3_TEMP_STATIC_GEN_8;

    static private PhysicsMaterial PhysicsMaterial_TEMP_STATIC_GEN_0;

    static private Vec3 Vec3_TEMP_STATIC_GEN_9;

    static private Vec3 Vec3_TEMP_STATIC_GEN_10;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_19;

    static private CharacterVirtual CharacterVirtual_TEMP_STATIC_GEN_20;

    static private SubShapeID SubShapeID_TEMP_STATIC_GEN_9;

    static private RVec3 RVec3_TEMP_STATIC_GEN_4;

    static private Vec3 Vec3_TEMP_STATIC_GEN_11;

    static private Vec3 Vec3_TEMP_STATIC_GEN_12;

    static private PhysicsMaterial PhysicsMaterial_TEMP_STATIC_GEN_1;

    static private Vec3 Vec3_TEMP_STATIC_GEN_13;

    static private Vec3 Vec3_TEMP_STATIC_GEN_14;

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_OnAdjustBodyVelocity_custom = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnAdjustBodyVelocity_custom = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnContactValidate_custom = java.lang.invoke.MethodType.methodType(boolean.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnContactValidate_custom = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_BOOLEAN, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnContactValidateFull_custom = java.lang.invoke.MethodType.methodType(boolean.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnContactValidateFull_custom = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_BOOLEAN, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnCharacterContactValidate_custom = java.lang.invoke.MethodType.methodType(boolean.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnCharacterContactValidate_custom = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_BOOLEAN, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnCharacterContactValidateFull_custom = java.lang.invoke.MethodType.methodType(boolean.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnCharacterContactValidateFull_custom = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_BOOLEAN, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnContactAdded_custom = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, long.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnContactAdded_custom = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnContactAddedFull_custom = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnContactAddedFull_custom = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnContactPersisted_custom = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, long.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnContactPersisted_custom = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnContactPersistedFull_custom = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnContactPersistedFull_custom = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnContactRemoved_custom = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnContactRemoved_custom = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnCharacterContactAdded_custom = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, long.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnCharacterContactAdded_custom = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnCharacterContactAddedFull_custom = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnCharacterContactAddedFull_custom = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnCharacterContactPersisted_custom = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, long.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnCharacterContactPersisted_custom = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnCharacterContactPersistedFull_custom = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnCharacterContactPersistedFull_custom = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnCharacterContactRemoved_custom = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnCharacterContactRemoved_custom = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnContactSolve_custom = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, long.class, long.class, long.class, long.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnContactSolve_custom = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_OnCharacterContactSolve_custom = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, long.class, long.class, long.class, long.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnCharacterContactSolve_custom = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    static public final CharacterContactListener NULL = CharacterContactListener.native_new();

    @Deprecated()
    protected CharacterContactListener(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static CharacterContactListener native_new() {
        return new CharacterContactListener((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnAdjustBodyVelocity() {
        return internal_native_get_OnAdjustBodyVelocity(native_address);
    }

    public static boolean internal_native_get_OnAdjustBodyVelocity(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnAdjustBodyVelocity__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnAdjustBodyVelocity(boolean onAdjustBodyVelocity) {
        internal_native_set_OnAdjustBodyVelocity(native_address, onAdjustBodyVelocity);
    }

    public static void internal_native_set_OnAdjustBodyVelocity(long this_addr, boolean onAdjustBodyVelocity) {
        try {
            FFMHandles.internal_native_set_OnAdjustBodyVelocity__JZ.invokeExact(this_addr, onAdjustBodyVelocity);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnContactValidate() {
        return internal_native_get_OnContactValidate(native_address);
    }

    public static boolean internal_native_get_OnContactValidate(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnContactValidate__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnContactValidate(boolean onContactValidate) {
        internal_native_set_OnContactValidate(native_address, onContactValidate);
    }

    public static void internal_native_set_OnContactValidate(long this_addr, boolean onContactValidate) {
        try {
            FFMHandles.internal_native_set_OnContactValidate__JZ.invokeExact(this_addr, onContactValidate);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnContactValidateFull() {
        return internal_native_get_OnContactValidateFull(native_address);
    }

    public static boolean internal_native_get_OnContactValidateFull(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnContactValidateFull__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnContactValidateFull(boolean onContactValidateFull) {
        internal_native_set_OnContactValidateFull(native_address, onContactValidateFull);
    }

    public static void internal_native_set_OnContactValidateFull(long this_addr, boolean onContactValidateFull) {
        try {
            FFMHandles.internal_native_set_OnContactValidateFull__JZ.invokeExact(this_addr, onContactValidateFull);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnCharacterContactValidate() {
        return internal_native_get_OnCharacterContactValidate(native_address);
    }

    public static boolean internal_native_get_OnCharacterContactValidate(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnCharacterContactValidate__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnCharacterContactValidate(boolean onCharacterContactValidate) {
        internal_native_set_OnCharacterContactValidate(native_address, onCharacterContactValidate);
    }

    public static void internal_native_set_OnCharacterContactValidate(long this_addr, boolean onCharacterContactValidate) {
        try {
            FFMHandles.internal_native_set_OnCharacterContactValidate__JZ.invokeExact(this_addr, onCharacterContactValidate);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnCharacterContactValidateFull() {
        return internal_native_get_OnCharacterContactValidateFull(native_address);
    }

    public static boolean internal_native_get_OnCharacterContactValidateFull(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnCharacterContactValidateFull__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnCharacterContactValidateFull(boolean onCharacterContactValidateFull) {
        internal_native_set_OnCharacterContactValidateFull(native_address, onCharacterContactValidateFull);
    }

    public static void internal_native_set_OnCharacterContactValidateFull(long this_addr, boolean onCharacterContactValidateFull) {
        try {
            FFMHandles.internal_native_set_OnCharacterContactValidateFull__JZ.invokeExact(this_addr, onCharacterContactValidateFull);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnContactAdded() {
        return internal_native_get_OnContactAdded(native_address);
    }

    public static boolean internal_native_get_OnContactAdded(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnContactAdded__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnContactAdded(boolean onContactAdded) {
        internal_native_set_OnContactAdded(native_address, onContactAdded);
    }

    public static void internal_native_set_OnContactAdded(long this_addr, boolean onContactAdded) {
        try {
            FFMHandles.internal_native_set_OnContactAdded__JZ.invokeExact(this_addr, onContactAdded);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnContactAddedFull() {
        return internal_native_get_OnContactAddedFull(native_address);
    }

    public static boolean internal_native_get_OnContactAddedFull(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnContactAddedFull__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnContactAddedFull(boolean onContactAddedFull) {
        internal_native_set_OnContactAddedFull(native_address, onContactAddedFull);
    }

    public static void internal_native_set_OnContactAddedFull(long this_addr, boolean onContactAddedFull) {
        try {
            FFMHandles.internal_native_set_OnContactAddedFull__JZ.invokeExact(this_addr, onContactAddedFull);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnContactPersisted() {
        return internal_native_get_OnContactPersisted(native_address);
    }

    public static boolean internal_native_get_OnContactPersisted(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnContactPersisted__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnContactPersisted(boolean onContactPersisted) {
        internal_native_set_OnContactPersisted(native_address, onContactPersisted);
    }

    public static void internal_native_set_OnContactPersisted(long this_addr, boolean onContactPersisted) {
        try {
            FFMHandles.internal_native_set_OnContactPersisted__JZ.invokeExact(this_addr, onContactPersisted);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnContactPersistedFull() {
        return internal_native_get_OnContactPersistedFull(native_address);
    }

    public static boolean internal_native_get_OnContactPersistedFull(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnContactPersistedFull__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnContactPersistedFull(boolean onContactPersistedFull) {
        internal_native_set_OnContactPersistedFull(native_address, onContactPersistedFull);
    }

    public static void internal_native_set_OnContactPersistedFull(long this_addr, boolean onContactPersistedFull) {
        try {
            FFMHandles.internal_native_set_OnContactPersistedFull__JZ.invokeExact(this_addr, onContactPersistedFull);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnContactRemoved() {
        return internal_native_get_OnContactRemoved(native_address);
    }

    public static boolean internal_native_get_OnContactRemoved(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnContactRemoved__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnContactRemoved(boolean onContactRemoved) {
        internal_native_set_OnContactRemoved(native_address, onContactRemoved);
    }

    public static void internal_native_set_OnContactRemoved(long this_addr, boolean onContactRemoved) {
        try {
            FFMHandles.internal_native_set_OnContactRemoved__JZ.invokeExact(this_addr, onContactRemoved);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnCharacterContactAdded() {
        return internal_native_get_OnCharacterContactAdded(native_address);
    }

    public static boolean internal_native_get_OnCharacterContactAdded(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnCharacterContactAdded__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnCharacterContactAdded(boolean onCharacterContactAdded) {
        internal_native_set_OnCharacterContactAdded(native_address, onCharacterContactAdded);
    }

    public static void internal_native_set_OnCharacterContactAdded(long this_addr, boolean onCharacterContactAdded) {
        try {
            FFMHandles.internal_native_set_OnCharacterContactAdded__JZ.invokeExact(this_addr, onCharacterContactAdded);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnCharacterContactAddedFull() {
        return internal_native_get_OnCharacterContactAddedFull(native_address);
    }

    public static boolean internal_native_get_OnCharacterContactAddedFull(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnCharacterContactAddedFull__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnCharacterContactAddedFull(boolean onCharacterContactAddedFull) {
        internal_native_set_OnCharacterContactAddedFull(native_address, onCharacterContactAddedFull);
    }

    public static void internal_native_set_OnCharacterContactAddedFull(long this_addr, boolean onCharacterContactAddedFull) {
        try {
            FFMHandles.internal_native_set_OnCharacterContactAddedFull__JZ.invokeExact(this_addr, onCharacterContactAddedFull);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnCharacterContactPersisted() {
        return internal_native_get_OnCharacterContactPersisted(native_address);
    }

    public static boolean internal_native_get_OnCharacterContactPersisted(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnCharacterContactPersisted__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnCharacterContactPersisted(boolean onCharacterContactPersisted) {
        internal_native_set_OnCharacterContactPersisted(native_address, onCharacterContactPersisted);
    }

    public static void internal_native_set_OnCharacterContactPersisted(long this_addr, boolean onCharacterContactPersisted) {
        try {
            FFMHandles.internal_native_set_OnCharacterContactPersisted__JZ.invokeExact(this_addr, onCharacterContactPersisted);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnCharacterContactPersistedFull() {
        return internal_native_get_OnCharacterContactPersistedFull(native_address);
    }

    public static boolean internal_native_get_OnCharacterContactPersistedFull(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnCharacterContactPersistedFull__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnCharacterContactPersistedFull(boolean onCharacterContactPersistedFull) {
        internal_native_set_OnCharacterContactPersistedFull(native_address, onCharacterContactPersistedFull);
    }

    public static void internal_native_set_OnCharacterContactPersistedFull(long this_addr, boolean onCharacterContactPersistedFull) {
        try {
            FFMHandles.internal_native_set_OnCharacterContactPersistedFull__JZ.invokeExact(this_addr, onCharacterContactPersistedFull);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnCharacterContactRemoved() {
        return internal_native_get_OnCharacterContactRemoved(native_address);
    }

    public static boolean internal_native_get_OnCharacterContactRemoved(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnCharacterContactRemoved__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnCharacterContactRemoved(boolean onCharacterContactRemoved) {
        internal_native_set_OnCharacterContactRemoved(native_address, onCharacterContactRemoved);
    }

    public static void internal_native_set_OnCharacterContactRemoved(long this_addr, boolean onCharacterContactRemoved) {
        try {
            FFMHandles.internal_native_set_OnCharacterContactRemoved__JZ.invokeExact(this_addr, onCharacterContactRemoved);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnContactSolve() {
        return internal_native_get_OnContactSolve(native_address);
    }

    public static boolean internal_native_get_OnContactSolve(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnContactSolve__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnContactSolve(boolean onContactSolve) {
        internal_native_set_OnContactSolve(native_address, onContactSolve);
    }

    public static void internal_native_set_OnContactSolve(long this_addr, boolean onContactSolve) {
        try {
            FFMHandles.internal_native_set_OnContactSolve__JZ.invokeExact(this_addr, onContactSolve);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_OnCharacterContactSolve() {
        return internal_native_get_OnCharacterContactSolve(native_address);
    }

    public static boolean internal_native_get_OnCharacterContactSolve(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_OnCharacterContactSolve__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OnCharacterContactSolve(boolean onCharacterContactSolve) {
        internal_native_set_OnCharacterContactSolve(native_address, onCharacterContactSolve);
    }

    public static void internal_native_set_OnCharacterContactSolve(long this_addr, boolean onCharacterContactSolve) {
        try {
            FFMHandles.internal_native_set_OnCharacterContactSolve__JZ.invokeExact(this_addr, onCharacterContactSolve);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public CharacterContactListener() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_OnAdjustBodyVelocity_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnAdjustBodyVelocity_custom", callbackMethodType_OnAdjustBodyVelocity_custom).bindTo(this);
            upcallStub_OnAdjustBodyVelocity_custom = callbackLinker.upcallStub(mh_OnAdjustBodyVelocity_custom, callbackDescriptor_OnAdjustBodyVelocity_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnContactValidate_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnContactValidate_custom", callbackMethodType_OnContactValidate_custom).bindTo(this);
            upcallStub_OnContactValidate_custom = callbackLinker.upcallStub(mh_OnContactValidate_custom, callbackDescriptor_OnContactValidate_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnContactValidateFull_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnContactValidateFull_custom", callbackMethodType_OnContactValidateFull_custom).bindTo(this);
            upcallStub_OnContactValidateFull_custom = callbackLinker.upcallStub(mh_OnContactValidateFull_custom, callbackDescriptor_OnContactValidateFull_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnCharacterContactValidate_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnCharacterContactValidate_custom", callbackMethodType_OnCharacterContactValidate_custom).bindTo(this);
            upcallStub_OnCharacterContactValidate_custom = callbackLinker.upcallStub(mh_OnCharacterContactValidate_custom, callbackDescriptor_OnCharacterContactValidate_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnCharacterContactValidateFull_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnCharacterContactValidateFull_custom", callbackMethodType_OnCharacterContactValidateFull_custom).bindTo(this);
            upcallStub_OnCharacterContactValidateFull_custom = callbackLinker.upcallStub(mh_OnCharacterContactValidateFull_custom, callbackDescriptor_OnCharacterContactValidateFull_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnContactAdded_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnContactAdded_custom", callbackMethodType_OnContactAdded_custom).bindTo(this);
            upcallStub_OnContactAdded_custom = callbackLinker.upcallStub(mh_OnContactAdded_custom, callbackDescriptor_OnContactAdded_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnContactAddedFull_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnContactAddedFull_custom", callbackMethodType_OnContactAddedFull_custom).bindTo(this);
            upcallStub_OnContactAddedFull_custom = callbackLinker.upcallStub(mh_OnContactAddedFull_custom, callbackDescriptor_OnContactAddedFull_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnContactPersisted_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnContactPersisted_custom", callbackMethodType_OnContactPersisted_custom).bindTo(this);
            upcallStub_OnContactPersisted_custom = callbackLinker.upcallStub(mh_OnContactPersisted_custom, callbackDescriptor_OnContactPersisted_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnContactPersistedFull_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnContactPersistedFull_custom", callbackMethodType_OnContactPersistedFull_custom).bindTo(this);
            upcallStub_OnContactPersistedFull_custom = callbackLinker.upcallStub(mh_OnContactPersistedFull_custom, callbackDescriptor_OnContactPersistedFull_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnContactRemoved_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnContactRemoved_custom", callbackMethodType_OnContactRemoved_custom).bindTo(this);
            upcallStub_OnContactRemoved_custom = callbackLinker.upcallStub(mh_OnContactRemoved_custom, callbackDescriptor_OnContactRemoved_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnCharacterContactAdded_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnCharacterContactAdded_custom", callbackMethodType_OnCharacterContactAdded_custom).bindTo(this);
            upcallStub_OnCharacterContactAdded_custom = callbackLinker.upcallStub(mh_OnCharacterContactAdded_custom, callbackDescriptor_OnCharacterContactAdded_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnCharacterContactAddedFull_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnCharacterContactAddedFull_custom", callbackMethodType_OnCharacterContactAddedFull_custom).bindTo(this);
            upcallStub_OnCharacterContactAddedFull_custom = callbackLinker.upcallStub(mh_OnCharacterContactAddedFull_custom, callbackDescriptor_OnCharacterContactAddedFull_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnCharacterContactPersisted_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnCharacterContactPersisted_custom", callbackMethodType_OnCharacterContactPersisted_custom).bindTo(this);
            upcallStub_OnCharacterContactPersisted_custom = callbackLinker.upcallStub(mh_OnCharacterContactPersisted_custom, callbackDescriptor_OnCharacterContactPersisted_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnCharacterContactPersistedFull_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnCharacterContactPersistedFull_custom", callbackMethodType_OnCharacterContactPersistedFull_custom).bindTo(this);
            upcallStub_OnCharacterContactPersistedFull_custom = callbackLinker.upcallStub(mh_OnCharacterContactPersistedFull_custom, callbackDescriptor_OnCharacterContactPersistedFull_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnCharacterContactRemoved_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnCharacterContactRemoved_custom", callbackMethodType_OnCharacterContactRemoved_custom).bindTo(this);
            upcallStub_OnCharacterContactRemoved_custom = callbackLinker.upcallStub(mh_OnCharacterContactRemoved_custom, callbackDescriptor_OnCharacterContactRemoved_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnContactSolve_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnContactSolve_custom", callbackMethodType_OnContactSolve_custom).bindTo(this);
            upcallStub_OnContactSolve_custom = callbackLinker.upcallStub(mh_OnContactSolve_custom, callbackDescriptor_OnContactSolve_custom, upcallArena);
            java.lang.invoke.MethodHandle mh_OnCharacterContactSolve_custom = callbackLookup.findVirtual(CharacterContactListener.class, "internal_OnCharacterContactSolve_custom", callbackMethodType_OnCharacterContactSolve_custom).bindTo(this);
            upcallStub_OnCharacterContactSolve_custom = callbackLinker.upcallStub(mh_OnCharacterContactSolve_custom, callbackDescriptor_OnCharacterContactSolve_custom, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_OnAdjustBodyVelocity_custom.address(), upcallStub_OnContactValidate_custom.address(), upcallStub_OnContactValidateFull_custom.address(), upcallStub_OnCharacterContactValidate_custom.address(), upcallStub_OnCharacterContactValidateFull_custom.address(), upcallStub_OnContactAdded_custom.address(), upcallStub_OnContactAddedFull_custom.address(), upcallStub_OnContactPersisted_custom.address(), upcallStub_OnContactPersistedFull_custom.address(), upcallStub_OnContactRemoved_custom.address(), upcallStub_OnCharacterContactAdded_custom.address(), upcallStub_OnCharacterContactAddedFull_custom.address(), upcallStub_OnCharacterContactPersisted_custom.address(), upcallStub_OnCharacterContactPersistedFull_custom.address(), upcallStub_OnCharacterContactRemoved_custom.address(), upcallStub_OnContactSolve_custom.address(), upcallStub_OnCharacterContactSolve_custom.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected void OnAdjustBodyVelocity(CharacterVirtual inCharacter, Body inBody2, Vec3 ioLinearVelocity, Vec3 ioAngularVelocity) {
    }

    private void internal_OnAdjustBodyVelocity_custom(long inCharacter_addr, long inBody2_addr, long ioLinearVelocity_addr, long ioAngularVelocity_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_0 == null)
            CharacterVirtual_TEMP_STATIC_GEN_0 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_0.internal_reset(inCharacter_addr, false);
        if (Body_TEMP_STATIC_GEN_0 == null)
            Body_TEMP_STATIC_GEN_0 = Body.native_new();
        Body_TEMP_STATIC_GEN_0.internal_reset(inBody2_addr, false);
        if (Vec3_TEMP_STATIC_GEN_0 == null)
            Vec3_TEMP_STATIC_GEN_0 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_0.internal_reset(ioLinearVelocity_addr, false);
        if (Vec3_TEMP_STATIC_GEN_1 == null)
            Vec3_TEMP_STATIC_GEN_1 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_1.internal_reset(ioAngularVelocity_addr, false);
        OnAdjustBodyVelocity(CharacterVirtual_TEMP_STATIC_GEN_0, Body_TEMP_STATIC_GEN_0, Vec3_TEMP_STATIC_GEN_0, Vec3_TEMP_STATIC_GEN_1);
    }

    protected boolean OnContactValidate(CharacterVirtual inCharacter, BodyID inBodyID2, SubShapeID inSubShapeID2) {
        return false;
    }

    private boolean internal_OnContactValidate_custom(long inCharacter_addr, long inBodyID2_addr, long inSubShapeID2_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_1 == null)
            CharacterVirtual_TEMP_STATIC_GEN_1 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_1.internal_reset(inCharacter_addr, false);
        if (BodyID_TEMP_STATIC_GEN_0 == null)
            BodyID_TEMP_STATIC_GEN_0 = BodyID.native_new();
        BodyID_TEMP_STATIC_GEN_0.internal_reset(inBodyID2_addr, false);
        if (SubShapeID_TEMP_STATIC_GEN_0 == null)
            SubShapeID_TEMP_STATIC_GEN_0 = SubShapeID.native_new();
        SubShapeID_TEMP_STATIC_GEN_0.internal_reset(inSubShapeID2_addr, false);
        return OnContactValidate(CharacterVirtual_TEMP_STATIC_GEN_1, BodyID_TEMP_STATIC_GEN_0, SubShapeID_TEMP_STATIC_GEN_0);
    }

    protected boolean OnContactValidate(CharacterVirtual inCharacter, CharacterVirtualContact inContact) {
        return false;
    }

    private boolean internal_OnContactValidateFull_custom(long inCharacter_addr, long inContact_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_2 == null)
            CharacterVirtual_TEMP_STATIC_GEN_2 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_2.internal_reset(inCharacter_addr, false);
        if (CharacterVirtualContact_TEMP_STATIC_GEN_0 == null)
            CharacterVirtualContact_TEMP_STATIC_GEN_0 = CharacterVirtualContact.native_new();
        CharacterVirtualContact_TEMP_STATIC_GEN_0.internal_reset(inContact_addr, false);
        return OnContactValidate(CharacterVirtual_TEMP_STATIC_GEN_2, CharacterVirtualContact_TEMP_STATIC_GEN_0);
    }

    protected boolean OnCharacterContactValidate(CharacterVirtual inCharacter, CharacterVirtual inOtherCharacter, SubShapeID inSubShapeID2) {
        return false;
    }

    private boolean internal_OnCharacterContactValidate_custom(long inCharacter_addr, long inOtherCharacter_addr, long inSubShapeID2_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_3 == null)
            CharacterVirtual_TEMP_STATIC_GEN_3 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_3.internal_reset(inCharacter_addr, false);
        if (CharacterVirtual_TEMP_STATIC_GEN_4 == null)
            CharacterVirtual_TEMP_STATIC_GEN_4 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_4.internal_reset(inOtherCharacter_addr, false);
        if (SubShapeID_TEMP_STATIC_GEN_1 == null)
            SubShapeID_TEMP_STATIC_GEN_1 = SubShapeID.native_new();
        SubShapeID_TEMP_STATIC_GEN_1.internal_reset(inSubShapeID2_addr, false);
        return OnCharacterContactValidate(CharacterVirtual_TEMP_STATIC_GEN_3, CharacterVirtual_TEMP_STATIC_GEN_4, SubShapeID_TEMP_STATIC_GEN_1);
    }

    protected boolean OnCharacterContactValidate(CharacterVirtual inCharacter, CharacterVirtualContact inContact) {
        return false;
    }

    private boolean internal_OnCharacterContactValidateFull_custom(long inCharacter_addr, long inContact_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_5 == null)
            CharacterVirtual_TEMP_STATIC_GEN_5 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_5.internal_reset(inCharacter_addr, false);
        if (CharacterVirtualContact_TEMP_STATIC_GEN_1 == null)
            CharacterVirtualContact_TEMP_STATIC_GEN_1 = CharacterVirtualContact.native_new();
        CharacterVirtualContact_TEMP_STATIC_GEN_1.internal_reset(inContact_addr, false);
        return OnCharacterContactValidate(CharacterVirtual_TEMP_STATIC_GEN_5, CharacterVirtualContact_TEMP_STATIC_GEN_1);
    }

    protected void OnContactAdded(CharacterVirtual inCharacter, BodyID inBodyID2, SubShapeID inSubShapeID2, RVec3 inContactPosition, Vec3 inContactNormal, CharacterContactSettings ioSettings) {
    }

    private void internal_OnContactAdded_custom(long inCharacter_addr, long inBodyID2_addr, long inSubShapeID2_addr, long inContactPosition_addr, long inContactNormal_addr, long ioSettings_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_6 == null)
            CharacterVirtual_TEMP_STATIC_GEN_6 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_6.internal_reset(inCharacter_addr, false);
        if (BodyID_TEMP_STATIC_GEN_1 == null)
            BodyID_TEMP_STATIC_GEN_1 = BodyID.native_new();
        BodyID_TEMP_STATIC_GEN_1.internal_reset(inBodyID2_addr, false);
        if (SubShapeID_TEMP_STATIC_GEN_2 == null)
            SubShapeID_TEMP_STATIC_GEN_2 = SubShapeID.native_new();
        SubShapeID_TEMP_STATIC_GEN_2.internal_reset(inSubShapeID2_addr, false);
        if (RVec3_TEMP_STATIC_GEN_0 == null)
            RVec3_TEMP_STATIC_GEN_0 = RVec3.native_new();
        RVec3_TEMP_STATIC_GEN_0.internal_reset(inContactPosition_addr, false);
        if (Vec3_TEMP_STATIC_GEN_2 == null)
            Vec3_TEMP_STATIC_GEN_2 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_2.internal_reset(inContactNormal_addr, false);
        if (CharacterContactSettings_TEMP_STATIC_GEN_0 == null)
            CharacterContactSettings_TEMP_STATIC_GEN_0 = CharacterContactSettings.native_new();
        CharacterContactSettings_TEMP_STATIC_GEN_0.internal_reset(ioSettings_addr, false);
        OnContactAdded(CharacterVirtual_TEMP_STATIC_GEN_6, BodyID_TEMP_STATIC_GEN_1, SubShapeID_TEMP_STATIC_GEN_2, RVec3_TEMP_STATIC_GEN_0, Vec3_TEMP_STATIC_GEN_2, CharacterContactSettings_TEMP_STATIC_GEN_0);
    }

    protected void OnContactAdded(CharacterVirtual inCharacter, CharacterVirtualContact inContact, CharacterContactSettings ioSettings) {
    }

    private void internal_OnContactAddedFull_custom(long inCharacter_addr, long inContact_addr, long ioSettings_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_7 == null)
            CharacterVirtual_TEMP_STATIC_GEN_7 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_7.internal_reset(inCharacter_addr, false);
        if (CharacterVirtualContact_TEMP_STATIC_GEN_2 == null)
            CharacterVirtualContact_TEMP_STATIC_GEN_2 = CharacterVirtualContact.native_new();
        CharacterVirtualContact_TEMP_STATIC_GEN_2.internal_reset(inContact_addr, false);
        if (CharacterContactSettings_TEMP_STATIC_GEN_1 == null)
            CharacterContactSettings_TEMP_STATIC_GEN_1 = CharacterContactSettings.native_new();
        CharacterContactSettings_TEMP_STATIC_GEN_1.internal_reset(ioSettings_addr, false);
        OnContactAdded(CharacterVirtual_TEMP_STATIC_GEN_7, CharacterVirtualContact_TEMP_STATIC_GEN_2, CharacterContactSettings_TEMP_STATIC_GEN_1);
    }

    protected void OnContactPersisted(CharacterVirtual inCharacter, BodyID inBodyID2, SubShapeID inSubShapeID2, RVec3 inContactPosition, Vec3 inContactNormal, CharacterContactSettings ioSettings) {
    }

    private void internal_OnContactPersisted_custom(long inCharacter_addr, long inBodyID2_addr, long inSubShapeID2_addr, long inContactPosition_addr, long inContactNormal_addr, long ioSettings_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_8 == null)
            CharacterVirtual_TEMP_STATIC_GEN_8 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_8.internal_reset(inCharacter_addr, false);
        if (BodyID_TEMP_STATIC_GEN_2 == null)
            BodyID_TEMP_STATIC_GEN_2 = BodyID.native_new();
        BodyID_TEMP_STATIC_GEN_2.internal_reset(inBodyID2_addr, false);
        if (SubShapeID_TEMP_STATIC_GEN_3 == null)
            SubShapeID_TEMP_STATIC_GEN_3 = SubShapeID.native_new();
        SubShapeID_TEMP_STATIC_GEN_3.internal_reset(inSubShapeID2_addr, false);
        if (RVec3_TEMP_STATIC_GEN_1 == null)
            RVec3_TEMP_STATIC_GEN_1 = RVec3.native_new();
        RVec3_TEMP_STATIC_GEN_1.internal_reset(inContactPosition_addr, false);
        if (Vec3_TEMP_STATIC_GEN_3 == null)
            Vec3_TEMP_STATIC_GEN_3 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_3.internal_reset(inContactNormal_addr, false);
        if (CharacterContactSettings_TEMP_STATIC_GEN_2 == null)
            CharacterContactSettings_TEMP_STATIC_GEN_2 = CharacterContactSettings.native_new();
        CharacterContactSettings_TEMP_STATIC_GEN_2.internal_reset(ioSettings_addr, false);
        OnContactPersisted(CharacterVirtual_TEMP_STATIC_GEN_8, BodyID_TEMP_STATIC_GEN_2, SubShapeID_TEMP_STATIC_GEN_3, RVec3_TEMP_STATIC_GEN_1, Vec3_TEMP_STATIC_GEN_3, CharacterContactSettings_TEMP_STATIC_GEN_2);
    }

    protected void OnContactPersisted(CharacterVirtual inCharacter, CharacterVirtualContact inContact, CharacterContactSettings ioSettings) {
    }

    private void internal_OnContactPersistedFull_custom(long inCharacter_addr, long inContact_addr, long ioSettings_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_9 == null)
            CharacterVirtual_TEMP_STATIC_GEN_9 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_9.internal_reset(inCharacter_addr, false);
        if (CharacterVirtualContact_TEMP_STATIC_GEN_3 == null)
            CharacterVirtualContact_TEMP_STATIC_GEN_3 = CharacterVirtualContact.native_new();
        CharacterVirtualContact_TEMP_STATIC_GEN_3.internal_reset(inContact_addr, false);
        if (CharacterContactSettings_TEMP_STATIC_GEN_3 == null)
            CharacterContactSettings_TEMP_STATIC_GEN_3 = CharacterContactSettings.native_new();
        CharacterContactSettings_TEMP_STATIC_GEN_3.internal_reset(ioSettings_addr, false);
        OnContactPersisted(CharacterVirtual_TEMP_STATIC_GEN_9, CharacterVirtualContact_TEMP_STATIC_GEN_3, CharacterContactSettings_TEMP_STATIC_GEN_3);
    }

    protected void OnContactRemoved(CharacterVirtual inCharacter, BodyID inBodyID2, SubShapeID inSubShapeID2) {
    }

    private void internal_OnContactRemoved_custom(long inCharacter_addr, long inBodyID2_addr, long inSubShapeID2_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_10 == null)
            CharacterVirtual_TEMP_STATIC_GEN_10 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_10.internal_reset(inCharacter_addr, false);
        if (BodyID_TEMP_STATIC_GEN_3 == null)
            BodyID_TEMP_STATIC_GEN_3 = BodyID.native_new();
        BodyID_TEMP_STATIC_GEN_3.internal_reset(inBodyID2_addr, false);
        if (SubShapeID_TEMP_STATIC_GEN_4 == null)
            SubShapeID_TEMP_STATIC_GEN_4 = SubShapeID.native_new();
        SubShapeID_TEMP_STATIC_GEN_4.internal_reset(inSubShapeID2_addr, false);
        OnContactRemoved(CharacterVirtual_TEMP_STATIC_GEN_10, BodyID_TEMP_STATIC_GEN_3, SubShapeID_TEMP_STATIC_GEN_4);
    }

    protected void OnCharacterContactAdded(CharacterVirtual inCharacter, CharacterVirtual inOtherCharacter, SubShapeID inSubShapeID2, RVec3 inContactPosition, Vec3 inContactNormal, CharacterContactSettings ioSettings) {
    }

    private void internal_OnCharacterContactAdded_custom(long inCharacter_addr, long inOtherCharacter_addr, long inSubShapeID2_addr, long inContactPosition_addr, long inContactNormal_addr, long ioSettings_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_11 == null)
            CharacterVirtual_TEMP_STATIC_GEN_11 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_11.internal_reset(inCharacter_addr, false);
        if (CharacterVirtual_TEMP_STATIC_GEN_12 == null)
            CharacterVirtual_TEMP_STATIC_GEN_12 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_12.internal_reset(inOtherCharacter_addr, false);
        if (SubShapeID_TEMP_STATIC_GEN_5 == null)
            SubShapeID_TEMP_STATIC_GEN_5 = SubShapeID.native_new();
        SubShapeID_TEMP_STATIC_GEN_5.internal_reset(inSubShapeID2_addr, false);
        if (RVec3_TEMP_STATIC_GEN_2 == null)
            RVec3_TEMP_STATIC_GEN_2 = RVec3.native_new();
        RVec3_TEMP_STATIC_GEN_2.internal_reset(inContactPosition_addr, false);
        if (Vec3_TEMP_STATIC_GEN_4 == null)
            Vec3_TEMP_STATIC_GEN_4 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_4.internal_reset(inContactNormal_addr, false);
        if (CharacterContactSettings_TEMP_STATIC_GEN_4 == null)
            CharacterContactSettings_TEMP_STATIC_GEN_4 = CharacterContactSettings.native_new();
        CharacterContactSettings_TEMP_STATIC_GEN_4.internal_reset(ioSettings_addr, false);
        OnCharacterContactAdded(CharacterVirtual_TEMP_STATIC_GEN_11, CharacterVirtual_TEMP_STATIC_GEN_12, SubShapeID_TEMP_STATIC_GEN_5, RVec3_TEMP_STATIC_GEN_2, Vec3_TEMP_STATIC_GEN_4, CharacterContactSettings_TEMP_STATIC_GEN_4);
    }

    protected void OnCharacterContactAdded(CharacterVirtual inCharacter, CharacterVirtualContact inContact, CharacterContactSettings ioSettings) {
    }

    private void internal_OnCharacterContactAddedFull_custom(long inCharacter_addr, long inContact_addr, long ioSettings_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_13 == null)
            CharacterVirtual_TEMP_STATIC_GEN_13 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_13.internal_reset(inCharacter_addr, false);
        if (CharacterVirtualContact_TEMP_STATIC_GEN_4 == null)
            CharacterVirtualContact_TEMP_STATIC_GEN_4 = CharacterVirtualContact.native_new();
        CharacterVirtualContact_TEMP_STATIC_GEN_4.internal_reset(inContact_addr, false);
        if (CharacterContactSettings_TEMP_STATIC_GEN_5 == null)
            CharacterContactSettings_TEMP_STATIC_GEN_5 = CharacterContactSettings.native_new();
        CharacterContactSettings_TEMP_STATIC_GEN_5.internal_reset(ioSettings_addr, false);
        OnCharacterContactAdded(CharacterVirtual_TEMP_STATIC_GEN_13, CharacterVirtualContact_TEMP_STATIC_GEN_4, CharacterContactSettings_TEMP_STATIC_GEN_5);
    }

    protected void OnCharacterContactPersisted(CharacterVirtual inCharacter, CharacterVirtual inOtherCharacter, SubShapeID inSubShapeID2, Vec3 inContactPosition, Vec3 inContactNormal, CharacterContactSettings ioSettings) {
    }

    private void internal_OnCharacterContactPersisted_custom(long inCharacter_addr, long inOtherCharacter_addr, long inSubShapeID2_addr, long inContactPosition_addr, long inContactNormal_addr, long ioSettings_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_14 == null)
            CharacterVirtual_TEMP_STATIC_GEN_14 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_14.internal_reset(inCharacter_addr, false);
        if (CharacterVirtual_TEMP_STATIC_GEN_15 == null)
            CharacterVirtual_TEMP_STATIC_GEN_15 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_15.internal_reset(inOtherCharacter_addr, false);
        if (SubShapeID_TEMP_STATIC_GEN_6 == null)
            SubShapeID_TEMP_STATIC_GEN_6 = SubShapeID.native_new();
        SubShapeID_TEMP_STATIC_GEN_6.internal_reset(inSubShapeID2_addr, false);
        if (Vec3_TEMP_STATIC_GEN_5 == null)
            Vec3_TEMP_STATIC_GEN_5 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_5.internal_reset(inContactPosition_addr, false);
        if (Vec3_TEMP_STATIC_GEN_6 == null)
            Vec3_TEMP_STATIC_GEN_6 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_6.internal_reset(inContactNormal_addr, false);
        if (CharacterContactSettings_TEMP_STATIC_GEN_6 == null)
            CharacterContactSettings_TEMP_STATIC_GEN_6 = CharacterContactSettings.native_new();
        CharacterContactSettings_TEMP_STATIC_GEN_6.internal_reset(ioSettings_addr, false);
        OnCharacterContactPersisted(CharacterVirtual_TEMP_STATIC_GEN_14, CharacterVirtual_TEMP_STATIC_GEN_15, SubShapeID_TEMP_STATIC_GEN_6, Vec3_TEMP_STATIC_GEN_5, Vec3_TEMP_STATIC_GEN_6, CharacterContactSettings_TEMP_STATIC_GEN_6);
    }

    protected void OnCharacterContactPersisted(CharacterVirtual inCharacter, CharacterVirtualContact inContact, CharacterContactSettings ioSettings) {
    }

    private void internal_OnCharacterContactPersistedFull_custom(long inCharacter_addr, long inContact_addr, long ioSettings_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_16 == null)
            CharacterVirtual_TEMP_STATIC_GEN_16 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_16.internal_reset(inCharacter_addr, false);
        if (CharacterVirtualContact_TEMP_STATIC_GEN_5 == null)
            CharacterVirtualContact_TEMP_STATIC_GEN_5 = CharacterVirtualContact.native_new();
        CharacterVirtualContact_TEMP_STATIC_GEN_5.internal_reset(inContact_addr, false);
        if (CharacterContactSettings_TEMP_STATIC_GEN_7 == null)
            CharacterContactSettings_TEMP_STATIC_GEN_7 = CharacterContactSettings.native_new();
        CharacterContactSettings_TEMP_STATIC_GEN_7.internal_reset(ioSettings_addr, false);
        OnCharacterContactPersisted(CharacterVirtual_TEMP_STATIC_GEN_16, CharacterVirtualContact_TEMP_STATIC_GEN_5, CharacterContactSettings_TEMP_STATIC_GEN_7);
    }

    protected void OnCharacterContactRemoved(CharacterVirtual inCharacter, CharacterID inOtherCharacter, SubShapeID inSubShapeID2) {
    }

    private void internal_OnCharacterContactRemoved_custom(long inCharacter_addr, long inOtherCharacter_addr, long inSubShapeID2_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_17 == null)
            CharacterVirtual_TEMP_STATIC_GEN_17 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_17.internal_reset(inCharacter_addr, false);
        if (CharacterID_TEMP_STATIC_GEN_0 == null)
            CharacterID_TEMP_STATIC_GEN_0 = CharacterID.native_new();
        CharacterID_TEMP_STATIC_GEN_0.internal_reset(inOtherCharacter_addr, false);
        if (SubShapeID_TEMP_STATIC_GEN_7 == null)
            SubShapeID_TEMP_STATIC_GEN_7 = SubShapeID.native_new();
        SubShapeID_TEMP_STATIC_GEN_7.internal_reset(inSubShapeID2_addr, false);
        OnCharacterContactRemoved(CharacterVirtual_TEMP_STATIC_GEN_17, CharacterID_TEMP_STATIC_GEN_0, SubShapeID_TEMP_STATIC_GEN_7);
    }

    protected void OnContactSolve(CharacterVirtual inCharacter, BodyID inBodyID2, SubShapeID inSubShapeID2, RVec3 inContactPosition, Vec3 inContactNormal, Vec3 inContactVelocity, PhysicsMaterial inContactMaterial, Vec3 inCharacterVelocity, Vec3 ioNewCharacterVelocity) {
    }

    private void internal_OnContactSolve_custom(long inCharacter_addr, long inBodyID2_addr, long inSubShapeID2_addr, long inContactPosition_addr, long inContactNormal_addr, long inContactVelocity_addr, long inContactMaterial_addr, long inCharacterVelocity_addr, long ioNewCharacterVelocity_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_18 == null)
            CharacterVirtual_TEMP_STATIC_GEN_18 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_18.internal_reset(inCharacter_addr, false);
        if (BodyID_TEMP_STATIC_GEN_4 == null)
            BodyID_TEMP_STATIC_GEN_4 = BodyID.native_new();
        BodyID_TEMP_STATIC_GEN_4.internal_reset(inBodyID2_addr, false);
        if (SubShapeID_TEMP_STATIC_GEN_8 == null)
            SubShapeID_TEMP_STATIC_GEN_8 = SubShapeID.native_new();
        SubShapeID_TEMP_STATIC_GEN_8.internal_reset(inSubShapeID2_addr, false);
        if (RVec3_TEMP_STATIC_GEN_3 == null)
            RVec3_TEMP_STATIC_GEN_3 = RVec3.native_new();
        RVec3_TEMP_STATIC_GEN_3.internal_reset(inContactPosition_addr, false);
        if (Vec3_TEMP_STATIC_GEN_7 == null)
            Vec3_TEMP_STATIC_GEN_7 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_7.internal_reset(inContactNormal_addr, false);
        if (Vec3_TEMP_STATIC_GEN_8 == null)
            Vec3_TEMP_STATIC_GEN_8 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_8.internal_reset(inContactVelocity_addr, false);
        if (PhysicsMaterial_TEMP_STATIC_GEN_0 == null)
            PhysicsMaterial_TEMP_STATIC_GEN_0 = PhysicsMaterial.native_new();
        PhysicsMaterial_TEMP_STATIC_GEN_0.internal_reset(inContactMaterial_addr, false);
        if (Vec3_TEMP_STATIC_GEN_9 == null)
            Vec3_TEMP_STATIC_GEN_9 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_9.internal_reset(inCharacterVelocity_addr, false);
        if (Vec3_TEMP_STATIC_GEN_10 == null)
            Vec3_TEMP_STATIC_GEN_10 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_10.internal_reset(ioNewCharacterVelocity_addr, false);
        OnContactSolve(CharacterVirtual_TEMP_STATIC_GEN_18, BodyID_TEMP_STATIC_GEN_4, SubShapeID_TEMP_STATIC_GEN_8, RVec3_TEMP_STATIC_GEN_3, Vec3_TEMP_STATIC_GEN_7, Vec3_TEMP_STATIC_GEN_8, PhysicsMaterial_TEMP_STATIC_GEN_0, Vec3_TEMP_STATIC_GEN_9, Vec3_TEMP_STATIC_GEN_10);
    }

    protected void OnCharacterContactSolve(CharacterVirtual inCharacter, CharacterVirtual inOtherCharacter, SubShapeID inSubShapeID2, RVec3 inContactPosition, Vec3 inContactNormal, Vec3 inContactVelocity, PhysicsMaterial inContactMaterial, Vec3 inCharacterVelocity, Vec3 ioNewCharacterVelocity) {
    }

    private void internal_OnCharacterContactSolve_custom(long inCharacter_addr, long inOtherCharacter_addr, long inSubShapeID2_addr, long inContactPosition_addr, long inContactNormal_addr, long inContactVelocity_addr, long inContactMaterial_addr, long inCharacterVelocity_addr, long ioNewCharacterVelocity_addr) {
        if (CharacterVirtual_TEMP_STATIC_GEN_19 == null)
            CharacterVirtual_TEMP_STATIC_GEN_19 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_19.internal_reset(inCharacter_addr, false);
        if (CharacterVirtual_TEMP_STATIC_GEN_20 == null)
            CharacterVirtual_TEMP_STATIC_GEN_20 = CharacterVirtual.native_new();
        CharacterVirtual_TEMP_STATIC_GEN_20.internal_reset(inOtherCharacter_addr, false);
        if (SubShapeID_TEMP_STATIC_GEN_9 == null)
            SubShapeID_TEMP_STATIC_GEN_9 = SubShapeID.native_new();
        SubShapeID_TEMP_STATIC_GEN_9.internal_reset(inSubShapeID2_addr, false);
        if (RVec3_TEMP_STATIC_GEN_4 == null)
            RVec3_TEMP_STATIC_GEN_4 = RVec3.native_new();
        RVec3_TEMP_STATIC_GEN_4.internal_reset(inContactPosition_addr, false);
        if (Vec3_TEMP_STATIC_GEN_11 == null)
            Vec3_TEMP_STATIC_GEN_11 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_11.internal_reset(inContactNormal_addr, false);
        if (Vec3_TEMP_STATIC_GEN_12 == null)
            Vec3_TEMP_STATIC_GEN_12 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_12.internal_reset(inContactVelocity_addr, false);
        if (PhysicsMaterial_TEMP_STATIC_GEN_1 == null)
            PhysicsMaterial_TEMP_STATIC_GEN_1 = PhysicsMaterial.native_new();
        PhysicsMaterial_TEMP_STATIC_GEN_1.internal_reset(inContactMaterial_addr, false);
        if (Vec3_TEMP_STATIC_GEN_13 == null)
            Vec3_TEMP_STATIC_GEN_13 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_13.internal_reset(inCharacterVelocity_addr, false);
        if (Vec3_TEMP_STATIC_GEN_14 == null)
            Vec3_TEMP_STATIC_GEN_14 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_14.internal_reset(ioNewCharacterVelocity_addr, false);
        OnCharacterContactSolve(CharacterVirtual_TEMP_STATIC_GEN_19, CharacterVirtual_TEMP_STATIC_GEN_20, SubShapeID_TEMP_STATIC_GEN_9, RVec3_TEMP_STATIC_GEN_4, Vec3_TEMP_STATIC_GEN_11, Vec3_TEMP_STATIC_GEN_12, PhysicsMaterial_TEMP_STATIC_GEN_1, Vec3_TEMP_STATIC_GEN_13, Vec3_TEMP_STATIC_GEN_14);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_OnAdjustBodyVelocity_custom;

    private MemorySegment upcallStub_OnContactValidate_custom;

    private MemorySegment upcallStub_OnContactValidateFull_custom;

    private MemorySegment upcallStub_OnCharacterContactValidate_custom;

    private MemorySegment upcallStub_OnCharacterContactValidateFull_custom;

    private MemorySegment upcallStub_OnContactAdded_custom;

    private MemorySegment upcallStub_OnContactAddedFull_custom;

    private MemorySegment upcallStub_OnContactPersisted_custom;

    private MemorySegment upcallStub_OnContactPersistedFull_custom;

    private MemorySegment upcallStub_OnContactRemoved_custom;

    private MemorySegment upcallStub_OnCharacterContactAdded_custom;

    private MemorySegment upcallStub_OnCharacterContactAddedFull_custom;

    private MemorySegment upcallStub_OnCharacterContactPersisted_custom;

    private MemorySegment upcallStub_OnCharacterContactPersistedFull_custom;

    private MemorySegment upcallStub_OnCharacterContactRemoved_custom;

    private MemorySegment upcallStub_OnContactSolve_custom;

    private MemorySegment upcallStub_OnCharacterContactSolve_custom;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_OnAdjustBodyVelocity_custom = null;
        upcallStub_OnContactValidate_custom = null;
        upcallStub_OnContactValidateFull_custom = null;
        upcallStub_OnCharacterContactValidate_custom = null;
        upcallStub_OnCharacterContactValidateFull_custom = null;
        upcallStub_OnContactAdded_custom = null;
        upcallStub_OnContactAddedFull_custom = null;
        upcallStub_OnContactPersisted_custom = null;
        upcallStub_OnContactPersistedFull_custom = null;
        upcallStub_OnContactRemoved_custom = null;
        upcallStub_OnCharacterContactAdded_custom = null;
        upcallStub_OnCharacterContactAddedFull_custom = null;
        upcallStub_OnCharacterContactPersisted_custom = null;
        upcallStub_OnCharacterContactPersistedFull_custom = null;
        upcallStub_OnCharacterContactRemoved_custom = null;
        upcallStub_OnContactSolve_custom = null;
        upcallStub_OnCharacterContactSolve_custom = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long OnAdjustBodyVelocity_custom_fp, long OnContactValidate_custom_fp, long OnContactValidateFull_custom_fp, long OnCharacterContactValidate_custom_fp, long OnCharacterContactValidateFull_custom_fp, long OnContactAdded_custom_fp, long OnContactAddedFull_custom_fp, long OnContactPersisted_custom_fp, long OnContactPersistedFull_custom_fp, long OnContactRemoved_custom_fp, long OnCharacterContactAdded_custom_fp, long OnCharacterContactAddedFull_custom_fp, long OnCharacterContactPersisted_custom_fp, long OnCharacterContactPersistedFull_custom_fp, long OnCharacterContactRemoved_custom_fp, long OnContactSolve_custom_fp, long OnCharacterContactSolve_custom_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJJJJJJJJJJJJJJJJJ.invokeExact(this_addr, OnAdjustBodyVelocity_custom_fp, OnContactValidate_custom_fp, OnContactValidateFull_custom_fp, OnCharacterContactValidate_custom_fp, OnCharacterContactValidateFull_custom_fp, OnContactAdded_custom_fp, OnContactAddedFull_custom_fp, OnContactPersisted_custom_fp, OnContactPersistedFull_custom_fp, OnContactRemoved_custom_fp, OnCharacterContactAdded_custom_fp, OnCharacterContactAddedFull_custom_fp, OnCharacterContactPersisted_custom_fp, OnCharacterContactPersistedFull_custom_fp, OnCharacterContactRemoved_custom_fp, OnContactSolve_custom_fp, OnCharacterContactSolve_custom_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_OnAdjustBodyVelocity__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_onadjustbodyvelocity", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnAdjustBodyVelocity__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_onadjustbodyvelocity", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnContactValidate__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncontactvalidate", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnContactValidate__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncontactvalidate", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnContactValidateFull__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncontactvalidatefull", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnContactValidateFull__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncontactvalidatefull", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnCharacterContactValidate__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncharactercontactvalidate", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnCharacterContactValidate__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncharactercontactvalidate", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnCharacterContactValidateFull__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncharactercontactvalidatefull", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnCharacterContactValidateFull__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncharactercontactvalidatefull", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnContactAdded__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncontactadded", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnContactAdded__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncontactadded", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnContactAddedFull__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncontactaddedfull", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnContactAddedFull__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncontactaddedfull", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnContactPersisted__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncontactpersisted", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnContactPersisted__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncontactpersisted", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnContactPersistedFull__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncontactpersistedfull", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnContactPersistedFull__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncontactpersistedfull", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnContactRemoved__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncontactremoved", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnContactRemoved__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncontactremoved", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnCharacterContactAdded__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncharactercontactadded", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnCharacterContactAdded__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncharactercontactadded", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnCharacterContactAddedFull__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncharactercontactaddedfull", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnCharacterContactAddedFull__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncharactercontactaddedfull", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnCharacterContactPersisted__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncharactercontactpersisted", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnCharacterContactPersisted__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncharactercontactpersisted", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnCharacterContactPersistedFull__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncharactercontactpersistedfull", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnCharacterContactPersistedFull__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncharactercontactpersistedfull", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnCharacterContactRemoved__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncharactercontactremoved", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnCharacterContactRemoved__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncharactercontactremoved", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnContactSolve__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncontactsolve", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnContactSolve__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncontactsolve", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OnCharacterContactSolve__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_get_oncharactercontactsolve", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OnCharacterContactSolve__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_set_oncharactercontactsolve", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJJJJJJJJJJJJJJJJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_character_charactercontactlistener_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
