/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision;

import com.github.xpenatan.jParser.api.NativeObject;

public class ShapeFilter extends NativeObject {

    static public final ShapeFilter NULL = ShapeFilter.native_new();

    public ShapeFilter() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return jolt.physics.collision.natives.JNI_ShapeFilter.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ShapeFilter(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ShapeFilter native_new() {
        return new ShapeFilter((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.collision.natives.JNI_ShapeFilter.internal_native_deleteNative(this_addr);
    }
}
