/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_PlaneShape {

    public static native long internal_native_create_Plane_PhysicsMaterial_float_addr(long inPlane_addr, long inMaterial_addr, float inHalfExtent);

    public static native long internal_native_create_Plane_PhysicsMaterial_addr(long inPlane_addr, long inMaterial_addr);

    public static native long internal_native_create_Plane_addr(long inPlane_addr);

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_SetMaterial(long this_addr, long inMaterial_addr);

    public static native long internal_native_GetPlane_addr(long this_addr);

    public static native float internal_native_GetHalfExtent(long this_addr);
}
