/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_HeightFieldShapeSettings {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_get_mOffset_addr(long this_addr);

    public static native void internal_native_set_mOffset(long this_addr, long mOffset_addr);

    public static native long internal_native_get_mScale_addr(long this_addr);

    public static native void internal_native_set_mScale(long this_addr, long mScale_addr);

    public static native int internal_native_get_mSampleCount(long this_addr);

    public static native void internal_native_set_mSampleCount(long this_addr, int mSampleCount);

    public static native float internal_native_get_mMinHeightValue(long this_addr);

    public static native void internal_native_set_mMinHeightValue(long this_addr, float mMinHeightValue);

    public static native float internal_native_get_mMaxHeightValue(long this_addr);

    public static native void internal_native_set_mMaxHeightValue(long this_addr, float mMaxHeightValue);

    public static native int internal_native_get_mMaterialsCapacity(long this_addr);

    public static native void internal_native_set_mMaterialsCapacity(long this_addr, int mMaterialsCapacity);

    public static native int internal_native_get_mBlockSize(long this_addr);

    public static native void internal_native_set_mBlockSize(long this_addr, int mBlockSize);

    public static native int internal_native_get_mBitsPerSample(long this_addr);

    public static native void internal_native_set_mBitsPerSample(long this_addr, int mBitsPerSample);

    public static native long internal_native_get_mHeightSamples_addr(long this_addr);

    public static native void internal_native_set_mHeightSamples(long this_addr, long mHeightSamples_addr);

    public static native long internal_native_get_mMaterialIndices_addr(long this_addr);

    public static native void internal_native_set_mMaterialIndices(long this_addr, long mMaterialIndices_addr);

    public static native long internal_native_get_mMaterials_addr(long this_addr);

    public static native void internal_native_set_mMaterials(long this_addr, long mMaterials_addr);

    public static native float internal_native_get_mActiveEdgeCosThresholdAngle(long this_addr);

    public static native void internal_native_set_mActiveEdgeCosThresholdAngle(long this_addr, float mActiveEdgeCosThresholdAngle);
}
