/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_TaperedCylinderShapeSettings {

    public static native long internal_native_create_float_float_float_float_PhysicsMaterial_addr(float inHalfHeightOfTaperedCylinder, float inTopRadius, float inBottomRadius, float inConvexRadius, long inMaterial_addr);

    public static native long internal_native_create_float_float_float_float_addr(float inHalfHeightOfTaperedCylinder, float inTopRadius, float inBottomRadius, float inConvexRadius);

    public static native long internal_native_create_float_float_float_addr(float inHalfHeightOfTaperedCylinder, float inTopRadius, float inBottomRadius);

    public static native void internal_native_deleteNative(long this_addr);

    public static native float internal_native_get_mHalfHeight(long this_addr);

    public static native void internal_native_set_mHalfHeight(long this_addr, float mHalfHeight);

    public static native float internal_native_get_mTopRadius(long this_addr);

    public static native void internal_native_set_mTopRadius(long this_addr, float mTopRadius);

    public static native float internal_native_get_mBottomRadius(long this_addr);

    public static native void internal_native_set_mBottomRadius(long this_addr, float mBottomRadius);

    public static native float internal_native_get_mConvexRadius(long this_addr);

    public static native void internal_native_set_mConvexRadius(long this_addr, float mConvexRadius);
}
