/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_PlaneShapeSettings {

    public static native long internal_native_create_Plane_PhysicsMaterial_float_addr(long inPlane_addr, long inMaterial_addr, float inHalfExtent);

    public static native long internal_native_create_Plane_PhysicsMaterial_addr(long inPlane_addr, long inMaterial_addr);

    public static native long internal_native_create_Plane_addr(long inPlane_addr);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_get_mPlane_addr(long this_addr);

    public static native void internal_native_set_mPlane(long this_addr, long mPlane_addr);

    public static native long internal_native_get_mMaterial_addr(long this_addr);

    public static native void internal_native_set_mMaterial(long this_addr, long mMaterial_addr);

    public static native float internal_native_get_mHalfExtent(long this_addr);

    public static native void internal_native_set_mHalfExtent(long this_addr, float mHalfExtent);
}
