/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_ConvexShape {

    public static native float internal_native_GetDensity(long this_addr);

    public static native void internal_native_SetDensity(long this_addr, float inDensity);
}
