/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_MeshShape {

    public static native int internal_native_GetTriangleUserData(long this_addr, long inSubShapeID_addr);
}
