/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_ShapeCastSettings {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native float internal_native_get_mExtraConvexRadius(long this_addr);

    public static native void internal_native_set_mExtraConvexRadius(long this_addr, float mExtraConvexRadius);

    public static native int internal_native_get_mBackFaceModeTriangles(long this_addr);

    public static native void internal_native_set_mBackFaceModeTriangles(long this_addr, int mBackFaceModeTriangles);

    public static native int internal_native_get_mBackFaceModeConvex(long this_addr);

    public static native void internal_native_set_mBackFaceModeConvex(long this_addr, int mBackFaceModeConvex);

    public static native boolean internal_native_get_mUseShrunkenShapeAndConvexRadius(long this_addr);

    public static native void internal_native_set_mUseShrunkenShapeAndConvexRadius(long this_addr, boolean mUseShrunkenShapeAndConvexRadius);

    public static native boolean internal_native_get_mReturnDeepestPoint(long this_addr);

    public static native void internal_native_set_mReturnDeepestPoint(long this_addr, boolean mReturnDeepestPoint);
}
