/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_ShapeCastResult {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native float internal_native_get_mFraction(long this_addr);

    public static native void internal_native_set_mFraction(long this_addr, float mFraction);

    public static native boolean internal_native_get_mIsBackFaceHit(long this_addr);

    public static native void internal_native_set_mIsBackFaceHit(long this_addr, boolean mIsBackFaceHit);
}
