/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_CompoundShapeSettings {

    public static native void internal_native_AddShape__0(long this_addr, long inPosition_addr, long inRotation_addr, long inShape_addr, int inUserData);

    public static native void internal_native_AddShape__0(long this_addr, long inPosition_addr, long inRotation_addr, long inShape_addr);

    public static native void internal_native_AddShape__1(long this_addr, long inPosition_addr, long inRotation_addr, long inShape_addr, int inUserData);

    public static native void internal_native_AddShape__1(long this_addr, long inPosition_addr, long inRotation_addr, long inShape_addr);
}
