/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_RotatedTranslatedShapeSettings {

    public static native long internal_native_create_Vec3_Quat_ShapeSettings_addr(long inPosition_addr, long inRotation_addr, long inShape_addr);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_get_mPosition_addr(long this_addr);

    public static native void internal_native_set_mPosition(long this_addr, long mPosition_addr);

    public static native long internal_native_get_mRotation_addr(long this_addr);

    public static native void internal_native_set_mRotation(long this_addr, long mRotation_addr);
}
