/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_RotatedTranslatedShape {

    public static native long internal_native_GetRotation_addr(long this_addr);

    public static native long internal_native_GetPosition_addr(long this_addr);
}
