/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.constraints;

import com.github.xpenatan.jParser.api.NativeObject;

public class PathConstraintPath extends NativeObject {

    static public final PathConstraintPath NULL = PathConstraintPath.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected PathConstraintPath(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static PathConstraintPath native_new() {
        return new PathConstraintPath((byte) 0, (char) 0);
    }

    public boolean IsLooping() {
        return false;
    }

    public void SetIsLooping(boolean inIsLooping) {
    }

    public int GetRefCount() {
        return 0;
    }

    public void AddRef() {
    }

    public void Release() {
    }
}
