/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums.natives;

import jolt.enums.*;

final public class JNI_ETireFrictionDirection {

    static native public int ETireFrictionDirection_Longitudinal_NATIVE();

    static native public int ETireFrictionDirection_Lateral_NATIVE();
}
