/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums.natives;

import jolt.enums.*;

final public class JNI_EShapeColor {

    static native public int EShapeColor_InstanceColor_NATIVE();

    static native public int EShapeColor_ShapeTypeColor_NATIVE();

    static native public int EShapeColor_MotionTypeColor_NATIVE();

    static native public int EShapeColor_SleepColor_NATIVE();

    static native public int EShapeColor_IslandColor_NATIVE();

    static native public int EShapeColor_MaterialColor_NATIVE();
}
