/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums.natives;

import jolt.enums.*;

final public class JNI_EGroundState {

    static native public int EGroundState_OnGround_NATIVE();

    static native public int EGroundState_OnSteepGround_NATIVE();

    static native public int EGroundState_NotSupported_NATIVE();

    static native public int EGroundState_InAir_NATIVE();
}
