/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums.natives;

import jolt.enums.*;

final public class JNI_ECastShadow {

    static native public int ECastShadow_On_NATIVE();

    static native public int ECastShadow_Off_NATIVE();
}
