/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums.natives;

import jolt.enums.*;

final public class JNI_EShapeSubType {

    static native public int EShapeSubType_Sphere_NATIVE();

    static native public int EShapeSubType_Box_NATIVE();

    static native public int EShapeSubType_Capsule_NATIVE();

    static native public int EShapeSubType_TaperedCapsule_NATIVE();

    static native public int EShapeSubType_Cylinder_NATIVE();

    static native public int EShapeSubType_TaperedCylinder_NATIVE();

    static native public int EShapeSubType_ConvexHull_NATIVE();

    static native public int EShapeSubType_StaticCompound_NATIVE();

    static native public int EShapeSubType_MutableCompound_NATIVE();

    static native public int EShapeSubType_RotatedTranslated_NATIVE();

    static native public int EShapeSubType_Scaled_NATIVE();

    static native public int EShapeSubType_OffsetCenterOfMass_NATIVE();

    static native public int EShapeSubType_Mesh_NATIVE();

    static native public int EShapeSubType_HeightField_NATIVE();

    static native public int EShapeSubType_Plane_NATIVE();

    static native public int EShapeSubType_Empty_NATIVE();
}
