/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums.natives;

import jolt.enums.*;

final public class JNI_ESpringMode {

    static native public int ESpringMode_FrequencyAndDamping_NATIVE();

    static native public int ESpringMode_StiffnessAndDamping_NATIVE();

    static native public int ESpringMode_MassNormalizedStiffnessAndDamping_NATIVE();
}
