/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums.natives;

import jolt.enums.*;

final public class JNI_EBackFaceMode {

    static native public int EBackFaceMode_IgnoreBackFaces_NATIVE();

    static native public int EBackFaceMode_CollideWithBackFaces_NATIVE();
}
