/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.natives;

import jolt.*;

final public class JNI_JoltNew {

    public static native long internal_native_PhysicsSystem__0_addr();

    public static native long internal_native_Factory__0_addr();

    public static native long internal_native_TempAllocatorImpl__0_addr(int inSize);

    public static native long internal_native_JobSystemThreadPool__0_addr(int inMaxJobs, int inMaxBarriers, int inNumThreads);

    public static native long internal_native_JobSystemThreadPool__0_addr(int inMaxJobs, int inMaxBarriers);

    public static native long internal_native_Mat44__0_addr();

    public static native long internal_native_Mat44__1_addr(long inC1_addr, long inC2_addr, long inC3_addr, long inC4_addr);

    public static native long internal_native_Mat44__2_addr(long inC1_addr, long inC2_addr, long inC3_addr, long inC4_addr);

    public static native long internal_native_Vec3__0_addr();

    public static native long internal_native_Vec3__1_addr(float inX, float inY, float inZ);

    public static native long internal_native_Vec3__2_addr(long inRHS_addr);

    public static native long internal_native_Vec3__3_addr(long inV_addr);

    public static native long internal_native_Vec4__0_addr();

    public static native long internal_native_Vec4__1_addr(float inX, float inY, float inZ, float inW);

    public static native long internal_native_Vec4__2_addr(long inV_addr);

    public static native long internal_native_Vec4__3_addr(long inV_addr, float inW);

    public static native long internal_native_Quat__0_addr();

    public static native long internal_native_Quat__1_addr(float inX, float inY, float inZ, float inW);

    public static native long internal_native_BodyCreationSettings__0_addr();

    public static native long internal_native_BodyCreationSettings__1_addr(long inShape_addr, long inPosition_addr, long inRotation_addr, int inMotionType, int inObjectLayer);

    public static native long internal_native_BodyCreationSettings__2_addr(long inShape_addr, long inPosition_addr, long inRotation_addr, int inMotionType, int inObjectLayer);

    public static native long internal_native_RotatedTranslatedShapeSettings__0_addr();

    public static native long internal_native_RotatedTranslatedShapeSettings__1_addr(long inPosition_addr, long inRotation_addr, long inShape_addr);

    public static native long internal_native_RotatedTranslatedShapeSettings__2_addr(long inPosition_addr, long inRotation_addr, long inShape_addr);

    public static native long internal_native_MeshShapeSettings__0_addr();

    public static native long internal_native_MeshShapeSettings__1_addr(long inTriangleList_addr, long inMaterialList_addr);

    public static native long internal_native_MeshShapeSettings__1_addr(long inTriangleList_addr);

    public static native long internal_native_MeshShapeSettings__2_addr(long inVertices_addr, long inTriangles_addr, long inMaterialList_addr);
}
