/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.natives;

import jolt.*;

final public class JNI_RVec3 {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_float_float_float_addr(float inX, float inY, float inZ);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_sZero_addr();

    public static native long internal_native_sOne_addr();

    public static native long internal_native_sAxisX_addr();

    public static native long internal_native_sAxisY_addr();

    public static native long internal_native_sAxisZ_addr();

    public static native long internal_native_sReplicate_addr(float inValue);

    public static native long internal_native_sMin_addr(long inLHS_addr, long inRHS_addr);

    public static native long internal_native_sMax_addr(long inLHS_addr, long inRHS_addr);

    public static native long internal_native_sClamp_addr(long inValue_addr, long inMin_addr, long inMax_addr);

    public static native float internal_native_GetComponent(long this_addr, int inCoordinate);

    public static native boolean internal_native_Equals(long this_addr, long inV_addr);

    public static native boolean internal_native_NotEquals(long this_addr, long inV_addr);

    public static native float internal_native_LengthSq(long this_addr);

    public static native float internal_native_Length(long this_addr);

    public static native long internal_native_Normalized_addr(long this_addr);

    public static native float internal_native_GetX(long this_addr);

    public static native float internal_native_GetY(long this_addr);

    public static native float internal_native_GetZ(long this_addr);

    public static native void internal_native_SetX(long this_addr, float inX);

    public static native void internal_native_SetY(long this_addr, float inY);

    public static native void internal_native_SetZ(long this_addr, float inZ);

    public static native void internal_native_Set(long this_addr, float inX, float inY, float inZ);

    public static native void internal_native_SetComponent(long this_addr, int inCoordinate, float inValue);

    public static native boolean internal_native_IsNearZero(long this_addr, float inMaxDistSq);

    public static native boolean internal_native_IsNearZero(long this_addr);

    public static native boolean internal_native_IsClose(long this_addr, long inV_addr, float inMaxDistSq);

    public static native boolean internal_native_IsClose(long this_addr, long inV_addr);

    public static native boolean internal_native_IsNormalized(long this_addr, float inTolerance);

    public static native boolean internal_native_IsNormalized(long this_addr);

    public static native long internal_native_Abs_addr(long this_addr);

    public static native long internal_native_Reciprocal_addr(long this_addr);

    public static native long internal_native_Cross_addr(long this_addr, long inRHS_addr);

    public static native float internal_native_Dot(long this_addr, long inRHS_addr);

    public static native long internal_native_Add_addr(long this_addr, long inV_addr);

    public static native long internal_native_Sub_addr(long this_addr, long inV_addr);

    public static native long internal_native_Mul_addr(long this_addr, float inV);

    public static native long internal_native_Div_addr(long this_addr, float inV);

    public static native long internal_native_MulRVec3_addr(long this_addr, long inV_addr);

    public static native long internal_native_MulFloat_addr(long this_addr, float inV);

    public static native long internal_native_DivRVec3_addr(long this_addr, long inV_addr);

    public static native long internal_native_DivFloat_addr(long this_addr, float inV);

    public static native long internal_native_AddRVec3_addr(long this_addr, long inV_addr);

    public static native long internal_native_SubRVec3_addr(long this_addr, long inV_addr);

    public static native long internal_native_Sqrt_addr(long this_addr);

    public static native long internal_native_GetSign_addr(long this_addr);
}
