/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.natives;

import jolt.*;

final public class JNI_Jolt {

    public static native void internal_native_Init();

    public static native void internal_native_RegisterTypes();

    public static native void internal_native_UnregisterTypes();

    public static native void internal_native_ClearWorld(long physicsSystem_addr);

    public static native long internal_native_GetCharacterContactListener_addr(long inCharacter_addr);
}
