/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.natives;

import jolt.*;

final public class JNI_JoltSettings {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_get_mMaxBodies(long this_addr);

    public static native void internal_native_set_mMaxBodies(long this_addr, int mMaxBodies);

    public static native int internal_native_get_mMaxBodyPairs(long this_addr);

    public static native void internal_native_set_mMaxBodyPairs(long this_addr, int mMaxBodyPairs);

    public static native int internal_native_get_mMaxContactConstraints(long this_addr);

    public static native void internal_native_set_mMaxContactConstraints(long this_addr, int mMaxContactConstraints);

    public static native int internal_native_get_mTempAllocatorSize(long this_addr);

    public static native void internal_native_set_mTempAllocatorSize(long this_addr, int mTempAllocatorSize);

    public static native int internal_native_get_mMaxWorkerThreads(long this_addr);

    public static native void internal_native_set_mMaxWorkerThreads(long this_addr, int mMaxWorkerThreads);

    public static native long internal_native_get_mBroadPhaseLayerInterface_addr(long this_addr);

    public static native void internal_native_set_mBroadPhaseLayerInterface(long this_addr, long mBroadPhaseLayerInterface_addr);

    public static native long internal_native_get_mObjectVsBroadPhaseLayerFilter_addr(long this_addr);

    public static native void internal_native_set_mObjectVsBroadPhaseLayerFilter(long this_addr, long mObjectVsBroadPhaseLayerFilter_addr);

    public static native long internal_native_get_mObjectLayerPairFilter_addr(long this_addr);

    public static native void internal_native_set_mObjectLayerPairFilter(long this_addr, long mObjectLayerPairFilter_addr);

    public static native long internal_native_get_mAssertFailedHandler_addr(long this_addr);

    public static native void internal_native_set_mAssertFailedHandler(long this_addr, long mAssertFailedHandler_addr);
}
