/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics;

import com.github.xpenatan.jParser.api.NativeObject;

public class StateRecorder extends NativeObject {

    static public final StateRecorder NULL = StateRecorder.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected StateRecorder(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static StateRecorder native_new() {
        return new StateRecorder((byte) 0, (char) 0);
    }

    public void SetValidating(boolean inValidating) {
    }

    public boolean IsValidating() {
        return false;
    }

    public void SetIsLastPart(boolean inIsLastPart) {
    }

    public boolean IsLastPart() {
        return false;
    }
}
