/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.renderer.natives;

import jolt.renderer.*;

final public class JNI_DebugRendererTriangleTraits {

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_get_mVOffset();

    public static native int internal_native_get_mSize();
}
