/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.broadphase;

import com.github.xpenatan.jParser.api.NativeObject;

public class BroadPhaseLayerInterface extends NativeObject {

    static public final BroadPhaseLayerInterface NULL = BroadPhaseLayerInterface.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected BroadPhaseLayerInterface(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static BroadPhaseLayerInterface native_new() {
        return new BroadPhaseLayerInterface((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.collision.broadphase.natives.JNI_BroadPhaseLayerInterface.internal_native_deleteNative(this_addr);
    }

    public int GetNumBroadPhaseLayers() {
        return internal_native_GetNumBroadPhaseLayers(native_address);
    }

    public static int internal_native_GetNumBroadPhaseLayers(long this_addr) {
        return jolt.physics.collision.broadphase.natives.JNI_BroadPhaseLayerInterface.internal_native_GetNumBroadPhaseLayers(this_addr);
    }
}
