/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.softbody.natives;

import jolt.physics.softbody.*;

final public class JNI_SoftBodySharedSettingsFace {

    public static native long internal_native_create_int_int_int_int_addr(int inVertex1, int inVertex2, int inVertex3, int inMaterialIndex);

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_get_mVertex(long this_addr, int index);

    public static native void internal_native_set_mVertex(long this_addr, int index, int mVertex);

    public static native int internal_native_get_mMaterialIndex(long this_addr);

    public static native void internal_native_set_mMaterialIndex(long this_addr, int mMaterialIndex);
}
