/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.physics.vehicle.WheeledVehicleController;

public class WheeledVehicleControllerCallbacksEm extends NativeObject {

    static private TireMaxImpulseCallbackResult TireMaxImpulseCallbackResult_TEMP_STATIC_GEN_0;

    static public final WheeledVehicleControllerCallbacksEm NULL = WheeledVehicleControllerCallbacksEm.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WheeledVehicleControllerCallbacksEm(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WheeledVehicleControllerCallbacksEm native_new() {
        return new WheeledVehicleControllerCallbacksEm((byte) 0, (char) 0);
    }

    public void SetWheeledVehicleController(WheeledVehicleController inController) {
    }

    public WheeledVehicleControllerCallbacksEm() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
    }

    protected void OnTireMaxImpulseCallback(int inWheelIndex, TireMaxImpulseCallbackResult outResult, float inSuspensionImpulse, float inLongitudinalFriction, float inLateralFriction, float inLongitudinalSlip, float inLateralSlip, float inDeltaTime) {
    }

    private void internal_OnTireMaxImpulseCallback(int inWheelIndex, long outResult_addr, float inSuspensionImpulse, float inLongitudinalFriction, float inLateralFriction, float inLongitudinalSlip, float inLateralSlip, float inDeltaTime) {
        if (TireMaxImpulseCallbackResult_TEMP_STATIC_GEN_0 == null)
            TireMaxImpulseCallbackResult_TEMP_STATIC_GEN_0 = TireMaxImpulseCallbackResult.native_new();
        TireMaxImpulseCallbackResult_TEMP_STATIC_GEN_0.internal_reset(outResult_addr, false);
        OnTireMaxImpulseCallback(inWheelIndex, TireMaxImpulseCallbackResult_TEMP_STATIC_GEN_0, inSuspensionImpulse, inLongitudinalFriction, inLateralFriction, inLongitudinalSlip, inLateralSlip, inDeltaTime);
    }

    public static native long internal_native_create_addr();
}
