/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision;

import com.github.xpenatan.jParser.api.NativeObject;

public class ObjectLayerFilter extends NativeObject {

    static public final ObjectLayerFilter NULL = ObjectLayerFilter.native_new();

    @Deprecated()
    protected ObjectLayerFilter(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ObjectLayerFilter native_new() {
        return new ObjectLayerFilter((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.collision.natives.JNI_ObjectLayerFilter.internal_native_deleteNative(this_addr);
    }

    public ObjectLayerFilter() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        internal_native_setupCallback(native_address);
    }

    protected boolean ShouldCollide(int inLayer) {
        return false;
    }

    private boolean internal_ShouldCollide(int inLayer) {
        return ShouldCollide(inLayer);
    }

    public static long internal_native_create_addr() {
        return jolt.physics.collision.natives.JNI_ObjectLayerFilter.internal_native_create_addr();
    }

    public native void internal_native_setupCallback(long this_addr);
}
