/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape;

public class DecoratedShape extends Shape {

    private Shape Shape_TEMP_GEN_0;

    static public final DecoratedShape NULL = DecoratedShape.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected DecoratedShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static DecoratedShape native_new() {
        return new DecoratedShape((byte) 0, (char) 0);
    }

    public Shape GetInnerShape() {
        long addr = internal_native_GetInnerShape_addr(native_address);
        if (addr == 0)
            return Shape.NULL;
        if (Shape_TEMP_GEN_0 == null)
            Shape_TEMP_GEN_0 = Shape.native_new();
        Shape_TEMP_GEN_0.internal_reset(addr, false);
        return Shape_TEMP_GEN_0;
    }

    public static long internal_native_GetInnerShape_addr(long this_addr) {
        return jolt.physics.collision.shape.natives.JNI_DecoratedShape.internal_native_GetInnerShape_addr(this_addr);
    }
}
