/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.renderer;

import com.github.xpenatan.jparser.runtime.helper.NativeFloatArray;
import jolt.physics.PhysicsSystem;
import jolt.physics.body.BodyManagerDrawSettings;
import jolt.physics.collision.shape.Shape;
import jolt.math.Mat44;
import jolt.math.Vec3;
import jolt.core.Color;
import jolt.physics.body.Body;
import jolt.physics.constraints.Constraint;
import jolt.enums.ECastShadow;
import jolt.enums.EDrawMode;
import jolt.enums.ECullMode;
import jolt.geometry.AABox;
import com.github.xpenatan.jParser.api.NativeObject;

public class DebugRendererEm extends DebugRenderer {

    static private Mat44 Mat44_TEMP_STATIC_GEN_0;

    static private NativeFloatArray NativeFloatArray_TEMP_STATIC_GEN_0;

    static private Color Color_TEMP_STATIC_GEN_0;

    static private Vec3 Vec3_TEMP_STATIC_GEN_0;

    static private Vec3 Vec3_TEMP_STATIC_GEN_1;

    static private Color Color_TEMP_STATIC_GEN_1;

    static private Vec3 Vec3_TEMP_STATIC_GEN_2;

    static private Vec3 Vec3_TEMP_STATIC_GEN_3;

    static private Vec3 Vec3_TEMP_STATIC_GEN_4;

    static private Color Color_TEMP_STATIC_GEN_2;

    static private Vec3 Vec3_TEMP_STATIC_GEN_5;

    static private NativeObject NativeObject_TEMP_STATIC_GEN_0;

    static private Color Color_TEMP_STATIC_GEN_3;

    static private Mat44 Mat44_TEMP_STATIC_GEN_1;

    static private AABox AABox_TEMP_STATIC_GEN_0;

    static private Color Color_TEMP_STATIC_GEN_4;

    static private NativeObject NativeObject_TEMP_STATIC_GEN_1;

    static private NativeObject NativeObject_TEMP_STATIC_GEN_2;

    static private NativeObject NativeObject_TEMP_STATIC_GEN_3;

    static public final DebugRendererEm NULL = DebugRendererEm.native_new();

    @Deprecated()
    protected DebugRendererEm(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static DebugRendererEm native_new() {
        return new DebugRendererEm((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.renderer.natives.JNI_DebugRendererEm.internal_native_deleteNative(this_addr);
    }

    public void Initialize() {
        internal_native_Initialize(native_address);
    }

    public static void internal_native_Initialize(long this_addr) {
        jolt.renderer.natives.JNI_DebugRendererEm.internal_native_Initialize(this_addr);
    }

    public void DrawBodies(PhysicsSystem system, BodyManagerDrawSettings inDrawSettings) {
        internal_native_DrawBodies(native_address, system.native_address, inDrawSettings.native_address);
    }

    public static void internal_native_DrawBodies(long this_addr, long system_addr, long inDrawSettings_addr) {
        jolt.renderer.natives.JNI_DebugRendererEm.internal_native_DrawBodies(this_addr, system_addr, inDrawSettings_addr);
    }

    public void DrawBodies(PhysicsSystem system) {
        internal_native_DrawBodies(native_address, system.native_address);
    }

    public static void internal_native_DrawBodies(long this_addr, long system_addr) {
        jolt.renderer.natives.JNI_DebugRendererEm.internal_native_DrawBodies(this_addr, system_addr);
    }

    public void DrawConstraints(PhysicsSystem system) {
        internal_native_DrawConstraints(native_address, system.native_address);
    }

    public static void internal_native_DrawConstraints(long this_addr, long system_addr) {
        jolt.renderer.natives.JNI_DebugRendererEm.internal_native_DrawConstraints(this_addr, system_addr);
    }

    public void DrawConstraintLimits(PhysicsSystem system) {
        internal_native_DrawConstraintLimits(native_address, system.native_address);
    }

    public static void internal_native_DrawConstraintLimits(long this_addr, long system_addr) {
        jolt.renderer.natives.JNI_DebugRendererEm.internal_native_DrawConstraintLimits(this_addr, system_addr);
    }

    public void DrawConstraintReferenceFrame(PhysicsSystem system) {
        internal_native_DrawConstraintReferenceFrame(native_address, system.native_address);
    }

    public static void internal_native_DrawConstraintReferenceFrame(long this_addr, long system_addr) {
        jolt.renderer.natives.JNI_DebugRendererEm.internal_native_DrawConstraintReferenceFrame(this_addr, system_addr);
    }

    public void DrawShape(Shape inShape, Mat44 inModelMatrix, Vec3 inScale, Color inColor, boolean inDrawWireFrame) {
        internal_native_DrawShape(native_address, inShape.native_address, inModelMatrix.native_address, inScale.native_address, inColor.native_address, inDrawWireFrame);
    }

    public static void internal_native_DrawShape(long this_addr, long inShape_addr, long inModelMatrix_addr, long inScale_addr, long inColor_addr, boolean inDrawWireFrame) {
        jolt.renderer.natives.JNI_DebugRendererEm.internal_native_DrawShape(this_addr, inShape_addr, inModelMatrix_addr, inScale_addr, inColor_addr, inDrawWireFrame);
    }

    public void DrawBody(Body inBody, Color inColor, boolean inDrawWireFrame) {
        internal_native_DrawBody(native_address, inBody.native_address, inColor.native_address, inDrawWireFrame);
    }

    public static void internal_native_DrawBody(long this_addr, long inBody_addr, long inColor_addr, boolean inDrawWireFrame) {
        jolt.renderer.natives.JNI_DebugRendererEm.internal_native_DrawBody(this_addr, inBody_addr, inColor_addr, inDrawWireFrame);
    }

    public void DrawConstraint(Constraint inConstraint) {
        internal_native_DrawConstraint(native_address, inConstraint.native_address);
    }

    public static void internal_native_DrawConstraint(long this_addr, long inConstraint_addr) {
        jolt.renderer.natives.JNI_DebugRendererEm.internal_native_DrawConstraint(this_addr, inConstraint_addr);
    }

    public void DrawCylinder(Mat44 inMatrix, float inHalfHeight, float inRadius, Color inColor, ECastShadow inCastShadow, EDrawMode inDrawMode) {
        internal_native_DrawCylinder(native_address, inMatrix.native_address, inHalfHeight, inRadius, inColor.native_address, inCastShadow.getValue(), inDrawMode.getValue());
    }

    public static void internal_native_DrawCylinder(long this_addr, long inMatrix_addr, float inHalfHeight, float inRadius, long inColor_addr, int inCastShadow, int inDrawMode) {
        jolt.renderer.natives.JNI_DebugRendererEm.internal_native_DrawCylinder(this_addr, inMatrix_addr, inHalfHeight, inRadius, inColor_addr, inCastShadow, inDrawMode);
    }

    public void DrawCylinder(Mat44 inMatrix, float inHalfHeight, float inRadius, Color inColor, ECastShadow inCastShadow) {
        internal_native_DrawCylinder(native_address, inMatrix.native_address, inHalfHeight, inRadius, inColor.native_address, inCastShadow.getValue());
    }

    public static void internal_native_DrawCylinder(long this_addr, long inMatrix_addr, float inHalfHeight, float inRadius, long inColor_addr, int inCastShadow) {
        jolt.renderer.natives.JNI_DebugRendererEm.internal_native_DrawCylinder(this_addr, inMatrix_addr, inHalfHeight, inRadius, inColor_addr, inCastShadow);
    }

    public void DrawCylinder(Mat44 inMatrix, float inHalfHeight, float inRadius, Color inColor) {
        internal_native_DrawCylinder(native_address, inMatrix.native_address, inHalfHeight, inRadius, inColor.native_address);
    }

    public static void internal_native_DrawCylinder(long this_addr, long inMatrix_addr, float inHalfHeight, float inRadius, long inColor_addr) {
        jolt.renderer.natives.JNI_DebugRendererEm.internal_native_DrawCylinder(this_addr, inMatrix_addr, inHalfHeight, inRadius, inColor_addr);
    }

    public DebugRendererEm() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        internal_native_setupCallback(native_address);
    }

    protected void DrawMesh(int id, Mat44 inModelMatrix, NativeFloatArray vertices, Color inModelColor, ECullMode inCullMode, EDrawMode inDrawMode) {
    }

    private void internal_DrawMesh(int id, long inModelMatrix_addr, long vertices_addr, long inModelColor_addr, int inCullMode_addr, int inDrawMode_addr) {
        if (Mat44_TEMP_STATIC_GEN_0 == null)
            Mat44_TEMP_STATIC_GEN_0 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_0.internal_reset(inModelMatrix_addr, false);
        if (NativeFloatArray_TEMP_STATIC_GEN_0 == null)
            NativeFloatArray_TEMP_STATIC_GEN_0 = NativeFloatArray.native_new();
        NativeFloatArray_TEMP_STATIC_GEN_0.internal_reset(vertices_addr, false);
        if (Color_TEMP_STATIC_GEN_0 == null)
            Color_TEMP_STATIC_GEN_0 = Color.native_new();
        Color_TEMP_STATIC_GEN_0.internal_reset(inModelColor_addr, false);
        ECullMode inCullMode_addr_enum = ECullMode.CUSTOM.setValue(inCullMode_addr);
        ECullMode[] inCullMode_addr_enum_values = ECullMode.values();
        for (int i = 0; i < inCullMode_addr_enum_values.length; i++) {
            ECullMode enumVal = inCullMode_addr_enum_values[i];
            if (enumVal != ECullMode.CUSTOM && enumVal.getValue() == inCullMode_addr) {
                inCullMode_addr_enum = inCullMode_addr_enum_values[i];
                break;
            }
        }
        EDrawMode inDrawMode_addr_enum = EDrawMode.CUSTOM.setValue(inDrawMode_addr);
        EDrawMode[] inDrawMode_addr_enum_values = EDrawMode.values();
        for (int i = 0; i < inDrawMode_addr_enum_values.length; i++) {
            EDrawMode enumVal = inDrawMode_addr_enum_values[i];
            if (enumVal != EDrawMode.CUSTOM && enumVal.getValue() == inDrawMode_addr) {
                inDrawMode_addr_enum = inDrawMode_addr_enum_values[i];
                break;
            }
        }
        DrawMesh(id, Mat44_TEMP_STATIC_GEN_0, NativeFloatArray_TEMP_STATIC_GEN_0, Color_TEMP_STATIC_GEN_0, inCullMode_addr_enum, inDrawMode_addr_enum);
    }

    protected void DrawLine(Vec3 inFrom, Vec3 inTo, Color inColor) {
    }

    private void internal_DrawLine(long inFrom_addr, long inTo_addr, long inColor_addr) {
        if (Vec3_TEMP_STATIC_GEN_0 == null)
            Vec3_TEMP_STATIC_GEN_0 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_0.internal_reset(inFrom_addr, false);
        if (Vec3_TEMP_STATIC_GEN_1 == null)
            Vec3_TEMP_STATIC_GEN_1 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_1.internal_reset(inTo_addr, false);
        if (Color_TEMP_STATIC_GEN_1 == null)
            Color_TEMP_STATIC_GEN_1 = Color.native_new();
        Color_TEMP_STATIC_GEN_1.internal_reset(inColor_addr, false);
        DrawLine(Vec3_TEMP_STATIC_GEN_0, Vec3_TEMP_STATIC_GEN_1, Color_TEMP_STATIC_GEN_1);
    }

    protected void DrawTriangle(Vec3 inV1, Vec3 inV2, Vec3 inV3, Color inColor, ECastShadow inCastShadow) {
    }

    private void internal_DrawTriangle(long inV1_addr, long inV2_addr, long inV3_addr, long inColor_addr, int inCastShadow_addr) {
        if (Vec3_TEMP_STATIC_GEN_2 == null)
            Vec3_TEMP_STATIC_GEN_2 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_2.internal_reset(inV1_addr, false);
        if (Vec3_TEMP_STATIC_GEN_3 == null)
            Vec3_TEMP_STATIC_GEN_3 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_3.internal_reset(inV2_addr, false);
        if (Vec3_TEMP_STATIC_GEN_4 == null)
            Vec3_TEMP_STATIC_GEN_4 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_4.internal_reset(inV3_addr, false);
        if (Color_TEMP_STATIC_GEN_2 == null)
            Color_TEMP_STATIC_GEN_2 = Color.native_new();
        Color_TEMP_STATIC_GEN_2.internal_reset(inColor_addr, false);
        ECastShadow inCastShadow_addr_enum = ECastShadow.CUSTOM.setValue(inCastShadow_addr);
        ECastShadow[] inCastShadow_addr_enum_values = ECastShadow.values();
        for (int i = 0; i < inCastShadow_addr_enum_values.length; i++) {
            ECastShadow enumVal = inCastShadow_addr_enum_values[i];
            if (enumVal != ECastShadow.CUSTOM && enumVal.getValue() == inCastShadow_addr) {
                inCastShadow_addr_enum = inCastShadow_addr_enum_values[i];
                break;
            }
        }
        DrawTriangle(Vec3_TEMP_STATIC_GEN_2, Vec3_TEMP_STATIC_GEN_3, Vec3_TEMP_STATIC_GEN_4, Color_TEMP_STATIC_GEN_2, inCastShadow_addr_enum);
    }

    protected void DrawText3D(Vec3 inPosition, NativeObject inString, int inStringLen, Color inColor, float inHeight) {
    }

    private void internal_DrawText3D(long inPosition_addr, long inString_addr, int inStringLen, long inColor_addr, float inHeight) {
        if (Vec3_TEMP_STATIC_GEN_5 == null)
            Vec3_TEMP_STATIC_GEN_5 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_5.internal_reset(inPosition_addr, false);
        if (NativeObject_TEMP_STATIC_GEN_0 == null)
            NativeObject_TEMP_STATIC_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_STATIC_GEN_0.internal_reset(inString_addr, false);
        if (Color_TEMP_STATIC_GEN_3 == null)
            Color_TEMP_STATIC_GEN_3 = Color.native_new();
        Color_TEMP_STATIC_GEN_3.internal_reset(inColor_addr, false);
        DrawText3D(Vec3_TEMP_STATIC_GEN_5, NativeObject_TEMP_STATIC_GEN_0, inStringLen, Color_TEMP_STATIC_GEN_3, inHeight);
    }

    protected void DrawGeometryWithID(Mat44 inModelMatrix, AABox inWorldSpaceBounds, float inLODScaleSq, Color inModelColor, int inGeometryID, ECullMode inCullMode, ECastShadow inCastShadow, EDrawMode inDrawMode) {
    }

    private void internal_DrawGeometryWithID(long inModelMatrix_addr, long inWorldSpaceBounds_addr, float inLODScaleSq, long inModelColor_addr, int inGeometryID, int inCullMode_addr, int inCastShadow_addr, int inDrawMode_addr) {
        if (Mat44_TEMP_STATIC_GEN_1 == null)
            Mat44_TEMP_STATIC_GEN_1 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_1.internal_reset(inModelMatrix_addr, false);
        if (AABox_TEMP_STATIC_GEN_0 == null)
            AABox_TEMP_STATIC_GEN_0 = AABox.native_new();
        AABox_TEMP_STATIC_GEN_0.internal_reset(inWorldSpaceBounds_addr, false);
        if (Color_TEMP_STATIC_GEN_4 == null)
            Color_TEMP_STATIC_GEN_4 = Color.native_new();
        Color_TEMP_STATIC_GEN_4.internal_reset(inModelColor_addr, false);
        ECullMode inCullMode_addr_enum = ECullMode.CUSTOM.setValue(inCullMode_addr);
        ECullMode[] inCullMode_addr_enum_values = ECullMode.values();
        for (int i = 0; i < inCullMode_addr_enum_values.length; i++) {
            ECullMode enumVal = inCullMode_addr_enum_values[i];
            if (enumVal != ECullMode.CUSTOM && enumVal.getValue() == inCullMode_addr) {
                inCullMode_addr_enum = inCullMode_addr_enum_values[i];
                break;
            }
        }
        ECastShadow inCastShadow_addr_enum = ECastShadow.CUSTOM.setValue(inCastShadow_addr);
        ECastShadow[] inCastShadow_addr_enum_values = ECastShadow.values();
        for (int i = 0; i < inCastShadow_addr_enum_values.length; i++) {
            ECastShadow enumVal = inCastShadow_addr_enum_values[i];
            if (enumVal != ECastShadow.CUSTOM && enumVal.getValue() == inCastShadow_addr) {
                inCastShadow_addr_enum = inCastShadow_addr_enum_values[i];
                break;
            }
        }
        EDrawMode inDrawMode_addr_enum = EDrawMode.CUSTOM.setValue(inDrawMode_addr);
        EDrawMode[] inDrawMode_addr_enum_values = EDrawMode.values();
        for (int i = 0; i < inDrawMode_addr_enum_values.length; i++) {
            EDrawMode enumVal = inDrawMode_addr_enum_values[i];
            if (enumVal != EDrawMode.CUSTOM && enumVal.getValue() == inDrawMode_addr) {
                inDrawMode_addr_enum = inDrawMode_addr_enum_values[i];
                break;
            }
        }
        DrawGeometryWithID(Mat44_TEMP_STATIC_GEN_1, AABox_TEMP_STATIC_GEN_0, inLODScaleSq, Color_TEMP_STATIC_GEN_4, inGeometryID, inCullMode_addr_enum, inCastShadow_addr_enum, inDrawMode_addr_enum);
    }

    protected int CreateTriangleBatchID(NativeObject inTriangles, int inTriangleCount) {
        return 0;
    }

    private int internal_CreateTriangleBatchID(long inTriangles_addr, int inTriangleCount) {
        if (NativeObject_TEMP_STATIC_GEN_1 == null)
            NativeObject_TEMP_STATIC_GEN_1 = NativeObject.native_new();
        NativeObject_TEMP_STATIC_GEN_1.internal_reset(inTriangles_addr, false);
        return CreateTriangleBatchID(NativeObject_TEMP_STATIC_GEN_1, inTriangleCount);
    }

    protected int CreateTriangleBatchIDWithIndex(NativeObject inVertices, int inVertexCount, NativeObject inIndices, int inIndexCount) {
        return 0;
    }

    private int internal_CreateTriangleBatchIDWithIndex(long inVertices_addr, int inVertexCount, long inIndices_addr, int inIndexCount) {
        if (NativeObject_TEMP_STATIC_GEN_2 == null)
            NativeObject_TEMP_STATIC_GEN_2 = NativeObject.native_new();
        NativeObject_TEMP_STATIC_GEN_2.internal_reset(inVertices_addr, false);
        if (NativeObject_TEMP_STATIC_GEN_3 == null)
            NativeObject_TEMP_STATIC_GEN_3 = NativeObject.native_new();
        NativeObject_TEMP_STATIC_GEN_3.internal_reset(inIndices_addr, false);
        return CreateTriangleBatchIDWithIndex(NativeObject_TEMP_STATIC_GEN_2, inVertexCount, NativeObject_TEMP_STATIC_GEN_3, inIndexCount);
    }

    public static long internal_native_create_addr() {
        return jolt.renderer.natives.JNI_DebugRendererEm.internal_native_create_addr();
    }

    public native void internal_native_setupCallback(long this_addr);
}
