/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.constraints.natives;

import jolt.physics.constraints.*;

final public class JNI_GearConstraint {

    public static native void internal_native_SetConstraints(long this_addr, long inGear1_addr, long inGear2_addr);

    public static native float internal_native_GetTotalLambda(long this_addr);
}
