/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.constraints.natives;

import jolt.physics.constraints.*;

final public class JNI_PathConstraint {

    public static native void internal_native_SetPath(long this_addr, long inPath_addr, float inPathFraction);

    public static native long internal_native_GetPath_addr(long this_addr);

    public static native float internal_native_GetPathFraction(long this_addr);

    public static native void internal_native_SetMaxFrictionForce(long this_addr, float inFrictionForce);

    public static native float internal_native_GetMaxFrictionForce(long this_addr);

    public static native long internal_native_GetPositionMotorSettings_addr(long this_addr);

    public static native void internal_native_SetPositionMotorState(long this_addr, int inState);

    public static native int internal_native_GetPositionMotorState(long this_addr);

    public static native void internal_native_SetTargetVelocity(long this_addr, float inVelocity);

    public static native float internal_native_GetTargetVelocity(long this_addr);

    public static native void internal_native_SetTargetPathFraction(long this_addr, float inFraction);

    public static native float internal_native_GetTargetPathFraction(long this_addr);
}
