/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.constraints.natives;

import jolt.physics.constraints.*;

final public class JNI_SliderConstraint {

    public static native float internal_native_GetCurrentPosition(long this_addr);

    public static native void internal_native_SetMaxFrictionForce(long this_addr, float inFrictionForce);

    public static native float internal_native_GetMaxFrictionForce(long this_addr);

    public static native long internal_native_GetMotorSettings_addr(long this_addr);

    public static native void internal_native_SetMotorState(long this_addr, int inState);

    public static native int internal_native_GetMotorState(long this_addr);

    public static native void internal_native_SetTargetVelocity(long this_addr, float inVelocity);

    public static native float internal_native_GetTargetVelocity(long this_addr);

    public static native void internal_native_SetTargetPosition(long this_addr, float inPosition);

    public static native float internal_native_GetTargetPosition(long this_addr);

    public static native void internal_native_SetLimits(long this_addr, float inLimitsMin, float inLimitsMax);

    public static native float internal_native_GetLimitsMin(long this_addr);

    public static native float internal_native_GetLimitsMax(long this_addr);

    public static native boolean internal_native_HasLimits(long this_addr);

    public static native long internal_native_GetLimitsSpringSettings_addr(long this_addr);

    public static native void internal_native_SetLimitsSpringSettings(long this_addr, long inLimitsSpringSettings_addr);

    public static native long internal_native_GetTotalLambdaPosition_addr(long this_addr);

    public static native float internal_native_GetTotalLambdaPositionLimits(long this_addr);

    public static native long internal_native_GetTotalLambdaRotation_addr(long this_addr);

    public static native float internal_native_GetTotalLambdaMotor(long this_addr);
}
