/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.constraints.natives;

import jolt.physics.constraints.*;

final public class JNI_DistanceConstraintSettings {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_get_mSpace(long this_addr);

    public static native void internal_native_set_mSpace(long this_addr, int mSpace);

    public static native long internal_native_get_mPoint1_addr(long this_addr);

    public static native void internal_native_set_mPoint1(long this_addr, long mPoint1_addr);

    public static native long internal_native_get_mPoint2_addr(long this_addr);

    public static native void internal_native_set_mPoint2(long this_addr, long mPoint2_addr);

    public static native float internal_native_get_mMinDistance(long this_addr);

    public static native void internal_native_set_mMinDistance(long this_addr, float mMinDistance);

    public static native float internal_native_get_mMaxDistance(long this_addr);

    public static native void internal_native_set_mMaxDistance(long this_addr, float mMaxDistance);

    public static native long internal_native_get_mLimitsSpringSettings_addr(long this_addr);

    public static native void internal_native_set_mLimitsSpringSettings(long this_addr, long mLimitsSpringSettings_addr);
}
