/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.constraints.natives;

import jolt.physics.constraints.*;

final public class JNI_PulleyConstraint {

    public static native void internal_native_SetLength(long this_addr, float inMinLength, float inMaxLength);

    public static native float internal_native_GetMinLength(long this_addr);

    public static native float internal_native_GetMaxLength(long this_addr);

    public static native float internal_native_GetCurrentLength(long this_addr);
}
