/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.body;

import com.github.xpenatan.jParser.api.NativeObject;

public class BodyActivationListener extends NativeObject {

    static private BodyID BodyID_TEMP_STATIC_GEN_0;

    static private BodyID BodyID_TEMP_STATIC_GEN_1;

    static public final BodyActivationListener NULL = BodyActivationListener.native_new();

    @Deprecated()
    protected BodyActivationListener(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static BodyActivationListener native_new() {
        return new BodyActivationListener((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.body.natives.JNI_BodyActivationListener.internal_native_deleteNative(this_addr);
    }

    public BodyActivationListener() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        internal_native_setupCallback(native_address);
    }

    protected void OnBodyActivated(BodyID inBodyID, long inBodyUserData) {
    }

    private void internal_OnBodyActivated(long inBodyID_addr, long inBodyUserData) {
        if (BodyID_TEMP_STATIC_GEN_0 == null)
            BodyID_TEMP_STATIC_GEN_0 = BodyID.native_new();
        BodyID_TEMP_STATIC_GEN_0.internal_reset(inBodyID_addr, false);
        OnBodyActivated(BodyID_TEMP_STATIC_GEN_0, inBodyUserData);
    }

    protected void OnBodyDeactivated(BodyID inBodyID, long inBodyUserData) {
    }

    private void internal_OnBodyDeactivated(long inBodyID_addr, long inBodyUserData) {
        if (BodyID_TEMP_STATIC_GEN_1 == null)
            BodyID_TEMP_STATIC_GEN_1 = BodyID.native_new();
        BodyID_TEMP_STATIC_GEN_1.internal_reset(inBodyID_addr, false);
        OnBodyDeactivated(BodyID_TEMP_STATIC_GEN_1, inBodyUserData);
    }

    public static long internal_native_create_addr() {
        return jolt.physics.body.natives.JNI_BodyActivationListener.internal_native_create_addr();
    }

    public native void internal_native_setupCallback(long this_addr);
}
