/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum EBodyType implements NativeEnum<EBodyType> {

    CUSTOM(0), RigidBody(EBodyType_RigidBody_NATIVE()), SoftBody(EBodyType_SoftBody_NATIVE());

    private int value;

    private EBodyType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public EBodyType setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public EBodyType getCustom() {
        return CUSTOM;
    }

    private static int EBodyType_RigidBody_NATIVE() {
        try {
            return (int) FFMHandles.EBodyType_RigidBody_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EBodyType_SoftBody_NATIVE() {
        try {
            return (int) FFMHandles.EBodyType_SoftBody_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle EBodyType_RigidBody_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_ebodytype_ebodytype_rigidbody_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EBodyType_SoftBody_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_ebodytype_ebodytype_softbody_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
