/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ECastShadow implements NativeEnum<ECastShadow> {

    CUSTOM(0), ECastShadow_On(ECastShadow_On_NATIVE()), ECastShadow_Off(ECastShadow_Off_NATIVE());

    private int value;

    private ECastShadow(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ECastShadow setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ECastShadow getCustom() {
        return CUSTOM;
    }

    private static int ECastShadow_On_NATIVE() {
        try {
            return (int) FFMHandles.ECastShadow_On_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ECastShadow_Off_NATIVE() {
        try {
            return (int) FFMHandles.ECastShadow_Off_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle ECastShadow_On_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_ecastshadow_ecastshadow_on_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ECastShadow_Off_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_ecastshadow_ecastshadow_off_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
