/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum EDrawMode implements NativeEnum<EDrawMode> {

    CUSTOM(0), EDrawMode_Solid(EDrawMode_Solid_NATIVE()), EDrawMode_Wireframe(EDrawMode_Wireframe_NATIVE());

    private int value;

    private EDrawMode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public EDrawMode setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public EDrawMode getCustom() {
        return CUSTOM;
    }

    private static int EDrawMode_Solid_NATIVE() {
        try {
            return (int) FFMHandles.EDrawMode_Solid_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int EDrawMode_Wireframe_NATIVE() {
        try {
            return (int) FFMHandles.EDrawMode_Wireframe_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle EDrawMode_Solid_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_edrawmode_edrawmode_solid_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle EDrawMode_Wireframe_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_edrawmode_edrawmode_wireframe_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
