/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ESpringMode implements NativeEnum<ESpringMode> {

    CUSTOM(0), FrequencyAndDamping(ESpringMode_FrequencyAndDamping_NATIVE()), StiffnessAndDamping(ESpringMode_StiffnessAndDamping_NATIVE());

    private int value;

    private ESpringMode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ESpringMode setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ESpringMode getCustom() {
        return CUSTOM;
    }

    private static int ESpringMode_FrequencyAndDamping_NATIVE() {
        try {
            return (int) FFMHandles.ESpringMode_FrequencyAndDamping_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ESpringMode_StiffnessAndDamping_NATIVE() {
        try {
            return (int) FFMHandles.ESpringMode_StiffnessAndDamping_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle ESpringMode_FrequencyAndDamping_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_espringmode_espringmode_frequencyanddamping_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ESpringMode_StiffnessAndDamping_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_espringmode_espringmode_stiffnessanddamping_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
