/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum SoftBodyValidateResult implements NativeEnum<SoftBodyValidateResult> {

    CUSTOM(0), AcceptContact(SoftBodyValidateResult_AcceptContact_NATIVE()), RejectContact(SoftBodyValidateResult_RejectContact_NATIVE());

    private int value;

    private SoftBodyValidateResult(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public SoftBodyValidateResult setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public SoftBodyValidateResult getCustom() {
        return CUSTOM;
    }

    private static int SoftBodyValidateResult_AcceptContact_NATIVE() {
        try {
            return (int) FFMHandles.SoftBodyValidateResult_AcceptContact_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int SoftBodyValidateResult_RejectContact_NATIVE() {
        try {
            return (int) FFMHandles.SoftBodyValidateResult_RejectContact_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle SoftBodyValidateResult_AcceptContact_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_softbodyvalidateresult_softbodyvalidateresult_acceptcontact_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle SoftBodyValidateResult_RejectContact_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_enums_softbodyvalidateresult_softbodyvalidateresult_rejectcontact_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
