/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision;

import com.github.xpenatan.jParser.api.NativeObject;

public class SimShapeFilter extends NativeObject {

    static public final SimShapeFilter NULL = SimShapeFilter.native_new();

    public SimShapeFilter() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected SimShapeFilter(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static SimShapeFilter native_new() {
        return new SimShapeFilter((byte) 0, (char) 0);
    }
}
