/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class VehicleController extends NativeObject {

    private VehicleConstraint VehicleConstraint_TEMP_GEN_0;

    static public final VehicleController NULL = VehicleController.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VehicleController(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static VehicleController native_new() {
        return new VehicleController((byte) 0, (char) 0);
    }

    public VehicleConstraint GetConstraint() {
        long addr = internal_native_GetConstraint_addr(native_address);
        if (addr == 0)
            return VehicleConstraint.NULL;
        if (VehicleConstraint_TEMP_GEN_0 == null)
            VehicleConstraint_TEMP_GEN_0 = VehicleConstraint.native_new();
        VehicleConstraint_TEMP_GEN_0.internal_reset(addr, false);
        return VehicleConstraint_TEMP_GEN_0;
    }

    public static long internal_native_GetConstraint_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetConstraint_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_GetConstraint_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_vehicle_vehiclecontroller_getconstraint_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
