/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum EMotorState implements NativeEnum<EMotorState> {

    CUSTOM(0), Off(EMotorState_Off_NATIVE()), Velocity(EMotorState_Velocity_NATIVE()), Position(EMotorState_Position_NATIVE());

    private int value;

    private EMotorState(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public EMotorState setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public EMotorState getCustom() {
        return CUSTOM;
    }

    private static int EMotorState_Off_NATIVE() {
        return jolt.enums.natives.JNI_EMotorState.EMotorState_Off_NATIVE();
    }

    private static int EMotorState_Velocity_NATIVE() {
        return jolt.enums.natives.JNI_EMotorState.EMotorState_Velocity_NATIVE();
    }

    private static int EMotorState_Position_NATIVE() {
        return jolt.enums.natives.JNI_EMotorState.EMotorState_Position_NATIVE();
    }
}
