/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum SixDOFConstraintSettings_EAxis implements NativeEnum<SixDOFConstraintSettings_EAxis> {

    CUSTOM(0),
    TranslationX(SixDOFConstraintSettings_EAxis_TranslationX_NATIVE()),
    TranslationY(SixDOFConstraintSettings_EAxis_TranslationY_NATIVE()),
    TranslationZ(SixDOFConstraintSettings_EAxis_TranslationZ_NATIVE()),
    RotationX(SixDOFConstraintSettings_EAxis_RotationX_NATIVE()),
    RotationY(SixDOFConstraintSettings_EAxis_RotationY_NATIVE()),
    RotationZ(SixDOFConstraintSettings_EAxis_RotationZ_NATIVE());

    private int value;

    private SixDOFConstraintSettings_EAxis(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public SixDOFConstraintSettings_EAxis setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public SixDOFConstraintSettings_EAxis getCustom() {
        return CUSTOM;
    }

    private static int SixDOFConstraintSettings_EAxis_TranslationX_NATIVE() {
        return jolt.enums.natives.JNI_SixDOFConstraintSettings_EAxis.SixDOFConstraintSettings_EAxis_TranslationX_NATIVE();
    }

    private static int SixDOFConstraintSettings_EAxis_TranslationY_NATIVE() {
        return jolt.enums.natives.JNI_SixDOFConstraintSettings_EAxis.SixDOFConstraintSettings_EAxis_TranslationY_NATIVE();
    }

    private static int SixDOFConstraintSettings_EAxis_TranslationZ_NATIVE() {
        return jolt.enums.natives.JNI_SixDOFConstraintSettings_EAxis.SixDOFConstraintSettings_EAxis_TranslationZ_NATIVE();
    }

    private static int SixDOFConstraintSettings_EAxis_RotationX_NATIVE() {
        return jolt.enums.natives.JNI_SixDOFConstraintSettings_EAxis.SixDOFConstraintSettings_EAxis_RotationX_NATIVE();
    }

    private static int SixDOFConstraintSettings_EAxis_RotationY_NATIVE() {
        return jolt.enums.natives.JNI_SixDOFConstraintSettings_EAxis.SixDOFConstraintSettings_EAxis_RotationY_NATIVE();
    }

    private static int SixDOFConstraintSettings_EAxis_RotationZ_NATIVE() {
        return jolt.enums.natives.JNI_SixDOFConstraintSettings_EAxis.SixDOFConstraintSettings_EAxis_RotationZ_NATIVE();
    }
}
