/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ValidateResult implements NativeEnum<ValidateResult> {

    CUSTOM(0), AcceptAllContactsForThisBodyPair(ValidateResult_AcceptAllContactsForThisBodyPair_NATIVE()), AcceptContact(ValidateResult_AcceptContact_NATIVE()), RejectContact(ValidateResult_RejectContact_NATIVE()), RejectAllContactsForThisBodyPair(ValidateResult_RejectAllContactsForThisBodyPair_NATIVE());

    private int value;

    private ValidateResult(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ValidateResult setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ValidateResult getCustom() {
        return CUSTOM;
    }

    private static int ValidateResult_AcceptAllContactsForThisBodyPair_NATIVE() {
        return jolt.enums.natives.JNI_ValidateResult.ValidateResult_AcceptAllContactsForThisBodyPair_NATIVE();
    }

    private static int ValidateResult_AcceptContact_NATIVE() {
        return jolt.enums.natives.JNI_ValidateResult.ValidateResult_AcceptContact_NATIVE();
    }

    private static int ValidateResult_RejectContact_NATIVE() {
        return jolt.enums.natives.JNI_ValidateResult.ValidateResult_RejectContact_NATIVE();
    }

    private static int ValidateResult_RejectAllContactsForThisBodyPair_NATIVE() {
        return jolt.enums.natives.JNI_ValidateResult.ValidateResult_RejectAllContactsForThisBodyPair_NATIVE();
    }
}
