/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.natives;

import jolt.physics.collision.*;

final public class JNI_ObjectLayerPairFilterMask {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_sGetObjectLayer(int inGroup, int inMask);

    public static native int internal_native_sGetGroup(int inObjectLayer);

    public static native int internal_native_sGetMask(int inObjectLayer);
}
