/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.natives;

import jolt.physics.collision.*;

final public class JNI_ObjectLayerPairFilterTable {

    public static native long internal_native_create_int_addr(int inNumObjectLayers);

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_GetNumObjectLayers(long this_addr);

    public static native void internal_native_DisableCollision(long this_addr, int inLayer1, int inLayer2);

    public static native void internal_native_EnableCollision(long this_addr, int inLayer1, int inLayer2);
}
