/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.natives;

import jolt.physics.collision.*;

final public class JNI_AABoxCast {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_get_mBox_addr(long this_addr);

    public static native void internal_native_set_mBox(long this_addr, long mBox_addr);

    public static native long internal_native_get_mDirection_addr(long this_addr);

    public static native void internal_native_set_mDirection(long this_addr, long mDirection_addr);
}
