/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.natives;

import jolt.physics.collision.*;

final public class JNI_RayCastSettings {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_SetBackFaceMode(long this_addr, int inBackFaceMode);

    public static native int internal_native_get_mBackFaceModeTriangles(long this_addr);

    public static native void internal_native_set_mBackFaceModeTriangles(long this_addr, int mBackFaceModeTriangles);

    public static native int internal_native_get_mBackFaceModeConvex(long this_addr);

    public static native void internal_native_set_mBackFaceModeConvex(long this_addr, int mBackFaceModeConvex);

    public static native boolean internal_native_get_mTreatConvexAsSolid(long this_addr);

    public static native void internal_native_set_mTreatConvexAsSolid(long this_addr, boolean mTreatConvexAsSolid);
}
