/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.natives;

import jolt.physics.*;

final public class JNI_SpecifiedObjectLayerFilter {

    public static native long internal_native_create_int_addr(int inObjectLayer);

    public static native void internal_native_deleteNative(long this_addr);
}
