/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.natives;

import jolt.physics.*;

final public class JNI_StateRecorderImpl {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_Clear(long this_addr);

    public static native void internal_native_Rewind(long this_addr);

    public static native boolean internal_native_IsEqual(long this_addr, long inReference_addr);
}
