/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.character.natives;

import jolt.physics.character.*;

final public class JNI_ExtendedUpdateSettings {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_get_mStickToFloorStepDown_addr(long this_addr);

    public static native void internal_native_set_mStickToFloorStepDown(long this_addr, long mStickToFloorStepDown_addr);

    public static native long internal_native_get_mWalkStairsStepUp_addr(long this_addr);

    public static native void internal_native_set_mWalkStairsStepUp(long this_addr, long mWalkStairsStepUp_addr);

    public static native float internal_native_get_mWalkStairsMinStepForward(long this_addr);

    public static native void internal_native_set_mWalkStairsMinStepForward(long this_addr, float mWalkStairsMinStepForward);

    public static native float internal_native_get_mWalkStairsStepForwardTest(long this_addr);

    public static native void internal_native_set_mWalkStairsStepForwardTest(long this_addr, float mWalkStairsStepForwardTest);

    public static native float internal_native_get_mWalkStairsCosAngleForwardContact(long this_addr);

    public static native void internal_native_set_mWalkStairsCosAngleForwardContact(long this_addr, float mWalkStairsCosAngleForwardContact);

    public static native long internal_native_get_mWalkStairsStepDownExtra_addr(long this_addr);

    public static native void internal_native_set_mWalkStairsStepDownExtra(long this_addr, long mWalkStairsStepDownExtra_addr);
}
