/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.constraints.natives;

import jolt.physics.constraints.*;

final public class JNI_SwingTwistConstraintSettings {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_get_mSpace(long this_addr);

    public static native void internal_native_set_mSpace(long this_addr, int mSpace);

    public static native long internal_native_get_mPosition1_addr(long this_addr);

    public static native void internal_native_set_mPosition1(long this_addr, long mPosition1_addr);

    public static native long internal_native_get_mTwistAxis1_addr(long this_addr);

    public static native void internal_native_set_mTwistAxis1(long this_addr, long mTwistAxis1_addr);

    public static native long internal_native_get_mPlaneAxis1_addr(long this_addr);

    public static native void internal_native_set_mPlaneAxis1(long this_addr, long mPlaneAxis1_addr);

    public static native long internal_native_get_mPosition2_addr(long this_addr);

    public static native void internal_native_set_mPosition2(long this_addr, long mPosition2_addr);

    public static native long internal_native_get_mTwistAxis2_addr(long this_addr);

    public static native void internal_native_set_mTwistAxis2(long this_addr, long mTwistAxis2_addr);

    public static native long internal_native_get_mPlaneAxis2_addr(long this_addr);

    public static native void internal_native_set_mPlaneAxis2(long this_addr, long mPlaneAxis2_addr);

    public static native int internal_native_get_mSwingType(long this_addr);

    public static native void internal_native_set_mSwingType(long this_addr, int mSwingType);

    public static native float internal_native_get_mNormalHalfConeAngle(long this_addr);

    public static native void internal_native_set_mNormalHalfConeAngle(long this_addr, float mNormalHalfConeAngle);

    public static native float internal_native_get_mPlaneHalfConeAngle(long this_addr);

    public static native void internal_native_set_mPlaneHalfConeAngle(long this_addr, float mPlaneHalfConeAngle);

    public static native float internal_native_get_mTwistMinAngle(long this_addr);

    public static native void internal_native_set_mTwistMinAngle(long this_addr, float mTwistMinAngle);

    public static native float internal_native_get_mTwistMaxAngle(long this_addr);

    public static native void internal_native_set_mTwistMaxAngle(long this_addr, float mTwistMaxAngle);

    public static native float internal_native_get_mMaxFrictionTorque(long this_addr);

    public static native void internal_native_set_mMaxFrictionTorque(long this_addr, float mMaxFrictionTorque);

    public static native long internal_native_get_mSwingMotorSettings_addr(long this_addr);

    public static native void internal_native_set_mSwingMotorSettings(long this_addr, long mSwingMotorSettings_addr);

    public static native long internal_native_get_mTwistMotorSettings_addr(long this_addr);

    public static native void internal_native_set_mTwistMotorSettings(long this_addr, long mTwistMotorSettings_addr);
}
