/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.constraints.natives;

import jolt.physics.constraints.*;

final public class JNI_TwoBodyConstraint {

    public static native long internal_native_GetBody1_addr(long this_addr);

    public static native long internal_native_GetBody2_addr(long this_addr);

    public static native long internal_native_GetConstraintToBody1Matrix_addr(long this_addr);

    public static native long internal_native_GetConstraintToBody2Matrix_addr(long this_addr);
}
