/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.constraints.natives;

import jolt.physics.constraints.*;

final public class JNI_RackAndPinionConstraintSettings {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_SetRatio(long this_addr, int inNumTeethRack, float inRackLength, int inNumTeethPinion);

    public static native int internal_native_get_mSpace(long this_addr);

    public static native void internal_native_set_mSpace(long this_addr, int mSpace);

    public static native long internal_native_get_mHingeAxis_addr(long this_addr);

    public static native void internal_native_set_mHingeAxis(long this_addr, long mHingeAxis_addr);

    public static native long internal_native_get_mSliderAxis_addr(long this_addr);

    public static native void internal_native_set_mSliderAxis(long this_addr, long mSliderAxis_addr);

    public static native float internal_native_get_mRatio(long this_addr);

    public static native void internal_native_set_mRatio(long this_addr, float mRatio);
}
