/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.constraints.natives;

import jolt.physics.constraints.*;

final public class JNI_FixedConstraintSettings {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_get_mSpace(long this_addr);

    public static native void internal_native_set_mSpace(long this_addr, int mSpace);

    public static native boolean internal_native_get_mAutoDetectPoint(long this_addr);

    public static native void internal_native_set_mAutoDetectPoint(long this_addr, boolean mAutoDetectPoint);

    public static native long internal_native_get_mPoint1_addr(long this_addr);

    public static native void internal_native_set_mPoint1(long this_addr, long mPoint1_addr);

    public static native long internal_native_get_mAxisX1_addr(long this_addr);

    public static native void internal_native_set_mAxisX1(long this_addr, long mAxisX1_addr);

    public static native long internal_native_get_mAxisY1_addr(long this_addr);

    public static native void internal_native_set_mAxisY1(long this_addr, long mAxisY1_addr);

    public static native long internal_native_get_mPoint2_addr(long this_addr);

    public static native void internal_native_set_mPoint2(long this_addr, long mPoint2_addr);

    public static native long internal_native_get_mAxisX2_addr(long this_addr);

    public static native void internal_native_set_mAxisX2(long this_addr, long mAxisX2_addr);

    public static native long internal_native_get_mAxisY2_addr(long this_addr);

    public static native void internal_native_set_mAxisY2(long this_addr, long mAxisY2_addr);
}
