/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.character;

import com.github.xpenatan.jParser.api.NativeObject;

public class CharacterVsCharacterCollision extends NativeObject {

    static public final CharacterVsCharacterCollision NULL = CharacterVsCharacterCollision.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CharacterVsCharacterCollision(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static CharacterVsCharacterCollision native_new() {
        return new CharacterVsCharacterCollision((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.character.natives.JNI_CharacterVsCharacterCollision.internal_native_deleteNative(this_addr);
    }
}
