/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.physics.PhysicsSystem;

public class Jolt extends NativeObject {

    static public final Jolt NULL = Jolt.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected Jolt(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static Jolt native_new() {
        return new Jolt((byte) 0, (char) 0);
    }

    public static void Init() {
        internal_native_Init();
    }

    public static void internal_native_Init() {
        jolt.natives.JNI_Jolt.internal_native_Init();
    }

    public static void RegisterTypes() {
        internal_native_RegisterTypes();
    }

    public static void internal_native_RegisterTypes() {
        jolt.natives.JNI_Jolt.internal_native_RegisterTypes();
    }

    public static void UnregisterTypes() {
        internal_native_UnregisterTypes();
    }

    public static void internal_native_UnregisterTypes() {
        jolt.natives.JNI_Jolt.internal_native_UnregisterTypes();
    }

    public static void ClearWorld(PhysicsSystem physicsSystem) {
        internal_native_ClearWorld(physicsSystem.native_address);
    }

    public static void internal_native_ClearWorld(long physicsSystem_addr) {
        jolt.natives.JNI_Jolt.internal_native_ClearWorld(physicsSystem_addr);
    }
}
