/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.math.Vec3;
import jolt.physics.collision.shape.SubShapeID;
import jolt.physics.body.BodyID;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class CollideShapeResult extends NativeObject {

    private Vec3 Vec3_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_1;

    private Vec3 Vec3_TEMP_GEN_2;

    private SubShapeID SubShapeID_TEMP_GEN_0;

    private SubShapeID SubShapeID_TEMP_GEN_1;

    private BodyID BodyID_TEMP_GEN_0;

    private CollideShapeResultFace CollideShapeResultFace_TEMP_GEN_0;

    private CollideShapeResultFace CollideShapeResultFace_TEMP_GEN_1;

    static public final CollideShapeResult NULL = CollideShapeResult.native_new();

    public CollideShapeResult() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CollideShapeResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static CollideShapeResult native_new() {
        return new CollideShapeResult((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 get_mContactPointOn1() {
        long addr = internal_native_get_mContactPointOn1_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = Vec3.native_new();
        Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return Vec3_TEMP_GEN_0;
    }

    public static long internal_native_get_mContactPointOn1_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mContactPointOn1_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mContactPointOn1(Vec3 mContactPointOn1) {
        internal_native_set_mContactPointOn1(native_address, mContactPointOn1.native_address);
    }

    public static void internal_native_set_mContactPointOn1(long this_addr, long mContactPointOn1_addr) {
        try {
            FFMHandles.internal_native_set_mContactPointOn1__JJ.invokeExact(this_addr, mContactPointOn1_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 get_mContactPointOn2() {
        long addr = internal_native_get_mContactPointOn2_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_1 == null)
            Vec3_TEMP_GEN_1 = Vec3.native_new();
        Vec3_TEMP_GEN_1.internal_reset(addr, false);
        return Vec3_TEMP_GEN_1;
    }

    public static long internal_native_get_mContactPointOn2_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mContactPointOn2_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mContactPointOn2(Vec3 mContactPointOn2) {
        internal_native_set_mContactPointOn2(native_address, mContactPointOn2.native_address);
    }

    public static void internal_native_set_mContactPointOn2(long this_addr, long mContactPointOn2_addr) {
        try {
            FFMHandles.internal_native_set_mContactPointOn2__JJ.invokeExact(this_addr, mContactPointOn2_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 get_mPenetrationAxis() {
        long addr = internal_native_get_mPenetrationAxis_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_2 == null)
            Vec3_TEMP_GEN_2 = Vec3.native_new();
        Vec3_TEMP_GEN_2.internal_reset(addr, false);
        return Vec3_TEMP_GEN_2;
    }

    public static long internal_native_get_mPenetrationAxis_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mPenetrationAxis_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mPenetrationAxis(Vec3 mPenetrationAxis) {
        internal_native_set_mPenetrationAxis(native_address, mPenetrationAxis.native_address);
    }

    public static void internal_native_set_mPenetrationAxis(long this_addr, long mPenetrationAxis_addr) {
        try {
            FFMHandles.internal_native_set_mPenetrationAxis__JJ.invokeExact(this_addr, mPenetrationAxis_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mPenetrationDepth() {
        return internal_native_get_mPenetrationDepth(native_address);
    }

    public static float internal_native_get_mPenetrationDepth(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mPenetrationDepth__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mPenetrationDepth(float mPenetrationDepth) {
        internal_native_set_mPenetrationDepth(native_address, mPenetrationDepth);
    }

    public static void internal_native_set_mPenetrationDepth(long this_addr, float mPenetrationDepth) {
        try {
            FFMHandles.internal_native_set_mPenetrationDepth__JF.invokeExact(this_addr, mPenetrationDepth);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public SubShapeID get_mSubShapeID1() {
        long addr = internal_native_get_mSubShapeID1_addr(native_address);
        if (addr == 0)
            return SubShapeID.NULL;
        if (SubShapeID_TEMP_GEN_0 == null)
            SubShapeID_TEMP_GEN_0 = SubShapeID.native_new();
        SubShapeID_TEMP_GEN_0.internal_reset(addr, false);
        return SubShapeID_TEMP_GEN_0;
    }

    public static long internal_native_get_mSubShapeID1_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mSubShapeID1_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mSubShapeID1(SubShapeID mSubShapeID1) {
        internal_native_set_mSubShapeID1(native_address, mSubShapeID1.native_address);
    }

    public static void internal_native_set_mSubShapeID1(long this_addr, long mSubShapeID1_addr) {
        try {
            FFMHandles.internal_native_set_mSubShapeID1__JJ.invokeExact(this_addr, mSubShapeID1_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public SubShapeID get_mSubShapeID2() {
        long addr = internal_native_get_mSubShapeID2_addr(native_address);
        if (addr == 0)
            return SubShapeID.NULL;
        if (SubShapeID_TEMP_GEN_1 == null)
            SubShapeID_TEMP_GEN_1 = SubShapeID.native_new();
        SubShapeID_TEMP_GEN_1.internal_reset(addr, false);
        return SubShapeID_TEMP_GEN_1;
    }

    public static long internal_native_get_mSubShapeID2_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mSubShapeID2_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mSubShapeID2(SubShapeID mSubShapeID2) {
        internal_native_set_mSubShapeID2(native_address, mSubShapeID2.native_address);
    }

    public static void internal_native_set_mSubShapeID2(long this_addr, long mSubShapeID2_addr) {
        try {
            FFMHandles.internal_native_set_mSubShapeID2__JJ.invokeExact(this_addr, mSubShapeID2_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public BodyID get_mBodyID2() {
        long addr = internal_native_get_mBodyID2_addr(native_address);
        if (addr == 0)
            return BodyID.NULL;
        if (BodyID_TEMP_GEN_0 == null)
            BodyID_TEMP_GEN_0 = BodyID.native_new();
        BodyID_TEMP_GEN_0.internal_reset(addr, false);
        return BodyID_TEMP_GEN_0;
    }

    public static long internal_native_get_mBodyID2_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mBodyID2_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mBodyID2(BodyID mBodyID2) {
        internal_native_set_mBodyID2(native_address, mBodyID2.native_address);
    }

    public static void internal_native_set_mBodyID2(long this_addr, long mBodyID2_addr) {
        try {
            FFMHandles.internal_native_set_mBodyID2__JJ.invokeExact(this_addr, mBodyID2_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public CollideShapeResultFace get_mShape1Face() {
        long addr = internal_native_get_mShape1Face_addr(native_address);
        if (addr == 0)
            return CollideShapeResultFace.NULL;
        if (CollideShapeResultFace_TEMP_GEN_0 == null)
            CollideShapeResultFace_TEMP_GEN_0 = CollideShapeResultFace.native_new();
        CollideShapeResultFace_TEMP_GEN_0.internal_reset(addr, false);
        return CollideShapeResultFace_TEMP_GEN_0;
    }

    public static long internal_native_get_mShape1Face_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mShape1Face_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mShape1Face(CollideShapeResultFace mShape1Face) {
        internal_native_set_mShape1Face(native_address, mShape1Face.native_address);
    }

    public static void internal_native_set_mShape1Face(long this_addr, long mShape1Face_addr) {
        try {
            FFMHandles.internal_native_set_mShape1Face__JJ.invokeExact(this_addr, mShape1Face_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public CollideShapeResultFace get_mShape2Face() {
        long addr = internal_native_get_mShape2Face_addr(native_address);
        if (addr == 0)
            return CollideShapeResultFace.NULL;
        if (CollideShapeResultFace_TEMP_GEN_1 == null)
            CollideShapeResultFace_TEMP_GEN_1 = CollideShapeResultFace.native_new();
        CollideShapeResultFace_TEMP_GEN_1.internal_reset(addr, false);
        return CollideShapeResultFace_TEMP_GEN_1;
    }

    public static long internal_native_get_mShape2Face_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mShape2Face_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mShape2Face(CollideShapeResultFace mShape2Face) {
        internal_native_set_mShape2Face(native_address, mShape2Face.native_address);
    }

    public static void internal_native_set_mShape2Face(long this_addr, long mShape2Face_addr) {
        try {
            FFMHandles.internal_native_set_mShape2Face__JJ.invokeExact(this_addr, mShape2Face_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_collideshaperesult_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mContactPointOn1_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_get_mcontactpointon1_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mContactPointOn1__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_set_mcontactpointon1", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mContactPointOn2_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_get_mcontactpointon2_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mContactPointOn2__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_set_mcontactpointon2", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mPenetrationAxis_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_get_mpenetrationaxis_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mPenetrationAxis__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_set_mpenetrationaxis", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mPenetrationDepth__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_get_mpenetrationdepth", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mPenetrationDepth__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_set_mpenetrationdepth", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_mSubShapeID1_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_get_msubshapeid1_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mSubShapeID1__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_set_msubshapeid1", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mSubShapeID2_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_get_msubshapeid2_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mSubShapeID2__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_set_msubshapeid2", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mBodyID2_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_get_mbodyid2_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mBodyID2__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_set_mbodyid2", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mShape1Face_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_get_mshape1face_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mShape1Face__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_set_mshape1face", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mShape2Face_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_get_mshape2face_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mShape2Face__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("jolt_physics_collision_collideshaperesult_set_mshape2face", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
