/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape;

public class CompoundShape extends Shape {

    static public final CompoundShape NULL = CompoundShape.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CompoundShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static CompoundShape native_new() {
        return new CompoundShape((byte) 0, (char) 0);
    }

    public int GetNumSubShapes() {
        return 0;
    }

    public CompoundShapeSubShape GetSubShape(int inIdx) {
        return null;
    }
}
