/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.ragdoll.natives;

import jolt.physics.ragdoll.*;

final public class JNI_Ragdoll {

    public static native long internal_native_create_PhysicsSystem_addr(long inSystem_addr);

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_AddToPhysicsSystem(long this_addr, int inActivationMode, boolean inLockBodies);

    public static native void internal_native_AddToPhysicsSystem(long this_addr, int inActivationMode);

    public static native void internal_native_RemoveFromPhysicsSystem(long this_addr, boolean inLockBodies);

    public static native void internal_native_RemoveFromPhysicsSystem(long this_addr);

    public static native void internal_native_Activate(long this_addr, boolean inLockBodies);

    public static native void internal_native_Activate(long this_addr);

    public static native boolean internal_native_IsActive(long this_addr, boolean inLockBodies);

    public static native boolean internal_native_IsActive(long this_addr);

    public static native void internal_native_SetGroupID(long this_addr, int inGroupID, boolean inLockBodies);

    public static native void internal_native_SetGroupID(long this_addr, int inGroupID);

    public static native void internal_native_SetPose(long this_addr, long inPose_addr, boolean inLockBodies);

    public static native void internal_native_SetPose(long this_addr, long inPose_addr);

    public static native void internal_native_GetPose(long this_addr, long outPose_addr, boolean inLockBodies);

    public static native void internal_native_GetPose(long this_addr, long outPose_addr);

    public static native void internal_native_ResetWarmStart(long this_addr);

    public static native void internal_native_DriveToPoseUsingKinematics(long this_addr, long inPose_addr, float inDeltaTime, boolean inLockBodies);

    public static native void internal_native_DriveToPoseUsingKinematics(long this_addr, long inPose_addr, float inDeltaTime);

    public static native void internal_native_DriveToPoseUsingMotors__0(long this_addr, long inPose_addr);

    public static native void internal_native_DriveToPoseUsingMotors__1(long this_addr, long inPrevPose_addr, long inPose_addr, float inDeltaTime);

    public static native void internal_native_SetLinearAndAngularVelocity(long this_addr, long inLinearVelocity_addr, long inAngularVelocity_addr, boolean inLockBodies);

    public static native void internal_native_SetLinearAndAngularVelocity(long this_addr, long inLinearVelocity_addr, long inAngularVelocity_addr);

    public static native void internal_native_SetLinearVelocity(long this_addr, long inLinearVelocity_addr, boolean inLockBodies);

    public static native void internal_native_SetLinearVelocity(long this_addr, long inLinearVelocity_addr);

    public static native void internal_native_AddLinearVelocity(long this_addr, long inLinearVelocity_addr, boolean inLockBodies);

    public static native void internal_native_AddLinearVelocity(long this_addr, long inLinearVelocity_addr);

    public static native void internal_native_AddImpulse(long this_addr, long inImpulse_addr, boolean inLockBodies);

    public static native void internal_native_AddImpulse(long this_addr, long inImpulse_addr);

    public static native void internal_native_GetRootTransform(long this_addr, long outPosition_addr, long outRotation_addr, boolean inLockBodies);

    public static native void internal_native_GetRootTransform(long this_addr, long outPosition_addr, long outRotation_addr);

    public static native int internal_native_GetBodyCount(long this_addr);

    public static native long internal_native_GetBodyID_addr(long this_addr, int inBodyIndex);

    public static native long internal_native_GetBodyIDs_addr(long this_addr);

    public static native int internal_native_GetConstraintCount(long this_addr);

    public static native long internal_native_GetWorldSpaceBounds_addr(long this_addr, boolean inLockBodies);

    public static native long internal_native_GetWorldSpaceBounds_addr(long this_addr);

    public static native long internal_native_GetConstraint_addr(long this_addr, int inConstraintIndex);

    public static native long internal_native_GetRagdollSettings_addr(long this_addr);
}
