/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.softbody;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.physics.collision.TransformedShape;
import jolt.physics.body.BodyID;

public class CollideShapeBodyCollector extends NativeObject {

    private TransformedShape TransformedShape_TEMP_GEN_0;

    static private BodyID BodyID_TEMP_STATIC_GEN_0;

    static public final CollideShapeBodyCollector NULL = CollideShapeBodyCollector.native_new();

    @Deprecated()
    protected CollideShapeBodyCollector(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static CollideShapeBodyCollector native_new() {
        return new CollideShapeBodyCollector((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.softbody.natives.JNI_CollideShapeBodyCollector.internal_native_deleteNative(this_addr);
    }

    public void ResetNative() {
        internal_native_ResetNative(native_address);
    }

    public static void internal_native_ResetNative(long this_addr) {
        jolt.physics.softbody.natives.JNI_CollideShapeBodyCollector.internal_native_ResetNative(this_addr);
    }

    public void SetContext(TransformedShape inContext) {
        internal_native_SetContext(native_address, inContext.native_address);
    }

    public static void internal_native_SetContext(long this_addr, long inContext_addr) {
        jolt.physics.softbody.natives.JNI_CollideShapeBodyCollector.internal_native_SetContext(this_addr, inContext_addr);
    }

    public TransformedShape GetContext() {
        long addr = internal_native_GetContext_addr(native_address);
        if (addr == 0)
            return TransformedShape.NULL;
        if (TransformedShape_TEMP_GEN_0 == null)
            TransformedShape_TEMP_GEN_0 = TransformedShape.native_new();
        TransformedShape_TEMP_GEN_0.internal_reset(addr, false);
        return TransformedShape_TEMP_GEN_0;
    }

    public static long internal_native_GetContext_addr(long this_addr) {
        return jolt.physics.softbody.natives.JNI_CollideShapeBodyCollector.internal_native_GetContext_addr(this_addr);
    }

    public void UpdateEarlyOutFraction(float inFraction) {
        internal_native_UpdateEarlyOutFraction(native_address, inFraction);
    }

    public static void internal_native_UpdateEarlyOutFraction(long this_addr, float inFraction) {
        jolt.physics.softbody.natives.JNI_CollideShapeBodyCollector.internal_native_UpdateEarlyOutFraction(this_addr, inFraction);
    }

    public void ResetEarlyOutFraction(float inFraction) {
        internal_native_ResetEarlyOutFraction(native_address, inFraction);
    }

    public static void internal_native_ResetEarlyOutFraction(long this_addr, float inFraction) {
        jolt.physics.softbody.natives.JNI_CollideShapeBodyCollector.internal_native_ResetEarlyOutFraction(this_addr, inFraction);
    }

    public void ResetEarlyOutFraction() {
        internal_native_ResetEarlyOutFraction(native_address);
    }

    public static void internal_native_ResetEarlyOutFraction(long this_addr) {
        jolt.physics.softbody.natives.JNI_CollideShapeBodyCollector.internal_native_ResetEarlyOutFraction(this_addr);
    }

    public void ForceEarlyOut() {
        internal_native_ForceEarlyOut(native_address);
    }

    public static void internal_native_ForceEarlyOut(long this_addr) {
        jolt.physics.softbody.natives.JNI_CollideShapeBodyCollector.internal_native_ForceEarlyOut(this_addr);
    }

    public boolean ShouldEarlyOut() {
        return internal_native_ShouldEarlyOut(native_address);
    }

    public static boolean internal_native_ShouldEarlyOut(long this_addr) {
        return jolt.physics.softbody.natives.JNI_CollideShapeBodyCollector.internal_native_ShouldEarlyOut(this_addr);
    }

    public float GetEarlyOutFraction() {
        return internal_native_GetEarlyOutFraction(native_address);
    }

    public static float internal_native_GetEarlyOutFraction(long this_addr) {
        return jolt.physics.softbody.natives.JNI_CollideShapeBodyCollector.internal_native_GetEarlyOutFraction(this_addr);
    }

    public float GetPositiveEarlyOutFraction() {
        return internal_native_GetPositiveEarlyOutFraction(native_address);
    }

    public static float internal_native_GetPositiveEarlyOutFraction(long this_addr) {
        return jolt.physics.softbody.natives.JNI_CollideShapeBodyCollector.internal_native_GetPositiveEarlyOutFraction(this_addr);
    }

    public CollideShapeBodyCollector() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        internal_native_setupCallback(native_address);
    }

    protected void Reset() {
    }

    private void internal_Reset() {
        Reset();
    }

    protected void AddHit(BodyID inResult) {
    }

    private void internal_AddHit(long inResult_addr) {
        if (BodyID_TEMP_STATIC_GEN_0 == null)
            BodyID_TEMP_STATIC_GEN_0 = BodyID.native_new();
        BodyID_TEMP_STATIC_GEN_0.internal_reset(inResult_addr, false);
        AddHit(BodyID_TEMP_STATIC_GEN_0);
    }

    public static long internal_native_create_addr() {
        return jolt.physics.softbody.natives.JNI_CollideShapeBodyCollector.internal_native_create_addr();
    }

    public native void internal_native_setupCallback(long this_addr);
}
