/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.natives;

import jolt.*;

final public class JNI_CharacterSettings {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_get_mLayer(long this_addr);

    public static native void internal_native_set_mLayer(long this_addr, int mLayer);

    public static native float internal_native_get_mMass(long this_addr);

    public static native void internal_native_set_mMass(long this_addr, float mMass);

    public static native float internal_native_get_mFriction(long this_addr);

    public static native void internal_native_set_mFriction(long this_addr, float mFriction);

    public static native float internal_native_get_mGravityFactor(long this_addr);

    public static native void internal_native_set_mGravityFactor(long this_addr, float mGravityFactor);

    public static native int internal_native_get_mAllowedDOFs(long this_addr);

    public static native void internal_native_set_mAllowedDOFs(long this_addr, int mAllowedDOFs);
}
