/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt;

import jolt.physics.StateRecorder;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import com.github.xpenatan.jParser.api.NativeObject;

public class StateRecorderEm extends StateRecorder {

    static private NativeObject NativeObject_TEMP_STATIC_GEN_0;

    static private NativeObject NativeObject_TEMP_STATIC_GEN_1;

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_ReadBytes = java.lang.invoke.MethodType.methodType(void.class, long.class, int.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_ReadBytes = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_INT);

    private static final java.lang.invoke.MethodType callbackMethodType_WriteBytes = java.lang.invoke.MethodType.methodType(void.class, long.class, int.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_WriteBytes = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_INT);

    private static final java.lang.invoke.MethodType callbackMethodType_IsEOF = java.lang.invoke.MethodType.methodType(boolean.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_IsEOF = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_BOOLEAN);

    private static final java.lang.invoke.MethodType callbackMethodType_IsFailed = java.lang.invoke.MethodType.methodType(boolean.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_IsFailed = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_BOOLEAN);

    static public final StateRecorderEm NULL = StateRecorderEm.native_new();

    @Deprecated()
    protected StateRecorderEm(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static StateRecorderEm native_new() {
        return new StateRecorderEm((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public StateRecorderEm() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_ReadBytes = callbackLookup.findVirtual(StateRecorderEm.class, "internal_ReadBytes", callbackMethodType_ReadBytes).bindTo(this);
            upcallStub_ReadBytes = callbackLinker.upcallStub(mh_ReadBytes, callbackDescriptor_ReadBytes, upcallArena);
            java.lang.invoke.MethodHandle mh_WriteBytes = callbackLookup.findVirtual(StateRecorderEm.class, "internal_WriteBytes", callbackMethodType_WriteBytes).bindTo(this);
            upcallStub_WriteBytes = callbackLinker.upcallStub(mh_WriteBytes, callbackDescriptor_WriteBytes, upcallArena);
            java.lang.invoke.MethodHandle mh_IsEOF = callbackLookup.findVirtual(StateRecorderEm.class, "internal_IsEOF", callbackMethodType_IsEOF).bindTo(this);
            upcallStub_IsEOF = callbackLinker.upcallStub(mh_IsEOF, callbackDescriptor_IsEOF, upcallArena);
            java.lang.invoke.MethodHandle mh_IsFailed = callbackLookup.findVirtual(StateRecorderEm.class, "internal_IsFailed", callbackMethodType_IsFailed).bindTo(this);
            upcallStub_IsFailed = callbackLinker.upcallStub(mh_IsFailed, callbackDescriptor_IsFailed, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_ReadBytes.address(), upcallStub_WriteBytes.address(), upcallStub_IsEOF.address(), upcallStub_IsFailed.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected void ReadBytes(NativeObject outData, int inNumBytes) {
    }

    private void internal_ReadBytes(long outData_addr, int inNumBytes) {
        if (NativeObject_TEMP_STATIC_GEN_0 == null)
            NativeObject_TEMP_STATIC_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_STATIC_GEN_0.internal_reset(outData_addr, false);
        ReadBytes(NativeObject_TEMP_STATIC_GEN_0, inNumBytes);
    }

    protected void WriteBytes(NativeObject inData, int inNumBytes) {
    }

    private void internal_WriteBytes(long inData_addr, int inNumBytes) {
        if (NativeObject_TEMP_STATIC_GEN_1 == null)
            NativeObject_TEMP_STATIC_GEN_1 = NativeObject.native_new();
        NativeObject_TEMP_STATIC_GEN_1.internal_reset(inData_addr, false);
        WriteBytes(NativeObject_TEMP_STATIC_GEN_1, inNumBytes);
    }

    protected boolean IsEOF() {
        return false;
    }

    private boolean internal_IsEOF() {
        return IsEOF();
    }

    protected boolean IsFailed() {
        return false;
    }

    private boolean internal_IsFailed() {
        return IsFailed();
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_ReadBytes;

    private MemorySegment upcallStub_WriteBytes;

    private MemorySegment upcallStub_IsEOF;

    private MemorySegment upcallStub_IsFailed;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_ReadBytes = null;
        upcallStub_WriteBytes = null;
        upcallStub_IsEOF = null;
        upcallStub_IsFailed = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long ReadBytes_fp, long WriteBytes_fp, long IsEOF_fp, long IsFailed_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJJJJ.invokeExact(this_addr, ReadBytes_fp, WriteBytes_fp, IsEOF_fp, IsFailed_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_staterecorderem_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_staterecorderem_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJJJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_staterecorderem_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
