/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.physics.vehicle.WheeledVehicleController;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class WheeledVehicleControllerCallbacksEm extends NativeObject {

    static private TireMaxImpulseCallbackResult TireMaxImpulseCallbackResult_TEMP_STATIC_GEN_0;

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_OnTireMaxImpulseCallback = java.lang.invoke.MethodType.methodType(void.class, int.class, long.class, float.class, float.class, float.class, float.class, float.class, float.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_OnTireMaxImpulseCallback = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_FLOAT);

    static public final WheeledVehicleControllerCallbacksEm NULL = WheeledVehicleControllerCallbacksEm.native_new();

    @Deprecated()
    protected WheeledVehicleControllerCallbacksEm(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WheeledVehicleControllerCallbacksEm native_new() {
        return new WheeledVehicleControllerCallbacksEm((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetWheeledVehicleController(WheeledVehicleController inController) {
        internal_native_SetWheeledVehicleController(native_address, inController.native_address);
    }

    public static void internal_native_SetWheeledVehicleController(long this_addr, long inController_addr) {
        try {
            FFMHandles.internal_native_SetWheeledVehicleController__JJ.invokeExact(this_addr, inController_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public WheeledVehicleControllerCallbacksEm() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_OnTireMaxImpulseCallback = callbackLookup.findVirtual(WheeledVehicleControllerCallbacksEm.class, "internal_OnTireMaxImpulseCallback", callbackMethodType_OnTireMaxImpulseCallback).bindTo(this);
            upcallStub_OnTireMaxImpulseCallback = callbackLinker.upcallStub(mh_OnTireMaxImpulseCallback, callbackDescriptor_OnTireMaxImpulseCallback, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_OnTireMaxImpulseCallback.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected void OnTireMaxImpulseCallback(int inWheelIndex, TireMaxImpulseCallbackResult outResult, float inSuspensionImpulse, float inLongitudinalFriction, float inLateralFriction, float inLongitudinalSlip, float inLateralSlip, float inDeltaTime) {
    }

    private void internal_OnTireMaxImpulseCallback(int inWheelIndex, long outResult_addr, float inSuspensionImpulse, float inLongitudinalFriction, float inLateralFriction, float inLongitudinalSlip, float inLateralSlip, float inDeltaTime) {
        if (TireMaxImpulseCallbackResult_TEMP_STATIC_GEN_0 == null)
            TireMaxImpulseCallbackResult_TEMP_STATIC_GEN_0 = TireMaxImpulseCallbackResult.native_new();
        TireMaxImpulseCallbackResult_TEMP_STATIC_GEN_0.internal_reset(outResult_addr, false);
        OnTireMaxImpulseCallback(inWheelIndex, TireMaxImpulseCallbackResult_TEMP_STATIC_GEN_0, inSuspensionImpulse, inLongitudinalFriction, inLateralFriction, inLongitudinalSlip, inLateralSlip, inDeltaTime);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_OnTireMaxImpulseCallback;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_OnTireMaxImpulseCallback = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long OnTireMaxImpulseCallback_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJ.invokeExact(this_addr, OnTireMaxImpulseCallback_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_wheeledvehiclecontrollercallbacksem_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetWheeledVehicleController__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_wheeledvehiclecontrollercallbacksem_setwheeledvehiclecontroller", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_wheeledvehiclecontrollercallbacksem_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_wheeledvehiclecontrollercallbacksem_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
