/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle.natives;

import jolt.physics.vehicle.*;

final public class JNI_VehicleTrackSettings {

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_get_mDrivenWheel(long this_addr);

    public static native void internal_native_set_mDrivenWheel(long this_addr, int mDrivenWheel);

    public static native long internal_native_get_mWheels_addr(long this_addr);

    public static native void internal_native_set_mWheels(long this_addr, long mWheels_addr);

    public static native float internal_native_get_mInertia(long this_addr);

    public static native void internal_native_set_mInertia(long this_addr, float mInertia);

    public static native float internal_native_get_mAngularDamping(long this_addr);

    public static native void internal_native_set_mAngularDamping(long this_addr, float mAngularDamping);

    public static native float internal_native_get_mMaxBrakeTorque(long this_addr);

    public static native void internal_native_set_mMaxBrakeTorque(long this_addr, float mMaxBrakeTorque);

    public static native float internal_native_get_mDifferentialRatio(long this_addr);

    public static native void internal_native_set_mDifferentialRatio(long this_addr, float mDifferentialRatio);
}
