/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle.natives;

import jolt.physics.vehicle.*;

final public class JNI_VehicleCollisionTesterCastSphere {

    public static native long internal_native_create_int_float_Vec3_float_addr(int inObjectLayer, float inRadius, long inUp_addr, float inMaxSlopeAngle);

    public static native long internal_native_create_int_float_Vec3_addr(int inObjectLayer, float inRadius, long inUp_addr);

    public static native long internal_native_create_int_float_addr(int inObjectLayer, float inRadius);

    public static native void internal_native_deleteNative(long this_addr);
}
