/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle.natives;

import jolt.physics.vehicle.*;

final public class JNI_MotorcycleControllerSettings {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native float internal_native_get_mMaxLeanAngle(long this_addr);

    public static native void internal_native_set_mMaxLeanAngle(long this_addr, float mMaxLeanAngle);

    public static native float internal_native_get_mLeanSpringConstant(long this_addr);

    public static native void internal_native_set_mLeanSpringConstant(long this_addr, float mLeanSpringConstant);

    public static native float internal_native_get_mLeanSpringDamping(long this_addr);

    public static native void internal_native_set_mLeanSpringDamping(long this_addr, float mLeanSpringDamping);

    public static native float internal_native_get_mLeanSpringIntegrationCoefficient(long this_addr);

    public static native void internal_native_set_mLeanSpringIntegrationCoefficient(long this_addr, float mLeanSpringIntegrationCoefficient);

    public static native float internal_native_get_mLeanSpringIntegrationCoefficientDecay(long this_addr);

    public static native void internal_native_set_mLeanSpringIntegrationCoefficientDecay(long this_addr, float mLeanSpringIntegrationCoefficientDecay);

    public static native float internal_native_get_mLeanSmoothingFactor(long this_addr);

    public static native void internal_native_set_mLeanSmoothingFactor(long this_addr, float mLeanSmoothingFactor);
}
