/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle.natives;

import jolt.physics.vehicle.*;

final public class JNI_VehicleController {

    public static native long internal_native_GetConstraint_addr(long this_addr);
}
