/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle.natives;

import jolt.physics.vehicle.*;

final public class JNI_VehicleAntiRollBar {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_get_mLeftWheel(long this_addr);

    public static native void internal_native_set_mLeftWheel(long this_addr, int mLeftWheel);

    public static native int internal_native_get_mRightWheel(long this_addr);

    public static native void internal_native_set_mRightWheel(long this_addr, int mRightWheel);

    public static native float internal_native_get_mStiffness(long this_addr);

    public static native void internal_native_set_mStiffness(long this_addr, float mStiffness);
}
