/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.math.natives;

import jolt.math.*;

final public class JNI_TwoBodyConstraintSettings {

    public static native long internal_native_Create_addr(long this_addr, long inBody1_addr, long inBody2_addr);
}
