/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.math.natives;

import jolt.math.*;

final public class JNI_Float2 {

    public static native long internal_native_create_float_float_addr(float inX, float inY);

    public static native void internal_native_deleteNative(long this_addr);

    public static native float internal_native_get_x(long this_addr);

    public static native void internal_native_set_x(long this_addr, float x);

    public static native float internal_native_get_y(long this_addr);

    public static native void internal_native_set_y(long this_addr, float y);
}
