/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.math.natives;

import jolt.math.*;

final public class JNI_Quat {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_float_float_float_float_addr(float inX, float inY, float inZ, float inW);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_sZero_addr();

    public static native long internal_native_sIdentity_addr();

    public static native long internal_native_sRotation_addr(long inRotation_addr, float inAngle);

    public static native long internal_native_sFromTo_addr(long inFrom_addr, long inTo_addr);

    public static native boolean internal_native_Equals(long this_addr, long inQ_addr);

    public static native boolean internal_native_NotEquals(long this_addr, long inQ_addr);

    public static native long internal_native_Set__0_addr(long this_addr, long other_addr);

    public static native long internal_native_MulQuat_addr(long this_addr, long inQ_addr);

    public static native long internal_native_MulVec3_addr(long this_addr, long inV_addr);

    public static native long internal_native_MulFloat_addr(long this_addr, float inV);

    public static native boolean internal_native_IsClose(long this_addr, long inQ_addr, float inMaxDistSq);

    public static native boolean internal_native_IsClose(long this_addr, long inQ_addr);

    public static native boolean internal_native_IsNormalized(long this_addr, float inTolerance);

    public static native boolean internal_native_IsNormalized(long this_addr);

    public static native float internal_native_Length(long this_addr);

    public static native float internal_native_LengthSq(long this_addr);

    public static native long internal_native_Normalized_addr(long this_addr);

    public static native long internal_native_sEulerAngles_addr(long inInput_addr);

    public static native long internal_native_GetEulerAngles_addr(long this_addr);

    public static native float internal_native_GetX(long this_addr);

    public static native float internal_native_GetY(long this_addr);

    public static native float internal_native_GetZ(long this_addr);

    public static native float internal_native_GetW(long this_addr);

    public static native long internal_native_GetXYZ_addr(long this_addr);

    public static native void internal_native_SetX(long this_addr, float inX);

    public static native void internal_native_SetY(long this_addr, float inY);

    public static native void internal_native_SetZ(long this_addr, float inZ);

    public static native void internal_native_SetW(long this_addr, float inW);

    public static native void internal_native_Set(long this_addr, float inX, float inY, float inZ, float inW);

    public static native long internal_native_InverseRotate_addr(long this_addr, long inV_addr);

    public static native long internal_native_RotateAxisX_addr(long this_addr);

    public static native long internal_native_RotateAxisY_addr(long this_addr);

    public static native long internal_native_RotateAxisZ_addr(long this_addr);

    public static native float internal_native_Dot(long this_addr, long inQ_addr);

    public static native long internal_native_Conjugated_addr(long this_addr);

    public static native long internal_native_Inversed_addr(long this_addr);

    public static native long internal_native_EnsureWPositive_addr(long this_addr);

    public static native long internal_native_GetPerpendicular_addr(long this_addr);

    public static native float internal_native_GetRotationAngle(long this_addr, long inAxis_addr);

    public static native long internal_native_GetTwist_addr(long this_addr, long inAxis_addr);

    public static native void internal_native_GetSwingTwist(long this_addr, long outSwing_addr, long outTwist_addr);

    public static native long internal_native_LERP_addr(long this_addr, long inDestination_addr, float inFraction);

    public static native long internal_native_SLERP_addr(long this_addr, long inDestination_addr, float inFraction);
}
