/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.enums.ETireFrictionDirection;
import jolt.physics.body.Body;
import jolt.physics.collision.shape.SubShapeID;
import jolt.physics.PhysicsStepListenerContext;

public class VehicleConstraintCallbacksEm extends NativeObject {

    static private Body Body_TEMP_STATIC_GEN_0;

    static private SubShapeID SubShapeID_TEMP_STATIC_GEN_0;

    static private VehicleConstraint VehicleConstraint_TEMP_STATIC_GEN_0;

    static private PhysicsStepListenerContext PhysicsStepListenerContext_TEMP_STATIC_GEN_0;

    static private VehicleConstraint VehicleConstraint_TEMP_STATIC_GEN_1;

    static private PhysicsStepListenerContext PhysicsStepListenerContext_TEMP_STATIC_GEN_1;

    static private VehicleConstraint VehicleConstraint_TEMP_STATIC_GEN_2;

    static private PhysicsStepListenerContext PhysicsStepListenerContext_TEMP_STATIC_GEN_2;

    static public final VehicleConstraintCallbacksEm NULL = VehicleConstraintCallbacksEm.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VehicleConstraintCallbacksEm(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static VehicleConstraintCallbacksEm native_new() {
        return new VehicleConstraintCallbacksEm((byte) 0, (char) 0);
    }

    public void SetVehicleConstraint(VehicleConstraint inConstraint) {
    }

    public VehicleConstraintCallbacksEm() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
    }

    protected float GetCombinedFriction(int inWheelIndex, ETireFrictionDirection inTireFrictionDirection, float inTireFriction, Body inBody2, SubShapeID inSubShapeID2) {
        return 0;
    }

    private float internal_GetCombinedFriction(int inWheelIndex, int inTireFrictionDirection_addr, float inTireFriction, long inBody2_addr, long inSubShapeID2_addr) {
        ETireFrictionDirection inTireFrictionDirection_addr_enum = ETireFrictionDirection.CUSTOM.setValue(inTireFrictionDirection_addr);
        ETireFrictionDirection[] inTireFrictionDirection_addr_enum_values = ETireFrictionDirection.values();
        for (int i = 0; i < inTireFrictionDirection_addr_enum_values.length; i++) {
            ETireFrictionDirection enumVal = inTireFrictionDirection_addr_enum_values[i];
            if (enumVal != ETireFrictionDirection.CUSTOM && enumVal.getValue() == inTireFrictionDirection_addr) {
                inTireFrictionDirection_addr_enum = inTireFrictionDirection_addr_enum_values[i];
                break;
            }
        }
        if (Body_TEMP_STATIC_GEN_0 == null)
            Body_TEMP_STATIC_GEN_0 = Body.native_new();
        Body_TEMP_STATIC_GEN_0.internal_reset(inBody2_addr, false);
        if (SubShapeID_TEMP_STATIC_GEN_0 == null)
            SubShapeID_TEMP_STATIC_GEN_0 = SubShapeID.native_new();
        SubShapeID_TEMP_STATIC_GEN_0.internal_reset(inSubShapeID2_addr, false);
        return GetCombinedFriction(inWheelIndex, inTireFrictionDirection_addr_enum, inTireFriction, Body_TEMP_STATIC_GEN_0, SubShapeID_TEMP_STATIC_GEN_0);
    }

    protected void OnPreStepCallback(VehicleConstraint inVehicle, PhysicsStepListenerContext inContext) {
    }

    private void internal_OnPreStepCallback(long inVehicle_addr, long inContext_addr) {
        if (VehicleConstraint_TEMP_STATIC_GEN_0 == null)
            VehicleConstraint_TEMP_STATIC_GEN_0 = VehicleConstraint.native_new();
        VehicleConstraint_TEMP_STATIC_GEN_0.internal_reset(inVehicle_addr, false);
        if (PhysicsStepListenerContext_TEMP_STATIC_GEN_0 == null)
            PhysicsStepListenerContext_TEMP_STATIC_GEN_0 = PhysicsStepListenerContext.native_new();
        PhysicsStepListenerContext_TEMP_STATIC_GEN_0.internal_reset(inContext_addr, false);
        OnPreStepCallback(VehicleConstraint_TEMP_STATIC_GEN_0, PhysicsStepListenerContext_TEMP_STATIC_GEN_0);
    }

    protected void OnPostCollideCallback(VehicleConstraint inVehicle, PhysicsStepListenerContext inContext) {
    }

    private void internal_OnPostCollideCallback(long inVehicle_addr, long inContext_addr) {
        if (VehicleConstraint_TEMP_STATIC_GEN_1 == null)
            VehicleConstraint_TEMP_STATIC_GEN_1 = VehicleConstraint.native_new();
        VehicleConstraint_TEMP_STATIC_GEN_1.internal_reset(inVehicle_addr, false);
        if (PhysicsStepListenerContext_TEMP_STATIC_GEN_1 == null)
            PhysicsStepListenerContext_TEMP_STATIC_GEN_1 = PhysicsStepListenerContext.native_new();
        PhysicsStepListenerContext_TEMP_STATIC_GEN_1.internal_reset(inContext_addr, false);
        OnPostCollideCallback(VehicleConstraint_TEMP_STATIC_GEN_1, PhysicsStepListenerContext_TEMP_STATIC_GEN_1);
    }

    protected void OnPostStepCallback(VehicleConstraint inVehicle, PhysicsStepListenerContext inContext) {
    }

    private void internal_OnPostStepCallback(long inVehicle_addr, long inContext_addr) {
        if (VehicleConstraint_TEMP_STATIC_GEN_2 == null)
            VehicleConstraint_TEMP_STATIC_GEN_2 = VehicleConstraint.native_new();
        VehicleConstraint_TEMP_STATIC_GEN_2.internal_reset(inVehicle_addr, false);
        if (PhysicsStepListenerContext_TEMP_STATIC_GEN_2 == null)
            PhysicsStepListenerContext_TEMP_STATIC_GEN_2 = PhysicsStepListenerContext.native_new();
        PhysicsStepListenerContext_TEMP_STATIC_GEN_2.internal_reset(inContext_addr, false);
        OnPostStepCallback(VehicleConstraint_TEMP_STATIC_GEN_2, PhysicsStepListenerContext_TEMP_STATIC_GEN_2);
    }

    public static native long internal_native_create_addr();
}
