/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.physics.body.BodyID;
import jolt.math.Vec3;

public class Wheel extends NativeObject {

    static public final Wheel NULL = Wheel.native_new();

    public Wheel(WheelSettings inSettings) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected Wheel(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static Wheel native_new() {
        return new Wheel((byte) 0, (char) 0);
    }

    public WheelSettings GetSettings() {
        return null;
    }

    public float GetAngularVelocity() {
        return 0;
    }

    public void SetAngularVelocity(float inVel) {
    }

    public float GetRotationAngle() {
        return 0;
    }

    public void SetRotationAngle(float inAngle) {
    }

    public float GetSteerAngle() {
        return 0;
    }

    public void SetSteerAngle(float inAngle) {
    }

    public boolean HasContact() {
        return false;
    }

    public BodyID GetContactBodyID() {
        return null;
    }

    public Vec3 GetContactPosition() {
        return null;
    }

    public Vec3 GetContactPointVelocity() {
        return null;
    }

    public Vec3 GetContactNormal() {
        return null;
    }

    public Vec3 GetContactLongitudinal() {
        return null;
    }

    public Vec3 GetContactLateral() {
        return null;
    }

    public float GetSuspensionLength() {
        return 0;
    }

    public boolean HasHitHardPoint() {
        return false;
    }

    public float GetSuspensionLambda() {
        return 0;
    }

    public float GetLongitudinalLambda() {
        return 0;
    }

    public float GetLateralLambda() {
        return 0;
    }
}
