/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.math.ArrayUint;

public class VehicleTrackSettings extends NativeObject {

    private ArrayUint ArrayUint_TEMP_GEN_0;

    static public final VehicleTrackSettings NULL = VehicleTrackSettings.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VehicleTrackSettings(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static VehicleTrackSettings native_new() {
        return new VehicleTrackSettings((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.vehicle.natives.JNI_VehicleTrackSettings.internal_native_deleteNative(this_addr);
    }

    public int get_mDrivenWheel() {
        return internal_native_get_mDrivenWheel(native_address);
    }

    public static int internal_native_get_mDrivenWheel(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_VehicleTrackSettings.internal_native_get_mDrivenWheel(this_addr);
    }

    public void set_mDrivenWheel(int mDrivenWheel) {
        internal_native_set_mDrivenWheel(native_address, mDrivenWheel);
    }

    public static void internal_native_set_mDrivenWheel(long this_addr, int mDrivenWheel) {
        jolt.physics.vehicle.natives.JNI_VehicleTrackSettings.internal_native_set_mDrivenWheel(this_addr, mDrivenWheel);
    }

    public ArrayUint get_mWheels() {
        long addr = internal_native_get_mWheels_addr(native_address);
        if (addr == 0)
            return ArrayUint.NULL;
        if (ArrayUint_TEMP_GEN_0 == null)
            ArrayUint_TEMP_GEN_0 = ArrayUint.native_new();
        ArrayUint_TEMP_GEN_0.internal_reset(addr, false);
        return ArrayUint_TEMP_GEN_0;
    }

    public static long internal_native_get_mWheels_addr(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_VehicleTrackSettings.internal_native_get_mWheels_addr(this_addr);
    }

    public void set_mWheels(ArrayUint mWheels) {
        internal_native_set_mWheels(native_address, mWheels.native_address);
    }

    public static void internal_native_set_mWheels(long this_addr, long mWheels_addr) {
        jolt.physics.vehicle.natives.JNI_VehicleTrackSettings.internal_native_set_mWheels(this_addr, mWheels_addr);
    }

    public float get_mInertia() {
        return internal_native_get_mInertia(native_address);
    }

    public static float internal_native_get_mInertia(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_VehicleTrackSettings.internal_native_get_mInertia(this_addr);
    }

    public void set_mInertia(float mInertia) {
        internal_native_set_mInertia(native_address, mInertia);
    }

    public static void internal_native_set_mInertia(long this_addr, float mInertia) {
        jolt.physics.vehicle.natives.JNI_VehicleTrackSettings.internal_native_set_mInertia(this_addr, mInertia);
    }

    public float get_mAngularDamping() {
        return internal_native_get_mAngularDamping(native_address);
    }

    public static float internal_native_get_mAngularDamping(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_VehicleTrackSettings.internal_native_get_mAngularDamping(this_addr);
    }

    public void set_mAngularDamping(float mAngularDamping) {
        internal_native_set_mAngularDamping(native_address, mAngularDamping);
    }

    public static void internal_native_set_mAngularDamping(long this_addr, float mAngularDamping) {
        jolt.physics.vehicle.natives.JNI_VehicleTrackSettings.internal_native_set_mAngularDamping(this_addr, mAngularDamping);
    }

    public float get_mMaxBrakeTorque() {
        return internal_native_get_mMaxBrakeTorque(native_address);
    }

    public static float internal_native_get_mMaxBrakeTorque(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_VehicleTrackSettings.internal_native_get_mMaxBrakeTorque(this_addr);
    }

    public void set_mMaxBrakeTorque(float mMaxBrakeTorque) {
        internal_native_set_mMaxBrakeTorque(native_address, mMaxBrakeTorque);
    }

    public static void internal_native_set_mMaxBrakeTorque(long this_addr, float mMaxBrakeTorque) {
        jolt.physics.vehicle.natives.JNI_VehicleTrackSettings.internal_native_set_mMaxBrakeTorque(this_addr, mMaxBrakeTorque);
    }

    public float get_mDifferentialRatio() {
        return internal_native_get_mDifferentialRatio(native_address);
    }

    public static float internal_native_get_mDifferentialRatio(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_VehicleTrackSettings.internal_native_get_mDifferentialRatio(this_addr);
    }

    public void set_mDifferentialRatio(float mDifferentialRatio) {
        internal_native_set_mDifferentialRatio(native_address, mDifferentialRatio);
    }

    public static void internal_native_set_mDifferentialRatio(long this_addr, float mDifferentialRatio) {
        jolt.physics.vehicle.natives.JNI_VehicleTrackSettings.internal_native_set_mDifferentialRatio(this_addr, mDifferentialRatio);
    }
}
