/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.physics.body.BodyID;
import jolt.math.Vec3;

public class Wheel extends NativeObject {

    private WheelSettings WheelSettings_TEMP_GEN_0;

    private BodyID BodyID_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_1;

    private Vec3 Vec3_TEMP_GEN_2;

    private Vec3 Vec3_TEMP_GEN_3;

    private Vec3 Vec3_TEMP_GEN_4;

    static public final Wheel NULL = Wheel.native_new();

    public Wheel(WheelSettings inSettings) {
        long addr = internal_native_create_WheelSettings_addr(inSettings.native_address);
        internal_reset(addr, true);
    }

    public static long internal_native_create_WheelSettings_addr(long inSettings_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_create_WheelSettings_addr(inSettings_addr);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected Wheel(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static Wheel native_new() {
        return new Wheel((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.vehicle.natives.JNI_Wheel.internal_native_deleteNative(this_addr);
    }

    public WheelSettings GetSettings() {
        long addr = internal_native_GetSettings_addr(native_address);
        if (addr == 0)
            return WheelSettings.NULL;
        if (WheelSettings_TEMP_GEN_0 == null)
            WheelSettings_TEMP_GEN_0 = WheelSettings.native_new();
        WheelSettings_TEMP_GEN_0.internal_reset(addr, false);
        return WheelSettings_TEMP_GEN_0;
    }

    public static long internal_native_GetSettings_addr(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_GetSettings_addr(this_addr);
    }

    public float GetAngularVelocity() {
        return internal_native_GetAngularVelocity(native_address);
    }

    public static float internal_native_GetAngularVelocity(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_GetAngularVelocity(this_addr);
    }

    public void SetAngularVelocity(float inVel) {
        internal_native_SetAngularVelocity(native_address, inVel);
    }

    public static void internal_native_SetAngularVelocity(long this_addr, float inVel) {
        jolt.physics.vehicle.natives.JNI_Wheel.internal_native_SetAngularVelocity(this_addr, inVel);
    }

    public float GetRotationAngle() {
        return internal_native_GetRotationAngle(native_address);
    }

    public static float internal_native_GetRotationAngle(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_GetRotationAngle(this_addr);
    }

    public void SetRotationAngle(float inAngle) {
        internal_native_SetRotationAngle(native_address, inAngle);
    }

    public static void internal_native_SetRotationAngle(long this_addr, float inAngle) {
        jolt.physics.vehicle.natives.JNI_Wheel.internal_native_SetRotationAngle(this_addr, inAngle);
    }

    public float GetSteerAngle() {
        return internal_native_GetSteerAngle(native_address);
    }

    public static float internal_native_GetSteerAngle(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_GetSteerAngle(this_addr);
    }

    public void SetSteerAngle(float inAngle) {
        internal_native_SetSteerAngle(native_address, inAngle);
    }

    public static void internal_native_SetSteerAngle(long this_addr, float inAngle) {
        jolt.physics.vehicle.natives.JNI_Wheel.internal_native_SetSteerAngle(this_addr, inAngle);
    }

    public boolean HasContact() {
        return internal_native_HasContact(native_address);
    }

    public static boolean internal_native_HasContact(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_HasContact(this_addr);
    }

    public BodyID GetContactBodyID() {
        long addr = internal_native_GetContactBodyID_addr(native_address);
        if (addr == 0)
            return BodyID.NULL;
        if (BodyID_TEMP_GEN_0 == null)
            BodyID_TEMP_GEN_0 = BodyID.native_new();
        BodyID_TEMP_GEN_0.internal_reset(addr, false);
        return BodyID_TEMP_GEN_0;
    }

    public static long internal_native_GetContactBodyID_addr(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_GetContactBodyID_addr(this_addr);
    }

    public Vec3 GetContactPosition() {
        long addr = internal_native_GetContactPosition_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = Vec3.native_new();
        Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetContactPosition_addr(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_GetContactPosition_addr(this_addr);
    }

    public Vec3 GetContactPointVelocity() {
        long addr = internal_native_GetContactPointVelocity_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_1 == null)
            Vec3_TEMP_GEN_1 = Vec3.native_new();
        Vec3_TEMP_GEN_1.internal_reset(addr, false);
        return Vec3_TEMP_GEN_1;
    }

    public static long internal_native_GetContactPointVelocity_addr(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_GetContactPointVelocity_addr(this_addr);
    }

    public Vec3 GetContactNormal() {
        long addr = internal_native_GetContactNormal_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_2 == null)
            Vec3_TEMP_GEN_2 = Vec3.native_new();
        Vec3_TEMP_GEN_2.internal_reset(addr, false);
        return Vec3_TEMP_GEN_2;
    }

    public static long internal_native_GetContactNormal_addr(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_GetContactNormal_addr(this_addr);
    }

    public Vec3 GetContactLongitudinal() {
        long addr = internal_native_GetContactLongitudinal_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_3 == null)
            Vec3_TEMP_GEN_3 = Vec3.native_new();
        Vec3_TEMP_GEN_3.internal_reset(addr, false);
        return Vec3_TEMP_GEN_3;
    }

    public static long internal_native_GetContactLongitudinal_addr(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_GetContactLongitudinal_addr(this_addr);
    }

    public Vec3 GetContactLateral() {
        long addr = internal_native_GetContactLateral_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_4 == null)
            Vec3_TEMP_GEN_4 = Vec3.native_new();
        Vec3_TEMP_GEN_4.internal_reset(addr, false);
        return Vec3_TEMP_GEN_4;
    }

    public static long internal_native_GetContactLateral_addr(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_GetContactLateral_addr(this_addr);
    }

    public float GetSuspensionLength() {
        return internal_native_GetSuspensionLength(native_address);
    }

    public static float internal_native_GetSuspensionLength(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_GetSuspensionLength(this_addr);
    }

    public boolean HasHitHardPoint() {
        return internal_native_HasHitHardPoint(native_address);
    }

    public static boolean internal_native_HasHitHardPoint(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_HasHitHardPoint(this_addr);
    }

    public float GetSuspensionLambda() {
        return internal_native_GetSuspensionLambda(native_address);
    }

    public static float internal_native_GetSuspensionLambda(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_GetSuspensionLambda(this_addr);
    }

    public float GetLongitudinalLambda() {
        return internal_native_GetLongitudinalLambda(native_address);
    }

    public static float internal_native_GetLongitudinalLambda(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_GetLongitudinalLambda(this_addr);
    }

    public float GetLateralLambda() {
        return internal_native_GetLateralLambda(native_address);
    }

    public static float internal_native_GetLateralLambda(long this_addr) {
        return jolt.physics.vehicle.natives.JNI_Wheel.internal_native_GetLateralLambda(this_addr);
    }
}
