/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ECollectFacesMode implements NativeEnum<ECollectFacesMode> {

    CUSTOM(0), CollectFaces(ECollectFacesMode_CollectFaces_NATIVE()), NoFaces(ECollectFacesMode_NoFaces_NATIVE());

    private int value;

    private ECollectFacesMode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ECollectFacesMode setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ECollectFacesMode getCustom() {
        return CUSTOM;
    }

    private static int ECollectFacesMode_CollectFaces_NATIVE() {
        return jolt.enums.natives.JNI_ECollectFacesMode.ECollectFacesMode_CollectFaces_NATIVE();
    }

    private static int ECollectFacesMode_NoFaces_NATIVE() {
        return jolt.enums.natives.JNI_ECollectFacesMode.ECollectFacesMode_NoFaces_NATIVE();
    }
}
